import type { Locale } from "@/lib/i18n";

/** Hardcoded UI chrome strings (not CMS content). English is the key + fallback.
 *  hi/gu are AI-written — flag for review before go-live. */
export const UI_STRINGS: Record<string, { hi: string; gu: string }> = {
  "Learn more": { hi: "और जानें", gu: "વધુ જાણો" },
  "Patient Story": { hi: "मरीज़ की कहानी", gu: "દર્દીની વાર્તા" },
  "Use Calculator": { hi: "कैलकुलेटर उपयोग करें", gu: "કેલ્ક્યુલેટર વાપરો" },
  "View Centre": { hi: "सेंटर देखें", gu: "સેન્ટર જુઓ" },
  "View all awards & achievements": { hi: "सभी पुरस्कार और उपलब्धियाँ देखें", gu: "બધા એવોર્ડ અને સિદ્ધિઓ જુઓ" },
  "View More Events": { hi: "और कार्यक्रम देखें", gu: "વધુ કાર્યક્રમો જુઓ" },
  "Patient review": { hi: "मरीज़ की समीक्षा", gu: "દર્દીની સમીક્ષા" },
  "Google review": { hi: "Google समीक्षा", gu: "Google સમીક્ષા" },
  "* Terms and conditions apply.": { hi: "* नियम एवं शर्तें लागू।", gu: "* નિયમો અને શરતો લાગુ." },
  "Full Name *": { hi: "पूरा नाम *", gu: "પૂરું નામ *" },
  "Phone *": { hi: "फ़ोन *", gu: "ફોન *" },
  "Email": { hi: "ईमेल", gu: "ઇમેઇલ" },
  "Treatment of Interest": { hi: "रुचि का उपचार", gu: "રસની સારવાર" },
  "Preferred Centre": { hi: "पसंदीदा सेंटर", gu: "પસંદગીનું સેન્ટર" },
  "Message": { hi: "संदेश", gu: "સંદેશ" },
  "Sending…": { hi: "भेजा जा रहा है…", gu: "મોકલી રહ્યા છીએ…" },
  "Request a Callback": { hi: "कॉलबैक का अनुरोध करें", gu: "કૉલબેકની વિનંતી કરો" },
  "India's Trusted Fertility Experts · Since 1998": { hi: "भारत के विश्वसनीय फर्टिलिटी विशेषज्ञ · 1998 से", gu: "ભારતના વિશ્વસનીય ફર્ટિલિટી નિષ્ણાતો · 1998 થી" },
  "WhatsApp": { hi: "व्हाट्सऐप", gu: "વોટ્સએપ" },
  "24×7 Care": { hi: "24×7 देखभाल", gu: "24×7 સંભાળ" },
  "Book Consultation": { hi: "कंसल्टेशन बुक करें", gu: "કન્સલ્ટેશન બુક કરો" },
  "Check IVF Eligibility": { hi: "IVF पात्रता जांचें", gu: "IVF પાત્રતા ચકાસો" },
  "WhatsApp Now": { hi: "व्हाट्सऐप करें", gu: "વોટ્સએપ કરો" },
  "Call Now": { hi: "अभी कॉल करें", gu: "હમણાં કૉલ કરો" },

  // Contact page chrome
  "Home": { hi: "होम", gu: "હોમ" },
  "Contact Us": { hi: "संपर्क करें", gu: "અમારો સંપર્ક કરો" },
  "Call Us": { hi: "कॉल करें", gu: "કૉલ કરો" },
  "Chat with our team": { hi: "हमारी टीम से चैट करें", gu: "અમારી ટીમ સાથે ચેટ કરો" },
  "24×7 phone support — clinic visiting hours vary by centre": { hi: "24×7 फोन सपोर्ट — क्लिनिक विज़िटिंग आवर्स सेंटर के अनुसार अलग-अलग हैं", gu: "24×7 ફોન સપોર્ટ — ક્લિનિક વિઝિટિંગ અવર્સ સેન્ટર પ્રમાણે અલગ-અલગ છે" },
  "Quick replies, every day": { hi: "हर दिन त्वरित जवाब", gu: "દરરોજ ઝડપી જવાબ" },
  "We reply within 24 hours": { hi: "हम 24 घंटों के भीतर जवाब देते हैं", gu: "અમે 24 કલાકમાં જવાબ આપીએ છીએ" },
  "Our Network": { hi: "हमारा नेटवर्क", gu: "અમારું નેટવર્ક" },
  "Find a Bavishi Fertility Institute": { hi: "Bavishi Fertility Institute खोजें", gu: "Bavishi Fertility Institute શોધો" },
  "near you": { hi: "आपके पास", gu: "તમારી નજીક" },
  "14 fertility centres across 8 Indian cities — world-class care, close to home. Phone & WhatsApp support is available 24×7; centre visiting hours are listed below.": { hi: "8 भारतीय शहरों में 14 फर्टिलिटी सेंटर — विश्वस्तरीय देखभाल, घर के पास। फोन और व्हाट्सऐप सपोर्ट 24×7 उपलब्ध है; सेंटर के विज़िटिंग आवर्स नीचे दिए गए हैं।", gu: "8 ભારતીય શહેરોમાં 14 ફર્ટિલિટી સેન્ટર — વિશ્વસ્તરીય સંભાળ, ઘરની નજીક. ફોન અને વોટ્સએપ સપોર્ટ 24×7 ઉપલબ્ધ છે; સેન્ટરના વિઝિટિંગ અવર્સ નીચે આપેલા છે." },
  "Call": { hi: "कॉल", gu: "કૉલ" },
  "Directions": { hi: "दिशा-निर्देश", gu: "દિશા-નિર્દેશો" },
  "Need help choosing the right centre?": { hi: "सही सेंटर चुनने में मदद चाहिए?", gu: "યોગ્ય સેન્ટર પસંદ કરવામાં મદદ જોઈએ છે?" },
  "Our counsellors will guide you to the Bavishi Fertility Institute centre nearest you.": { hi: "हमारे काउंसलर आपको आपके नज़दीकी Bavishi Fertility Institute सेंटर तक मार्गदर्शन देंगे।", gu: "અમારા કાઉન્સેલર્સ તમને તમારા નજીકના Bavishi Fertility Institute સેન્ટર સુધી માર્ગદર્શન આપશે." },
  "FAQ": { hi: "सामान्य प्रश्न", gu: "વારંવાર પુછાતા પ્રશ્નો" },
  "Getting in touch —": { hi: "संपर्क करना —", gu: "સંપર્ક કરવો —" },
  "answered": { hi: "आसान बनाया गया", gu: "સરળ બનાવ્યું" },
  "Your journey to parenthood starts with": { hi: "पेरेंटहुड की आपकी यात्रा शुरू होती है", gu: "પેરેન્ટહુડની તમારી યાત્રા શરૂ થાય છે" },
  "one message.": { hi: "एक संदेश से।", gu: "એક સંદેશથી." },
  "WhatsApp Us": { hi: "व्हाट्सऐप करें", gu: "વોટ્સએપ કરો" },

  // Contact page hero + FAQ content (fallback copy — used when CMS has no hi/gu override)
  "We're here for you": { hi: "हम आपके लिए यहाँ हैं", gu: "અમે તમારા માટે અહીં છીએ" },
  "Contact": { hi: "संपर्क करें", gu: "સંપર્ક કરો" },
  "Have a question or ready to begin? Reach out — confidentially and without obligation. Our fertility counsellors are here to guide your very first step.": { hi: "कोई सवाल है या शुरुआत करने के लिए तैयार हैं? गोपनीय रूप से और बिना किसी दायित्व के संपर्क करें — हमारे फर्टिलिटी काउंसलर आपके पहले कदम में मार्गदर्शन के लिए यहाँ हैं।", gu: "કોઈ પ્રશ્ન છે અથવા શરૂઆત કરવા તૈયાર છો? ગોપનીય રીતે અને કોઈપણ જવાબદારી વિના સંપર્ક કરો — અમારા ફર્ટિલિટી કાઉન્સેલર્સ તમારા પ્રથમ પગલામાં માર્ગદર્શન આપવા માટે અહીં છે." },
  "How do I book an appointment at Bavishi Fertility Institute?": { hi: "मैं Bavishi Fertility Institute में अपॉइंटमेंट कैसे बुक करूं?", gu: "હું Bavishi Fertility Institute માં એપોઇન્ટમેન્ટ કેવી રીતે બુક કરું?" },
  "Fill in the enquiry form on this page, call us on +91 97126 22288, or message us on WhatsApp. Our team will help you choose the nearest centre and a convenient time.": { hi: "इस पेज पर पूछताछ फॉर्म भरें, हमें +91 97126 22288 पर कॉल करें, या व्हाट्सऐप पर संदेश भेजें। हमारी टीम आपको नज़दीकी सेंटर और सुविधाजनक समय चुनने में मदद करेगी।", gu: "આ પેજ પર પૂછપરછ ફોર્મ ભરો, અમને +91 97126 22288 પર કૉલ કરો, અથવા વોટ્સએપ પર સંદેશ મોકલો. અમારી ટીમ તમને નજીકનું સેન્ટર અને અનુકૂળ સમય પસંદ કરવામાં મદદ કરશે." },
  "Which Bavishi Fertility Institute centre is nearest to me?": { hi: "मेरे सबसे नज़दीक कौन सा Bavishi Fertility Institute सेंटर है?", gu: "મારી સૌથી નજીક કયું Bavishi Fertility Institute સેન્ટર છે?" },
  "We have 14 centres across 8 cities — Ahmedabad, Mumbai, Vadodara, Surat, Bhuj, Bhavnagar, Anand and Varanasi. Tell us your city and we'll connect you to the closest one.": { hi: "हमारे 8 शहरों — अहमदाबाद, मुंबई, वडोदरा, सूरत, भुज, भावनगर, आनंद और वाराणसी — में 14 सेंटर हैं। हमें अपना शहर बताएं, हम आपको सबसे नज़दीकी सेंटर से जोड़ देंगे।", gu: "અમારા 8 શહેરો — અમદાવાદ, મુંબઈ, વડોદરા, સુરત, ભુજ, ભાવનગર, આણંદ અને વારાણસી — માં 14 સેન્ટર છે. અમને તમારું શહેર જણાવો, અમે તમને સૌથી નજીકના સેન્ટર સાથે જોડીશું." },
  "Do you offer free consultations?": { hi: "क्या आप मुफ़्त कंसल्टेशन देते हैं?", gu: "શું તમે મફત કન્સલ્ટેશન આપો છો?" },
  "We understand that choosing the right fertility clinic is an important decision. To ensure every couple receives dedicated time, expert guidance, and a personalised evaluation, our consultations are not offered free of charge. However, we periodically offer special free consultation slots as part of limited-time programs. Please contact us to check current availability.": { hi: "हम समझते हैं कि सही फर्टिलिटी क्लिनिक चुनना एक महत्वपूर्ण निर्णय है। हर कपल को समर्पित समय, विशेषज्ञ मार्गदर्शन और व्यक्तिगत मूल्यांकन मिले, इसके लिए हमारे कंसल्टेशन मुफ़्त नहीं हैं। हालांकि, हम समय-समय पर सीमित अवधि के कार्यक्रमों के तहत विशेष मुफ़्त कंसल्टेशन स्लॉट भी देते हैं। वर्तमान उपलब्धता जानने के लिए कृपया हमसे संपर्क करें।", gu: "અમે સમજીએ છીએ કે યોગ્ય ફર્ટિલિટી ક્લિનિક પસંદ કરવો એ મહત્વનો નિર્ણય છે. દરેક કપલને સમર્પિત સમય, નિષ્ણાત માર્ગદર્શન અને વ્યક્તિગત મૂલ્યાંકન મળે તે માટે, અમારા કન્સલ્ટેશન મફત આપવામાં આવતા નથી. જોકે, અમે સમયાંતરે મર્યાદિત-સમયના કાર્યક્રમો હેઠળ ખાસ મફત કન્સલ્ટેશન સ્લોટ ઓફર કરીએ છીએ. હાલની ઉપલબ્ધતા ચકાસવા કૃપા કરી અમારો સંપર્ક કરો." },
  "Do you treat international patients?": { hi: "क्या आप अंतरराष्ट्रीय मरीज़ों का इलाज करते हैं?", gu: "શું તમે આંતરરાષ્ટ્રીય દર્દીઓની સારવાર કરો છો?" },
  "Yes — 300+ international patients choose Bavishi Fertility Institute every year. We provide end-to-end support including treatment planning and coordination across our 14 centres.": { hi: "हाँ — हर साल 300+ अंतरराष्ट्रीय मरीज़ Bavishi Fertility Institute चुनते हैं। हम अपने 14 सेंटरों में उपचार योजना और समन्वय सहित संपूर्ण सहायता प्रदान करते हैं।", gu: "હા — દર વર્ષે 300+ આંતરરાષ્ટ્રીય દર્દીઓ Bavishi Fertility Institute પસંદ કરે છે. અમે અમારા 14 સેન્ટરમાં સારવાર આયોજન અને સંકલન સહિત સંપૂર્ણ સહાય પૂરી પાડીએ છીએ." },

  // IVF Cost Calculator
  "Calculators": { hi: "कैलकुलेटर", gu: "કેલ્ક્યુલેટર" },
  "Transparent Estimates · No Hidden Surprises": { hi: "पारदर्शी अनुमान · कोई छिपा हुआ आश्चर्य नहीं", gu: "પારદર્શક અંદાજ · કોઈ છુપું આશ્ચર્ય નહીં" },
  "Free Tool": { hi: "मुफ़्त टूल", gu: "મફત ટૂલ" },
  "Instant Results": { hi: "तुरंत परिणाम", gu: "તાત્કાલિક પરિણામ" },
  "No Data Stored": { hi: "कोई डेटा सेव नहीं होता", gu: "કોઈ ડેટા સેવ થતો નથી" },
  "Typical IVF cycle cost": { hi: "सामान्य IVF साइकल लागत", gu: "સામાન્ય IVF સાયકલ ખર્ચ" },
  "Average cycles for success": { hi: "सफलता के लिए औसत साइकल", gu: "સફળતા માટે સરેરાશ સાયકલ" },
  "Success rate with right protocol": { hi: "सही प्रोटोकॉल के साथ सफलता दर", gu: "યોગ્ય પ્રોટોકોલ સાથે સફળતા દર" },
  "How This Calculator Works": { hi: "यह कैलकुलेटर कैसे काम करता है", gu: "આ કેલ્ક્યુલેટર કેવી રીતે કામ કરે છે" },
  "Transparent cost estimates based on Bavishi Fertility Institute pricing ranges.": { hi: "Bavishi Fertility Institute की मूल्य सीमाओं पर आधारित पारदर्शी लागत अनुमान।", gu: "Bavishi Fertility Institute ની કિંમત શ્રેણી પર આધારિત પારદર્શક ખર્ચ અંદાજ." },
  "Choose Your IVF Type": { hi: "अपना IVF प्रकार चुनें", gu: "તમારો IVF પ્રકાર પસંદ કરો" },
  "Select from Standard IVF, ICSI, Frozen Embryo Transfer, or Donor Egg IVF — each with different base costs.": { hi: "स्टैंडर्ड IVF, ICSI, फ्रोज़न एम्ब्रियो ट्रांसफर, या डोनर एग IVF में से चुनें — हर एक की बेस लागत अलग है।", gu: "સ્ટાન્ડર્ડ IVF, ICSI, ફ્રોઝન એમ્બ્રિયો ટ્રાન્સફર, અથવા ડોનર એગ IVF માંથી પસંદ કરો — દરેકની બેઝ કિંમત અલગ છે." },
  "Select Add-Ons": { hi: "ऐड-ऑन चुनें", gu: "એડ-ઓન પસંદ કરો" },
  "Add optional procedures like PGT-A, embryo freezing, ERA, or laser hatching that apply to your situation.": { hi: "PGT-A, एम्ब्रियो फ्रीज़िंग, ERA, या लेज़र हैचिंग जैसी वैकल्पिक प्रक्रियाएं जोड़ें जो आपकी स्थिति पर लागू होती हैं।", gu: "PGT-A, એમ્બ્રિયો ફ્રીઝિંગ, ERA, અથવા લેસર હેચિંગ જેવી વૈકલ્પિક પ્રક્રિયાઓ ઉમેરો જે તમારી સ્થિતિ પર લાગુ પડે છે." },
  "Set Number of Cycles": { hi: "साइकल की संख्या तय करें", gu: "સાયકલની સંખ્યા સેટ કરો" },
  "Planning for 1 cycle, or budgeting for 2–3? Adjust and see how the total investment changes.": { hi: "1 साइकल की योजना बना रहे हैं, या 2–3 के लिए बजट बना रहे हैं? समायोजित करें और देखें कि कुल निवेश कैसे बदलता है।", gu: "1 સાયકલનું આયોજન કરી રહ્યા છો, કે 2–3 માટે બજેટ બનાવી રહ્યા છો? એડજસ્ટ કરો અને જુઓ કુલ રોકાણ કેવી રીતે બદલાય છે." },
  "Get Your Estimate": { hi: "अपना अनुमान प्राप्त करें", gu: "તમારો અંદાજ મેળવો" },
  "See a transparent range for per-cycle and total cost, with a full line-item breakdown.": { hi: "प्रति साइकल और कुल लागत की पारदर्शी सीमा देखें, पूरी लाइन-आइटम ब्रेकडाउन के साथ।", gu: "પ્રતિ સાયકલ અને કુલ ખર્ચની પારદર્શક શ્રેણી જુઓ, સંપૂર્ણ લાઇન-આઇટમ બ્રેકડાઉન સાથે." },
  "Why Know Your Costs Upfront?": { hi: "अपनी लागत पहले से क्यों जानें?", gu: "તમારો ખર્ચ અગાઉથી શા માટે જાણવો?" },
  "Financial clarity removes one major stressor from your fertility journey.": { hi: "वित्तीय स्पष्टता आपकी फर्टिलिटी यात्रा से एक बड़ा तनाव दूर करती है।", gu: "નાણાકીય સ્પષ્ટતા તમારી ફર્ટિલિટી યાત્રામાંથી એક મોટો તણાવ દૂર કરે છે." },
  "No Unexpected Bills": { hi: "कोई अप्रत्याशित बिल नहीं", gu: "કોઈ અણધાર્યા બિલ નહીં" },
  "Know what to expect before you commit. Our estimates include medication ranges and common add-ons.": { hi: "प्रतिबद्ध होने से पहले जानें कि क्या उम्मीद करनी है। हमारे अनुमानों में दवा की सीमाएं और सामान्य ऐड-ऑन शामिल हैं।", gu: "કમિટ કરતા પહેલા જાણો શું અપેક્ષા રાખવી. અમારા અંદાજમાં દવાની શ્રેણી અને સામાન્ય એડ-ઓનનો સમાવેશ થાય છે." },
  "Plan Your Finances": { hi: "अपने वित्त की योजना बनाएं", gu: "તમારા નાણાંનું આયોજન કરો" },
  "Use the cost range to plan savings, explore EMI options, or check insurance coverage in advance.": { hi: "बचत की योजना बनाने, EMI विकल्प तलाशने, या पहले से बीमा कवरेज जांचने के लिए लागत सीमा का उपयोग करें।", gu: "બચતનું આયોજન કરવા, EMI વિકલ્પો શોધવા, અથવા અગાઉથી વીમા કવરેજ ચકાસવા માટે ખર્ચ શ્રેણીનો ઉપયોગ કરો." },
  "Compare Options": { hi: "विकल्पों की तुलना करें", gu: "વિકલ્પોની તુલના કરો" },
  "See how cycle type and add-ons affect your investment before making any decisions.": { hi: "कोई भी निर्णय लेने से पहले देखें कि साइकल प्रकार और ऐड-ऑन आपके निवेश को कैसे प्रभावित करते हैं।", gu: "કોઈપણ નિર્ણય લેતા પહેલા જુઓ સાયકલ પ્રકાર અને એડ-ઓન તમારા રોકાણને કેવી રીતે અસર કરે છે." },
  "Family Discussion Ready": { hi: "पारिवारिक चर्चा के लिए तैयार", gu: "કૌટુંબિક ચર્ચા માટે તૈયાર" },
  "Share a clear cost breakdown with your partner to make decisions together with full information.": { hi: "पूरी जानकारी के साथ मिलकर निर्णय लेने के लिए अपने पार्टनर के साथ स्पष्ट लागत ब्रेकडाउन साझा करें।", gu: "સંપૂર્ણ માહિતી સાથે મળીને નિર્ણય લેવા માટે તમારા પાર્ટનર સાથે સ્પષ્ટ ખર્ચ બ્રેકડાઉન શેર કરો." },
  "Prioritise Your Add-Ons": { hi: "अपने ऐड-ऑन को प्राथमिकता दें", gu: "તમારા એડ-ઓનને પ્રાધાન્ય આપો" },
  "Understand which add-ons are most cost-effective for your specific situation — ask your specialist.": { hi: "समझें कि आपकी विशिष्ट स्थिति के लिए कौन से ऐड-ऑन सबसे किफ़ायती हैं — अपने विशेषज्ञ से पूछें।", gu: "સમજો તમારી ચોક્કસ સ્થિતિ માટે કયા એડ-ઓન સૌથી કિફાયતી છે — તમારા નિષ્ણાતને પૂછો." },
  "Reduce Financial Anxiety": { hi: "वित्तीय चिंता कम करें", gu: "નાણાકીય ચિંતા ઘટાડો" },
  "Uncertainty about cost is one of the biggest barriers to seeking care. This calculator removes that barrier.": { hi: "लागत के बारे में अनिश्चितता देखभाल लेने में सबसे बड़ी बाधाओं में से एक है। यह कैलकुलेटर उस बाधा को दूर करता है।", gu: "ખર્ચ વિશે અનિશ્ચિતતા સંભાળ મેળવવામાં સૌથી મોટા અવરોધોમાંનો એક છે. આ કેલ્ક્યુલેટર તે અવરોધ દૂર કરે છે." },
  "Treatment Type": { hi: "उपचार प्रकार", gu: "સારવાર પ્રકાર" },
  "Type of IVF cycle": { hi: "IVF साइकल का प्रकार", gu: "IVF સાયકલનો પ્રકાર" },
  "Standard IVF": { hi: "स्टैंडर्ड IVF", gu: "સ્ટાન્ડર્ડ IVF" },
  "IVF with ICSI": { hi: "ICSI के साथ IVF", gu: "ICSI સાથે IVF" },
  "Frozen Embryo Transfer (FET)": { hi: "फ्रोज़न एम्ब्रियो ट्रांसफर (FET)", gu: "ફ્રોઝન એમ્બ્રિયો ટ્રાન્સફર (FET)" },
  "Donor Egg IVF": { hi: "डोनर एग IVF", gu: "ડોનર એગ IVF" },
  "Number of cycles": { hi: "साइकल की संख्या", gu: "સાયકલની સંખ્યા" },
  "1 cycle": { hi: "1 साइकल", gu: "1 સાયકલ" },
  "2 cycles": { hi: "2 साइकल", gu: "2 સાયકલ" },
  "3 cycles": { hi: "3 साइकल", gu: "3 સાયકલ" },
  "4+ cycles (budget planning)": { hi: "4+ साइकल (बजट योजना)", gu: "4+ સાયકલ (બજેટ આયોજન)" },
  "Add-Ons": { hi: "ऐड-ऑन", gu: "એડ-ઓન" },
  "(select all that apply)": { hi: "(जो लागू हों सभी चुनें)", gu: "(જે લાગુ પડે તે બધા પસંદ કરો)" },
  "Standard IVF (Base)": { hi: "स्टैंडर्ड IVF (आधार)", gu: "સ્ટાન્ડર્ડ IVF (બેઝ)" },
  "IVF + ICSI (Base)": { hi: "IVF + ICSI (आधार)", gu: "IVF + ICSI (બેઝ)" },
  "Frozen Embryo Transfer (Base)": { hi: "फ्रोज़न एम्ब्रियो ट्रांसफर (आधार)", gu: "ફ્રોઝન એમ્બ્રિયો ટ્રાન્સફર (બેઝ)" },
  "Donor Egg IVF (Base)": { hi: "डोनर एग IVF (आधार)", gu: "ડોનર એગ IVF (બેઝ)" },
  "PGT-A Genetic Testing": { hi: "PGT-A जेनेटिक टेस्टिंग", gu: "PGT-A જિનેટિક ટેસ્ટિંગ" },
  "Embryo Freezing & Storage": { hi: "एम्ब्रियो फ्रीज़िंग और स्टोरेज", gu: "એમ્બ્રિયો ફ્રીઝિંગ અને સ્ટોરેજ" },
  "Sperm Freezing": { hi: "स्पर्म फ्रीज़िंग", gu: "સ્પર્મ ફ્રીઝિંગ" },
  "ERA / Endometrial Testing": { hi: "ERA / एंडोमेट्रियल टेस्टिंग", gu: "ERA / એન્ડોમેટ્રિયલ ટેસ્ટિંગ" },
  "Laser Assisted Hatching": { hi: "लेज़र असिस्टेड हैचिंग", gu: "લેસર આસિસ્ટેડ હેચિંગ" },
  "Counselling Support": { hi: "काउंसलिंग सहायता", gu: "કાઉન્સેલિંગ સહાય" },
  "Calculate My IVF Cost": { hi: "मेरी IVF लागत की गणना करें", gu: "મારો IVF ખર્ચ ગણો" },
  "Recalculate": { hi: "फिर से गणना करें", gu: "ફરીથી ગણો" },
  "Estimated Total Investment": { hi: "अनुमानित कुल निवेश", gu: "અંદાજિત કુલ રોકાણ" },
  "For {cycles} cycle{s} including selected add-ons": { hi: "{cycles} साइकल के लिए, चुने गए ऐड-ऑन सहित", gu: "{cycles} સાયકલ માટે, પસંદ કરેલ એડ-ઓન સહિત" },
  "Cost Breakdown (per cycle)": { hi: "लागत ब्रेकडाउन (प्रति साइकल)", gu: "ખર્ચ બ્રેકડાઉન (પ્રતિ સાયકલ)" },
  "Total per cycle": { hi: "प्रति साइकल कुल", gu: "પ્રતિ સાયકલ કુલ" },
  "Get an Exact Quote": { hi: "सटीक कोट प्राप्त करें", gu: "ચોક્કસ ભાવ મેળવો" },
  "Book a consultation at Bavishi Fertility Institute for a precise, personalised cost plan based on your specific diagnosis.": { hi: "अपने विशिष्ट निदान के आधार पर सटीक, व्यक्तिगत लागत योजना के लिए Bavishi Fertility Institute में कंसल्टेशन बुक करें।", gu: "તમારા ચોક્કસ નિદાનના આધારે ચોક્કસ, વ્યક્તિગત ખર્ચ યોજના માટે Bavishi Fertility Institute પર કન્સલ્ટેશન બુક કરો." },
  "Explore EMI Options": { hi: "EMI विकल्प तलाशें", gu: "EMI વિકલ્પો શોધો" },
  "Ask about Bavishi Fertility Institute's flexible payment plans and medical finance options to spread your treatment costs.": { hi: "अपनी उपचार लागत फैलाने के लिए Bavishi Fertility Institute की लचीली भुगतान योजनाओं और मेडिकल फाइनेंस विकल्पों के बारे में पूछें।", gu: "તમારો સારવાર ખર્ચ ફેલાવવા માટે Bavishi Fertility Institute ની લવચીક ચુકવણી યોજનાઓ અને મેડિકલ ફાઇનાન્સ વિકલ્પો વિશે પૂછો." },
  "Review What's Included": { hi: "क्या शामिल है समीक्षा करें", gu: "શું સામેલ છે તે સમીક્ષા કરો" },
  "Always ask for a full itemised quote — medications, scans, blood tests, and lab fees can add significantly.": { hi: "हमेशा पूरी आइटमाइज़्ड कोट मांगें — दवाएं, स्कैन, ब्लड टेस्ट और लैब फीस काफी बढ़ सकती हैं।", gu: "હંમેશા સંપૂર્ણ આઇટમાઇઝ્ડ ભાવ માંગો — દવાઓ, સ્કેન, બ્લડ ટેસ્ટ અને લેબ ફી નોંધપાત્ર રીતે વધી શકે છે." },
  "Consider a Package Deal": { hi: "पैकेज डील पर विचार करें", gu: "પેકેજ ડીલ પર વિચાર કરો" },
  "Multi-cycle packages often offer better value. Ask Bavishi Fertility Institute about bundled pricing for 2–3 cycle commitments.": { hi: "मल्टी-साइकल पैकेज अक्सर बेहतर वैल्यू देते हैं। 2–3 साइकल प्रतिबद्धता के लिए बंडल्ड प्राइसिंग के बारे में Bavishi Fertility Institute से पूछें।", gu: "મલ્ટી-સાયકલ પેકેજ ઘણીવાર વધુ સારું મૂલ્ય આપે છે. 2–3 સાયકલ કમિટમેન્ટ માટે બંડલ્ડ પ્રાઇસિંગ વિશે Bavishi Fertility Institute ને પૂછો." },
  "* Cost estimates are indicative ranges for planning purposes only. Actual costs depend on your individual protocol, medications, and clinic. Request a full itemised quote at your consultation.": { hi: "* लागत अनुमान केवल योजना उद्देश्यों के लिए संकेतात्मक सीमाएं हैं। वास्तविक लागत आपके व्यक्तिगत प्रोटोकॉल, दवाओं और क्लिनिक पर निर्भर करती है। अपने कंसल्टेशन में पूरा आइटमाइज़्ड कोट मांगें।", gu: "* ખર્ચ અંદાજ ફક્ત આયોજન હેતુ માટે સૂચક શ્રેણી છે. વાસ્તવિક ખર્ચ તમારા વ્યક્તિગત પ્રોટોકોલ, દવાઓ અને ક્લિનિક પર આધારિત છે. તમારા કન્સલ્ટેશન પર સંપૂર્ણ આઇટમાઇઝ્ડ ભાવ માંગો." },
  "Using the cost calculator helped us budget properly for two cycles from the start. We weren't blindsided by any numbers — and that made the whole process less stressful.": { hi: "लागत कैलकुलेटर का उपयोग करने से हमें शुरू से ही दो साइकल के लिए सही ढंग से बजट बनाने में मदद मिली। हम किसी भी आंकड़े से हैरान नहीं हुए — और इससे पूरी प्रक्रिया कम तनावपूर्ण हो गई।", gu: "ખર્ચ કેલ્ક્યુલેટરનો ઉપયોગ કરવાથી અમને શરૂઆતથી જ બે સાયકલ માટે યોગ્ય રીતે બજેટ બનાવવામાં મદદ મળી. અમે કોઈપણ આંકડાથી ચોંક્યા નહીં — અને તેનાથી આખી પ્રક્રિયા ઓછી તણાવપૂર્ણ બની." },
  "— Patient at Bavishi Fertility Institute": { hi: "— Bavishi Fertility Institute में मरीज़", gu: "— Bavishi Fertility Institute ખાતે દર્દી" },
  "Who Should Use This Calculator?": { hi: "इस कैलकुलेटर का उपयोग किसे करना चाहिए?", gu: "આ કેલ્ક્યુલેટરનો ઉપયોગ કોણે કરવો જોઈએ?" },
  "Planning your first IVF cycle": { hi: "अपने पहले IVF साइकल की योजना बना रहे हैं", gu: "તમારા પ્રથમ IVF સાયકલનું આયોજન કરી રહ્યા છો" },
  "Get a realistic cost estimate before your first consultation so there are no surprises.": { hi: "अपने पहले कंसल्टेशन से पहले एक यथार्थवादी लागत अनुमान प्राप्त करें ताकि कोई आश्चर्य न हो।", gu: "તમારા પ્રથમ કન્સલ્ટેશન પહેલાં વાસ્તવિક ખર્ચ અંદાજ મેળવો જેથી કોઈ આશ્ચર્ય ન થાય." },
  "Budgeting for multiple cycles": { hi: "कई साइकल के लिए बजट बना रहे हैं", gu: "બહુવિધ સાયકલ માટે બજેટ બનાવી રહ્યા છો" },
  "See how total investment scales across 2–4 cycles and plan financially for the full journey.": { hi: "देखें कि 2–4 साइकल में कुल निवेश कैसे बढ़ता है और पूरी यात्रा के लिए वित्तीय योजना बनाएं।", gu: "જુઓ 2–4 સાયકલમાં કુલ રોકાણ કેવી રીતે વધે છે અને સંપૂર્ણ યાત્રા માટે નાણાકીય આયોજન કરો." },
  "Exploring financing options": { hi: "फाइनेंसिंग विकल्प तलाश रहे हैं", gu: "ફાઇનાન્સિંગ વિકલ્પો શોધી રહ્યા છો" },
  "Use the estimate to understand how much you need to save or borrow for EMI planning.": { hi: "EMI योजना के लिए आपको कितनी बचत या उधार लेने की आवश्यकता है, यह समझने के लिए अनुमान का उपयोग करें।", gu: "EMI આયોજન માટે તમારે કેટલી બચત અથવા ઉધાર લેવાની જરૂર છે તે સમજવા અંદાજનો ઉપયોગ કરો." },
  "Comparing treatment types": { hi: "उपचार प्रकारों की तुलना कर रहे हैं", gu: "સારવાર પ્રકારોની તુલના કરી રહ્યા છો" },
  "Switch between Standard IVF, ICSI, FET, and Donor Egg to compare costs before deciding.": { hi: "निर्णय लेने से पहले लागतों की तुलना करने के लिए स्टैंडर्ड IVF, ICSI, FET और डोनर एग के बीच स्विच करें।", gu: "નિર્ણય લેતા પહેલા ખર્ચની તુલના કરવા સ્ટાન્ડર્ડ IVF, ICSI, FET અને ડોનર એગ વચ્ચે સ્વિચ કરો." },
  "Understanding add-on costs": { hi: "ऐड-ऑन लागत को समझना", gu: "એડ-ઓન ખર્ચને સમજવું" },
  "See exactly how PGT-A, ERA, or other add-ons affect your total investment.": { hi: "ठीक-ठीक देखें कि PGT-A, ERA, या अन्य ऐड-ऑन आपके कुल निवेश को कैसे प्रभावित करते हैं।", gu: "બરાબર જુઓ PGT-A, ERA, અથવા અન્ય એડ-ઓન તમારા કુલ રોકાણને કેવી રીતે અસર કરે છે." },
  "Family financial planning": { hi: "पारिवारिक वित्तीय योजना", gu: "કૌટુંબિક નાણાકીય આયોજન" },
  "Share a clear, itemised estimate with your partner before making major treatment decisions.": { hi: "प्रमुख उपचार निर्णय लेने से पहले अपने पार्टनर के साथ एक स्पष्ट, आइटमाइज़्ड अनुमान साझा करें।", gu: "મોટા સારવાર નિર્ણયો લેતા પહેલા તમારા પાર્ટનર સાથે સ્પષ્ટ, આઇટમાઇઝ્ડ અંદાજ શેર કરો." },
  "What this calculator helps you do": { hi: "यह कैलकुलेटर आपकी क्या मदद करता है", gu: "આ કેલ્ક્યુલેટર તમને શું કરવામાં મદદ કરે છે" },
  "Budget Your Treatment": { hi: "अपने उपचार का बजट बनाएं", gu: "તમારી સારવારનું બજેટ બનાવો" },
  "Get indicative cost ranges for different IVF cycle types and add-on procedures.": { hi: "विभिन्न IVF साइकल प्रकारों और ऐड-ऑन प्रक्रियाओं के लिए संकेतात्मक लागत सीमाएं प्राप्त करें।", gu: "વિવિધ IVF સાયકલ પ્રકારો અને એડ-ઓન પ્રક્રિયાઓ માટે સૂચક ખર્ચ શ્રેણી મેળવો." },
  "See how cycle type and add-ons affect your total investment before booking.": { hi: "बुकिंग से पहले देखें कि साइकल प्रकार और ऐड-ऑन आपके कुल निवेश को कैसे प्रभावित करते हैं।", gu: "બુકિંગ પહેલા જુઓ સાયકલ પ્રકાર અને એડ-ઓન તમારા કુલ રોકાણને કેવી રીતે અસર કરે છે." },
  "Plan Financially": { hi: "वित्तीय रूप से योजना बनाएं", gu: "નાણાકીય રીતે આયોજન કરો" },
  "Use the estimates to explore EMI, insurance, and multi-cycle package options.": { hi: "EMI, बीमा और मल्टी-साइकल पैकेज विकल्पों का पता लगाने के लिए अनुमानों का उपयोग करें।", gu: "EMI, વીમા, અને મલ્ટી-સાયકલ પેકેજ વિકલ્પો શોધવા અંદાજનો ઉપયોગ કરો." },
  "Get a Precise Quote From Us": { hi: "हमसे सटीक कोट प्राप्त करें", gu: "અમારી પાસેથી ચોક્કસ ભાવ મેળવો" },
  "Get an exact cost plan for your IVF treatment at Bavishi Fertility Institute.": { hi: "Bavishi Fertility Institute में अपने IVF उपचार के लिए सटीक लागत योजना प्राप्त करें।", gu: "Bavishi Fertility Institute પર તમારી IVF સારવાર માટે ચોક્કસ ખર્ચ યોજના મેળવો." },
  "Our team will provide a full itemised quote, discuss flexible payment options, and help you plan the most cost-effective path to your goal.": { hi: "हमारी टीम पूरा आइटमाइज़्ड कोट देगी, लचीले भुगतान विकल्पों पर चर्चा करेगी, और आपके लक्ष्य के लिए सबसे किफ़ायती रास्ता बनाने में मदद करेगी।", gu: "અમારી ટીમ સંપૂર્ણ આઇટમાઇઝ્ડ ભાવ આપશે, લવચીક ચુકવણી વિકલ્પોની ચર્ચા કરશે, અને તમારા લક્ષ્ય માટે સૌથી કિફાયતી માર્ગ બનાવવામાં મદદ કરશે." },
  "WhatsApp Support": { hi: "व्हाट्सऐप सहायता", gu: "વોટ્સએપ સહાય" },
  "About This Calculator": { hi: "इस कैलकुलेटर के बारे में", gu: "આ કેલ્ક્યુલેટર વિશે" },
  "Frequently Asked Questions": { hi: "अक्सर पूछे जाने वाले सवाल", gu: "વારંવાર પુછાતા પ્રશ્નો" },

  // Calculator cross-links
  "Fertility Calculators To Plan Your Pregnancy Journey": { hi: "आपकी प्रेगनेंसी यात्रा की योजना बनाने के लिए फर्टिलिटी कैलकुलेटर", gu: "તમારી પ્રેગ્નન્સી યાત્રાનું આયોજન કરવા ફર્ટિલિટી કેલ્ક્યુલેટર" },
  "Use our expert-designed fertility calculators to estimate IVF success rates, track ovulation, understand your fertile window, and plan your journey to parenthood with confidence.": { hi: "IVF सफलता दर का अनुमान लगाने, ओव्यूलेशन ट्रैक करने, अपनी फर्टाइल विंडो समझने और आत्मविश्वास के साथ पेरेंटहुड की यात्रा की योजना बनाने के लिए हमारे विशेषज्ञ-डिज़ाइन किए गए फर्टिलिटी कैलकुलेटर का उपयोग करें।", gu: "IVF સફળતા દરનો અંદાજ કાઢવા, ઓવ્યુલેશન ટ્રેક કરવા, તમારી ફર્ટાઇલ વિન્ડો સમજવા, અને આત્મવિશ્વાસ સાથે પેરેન્ટહુડની યાત્રાનું આયોજન કરવા અમારા નિષ્ણાત-ડિઝાઇન કરેલા ફર્ટિલિટી કેલ્ક્યુલેટરનો ઉપયોગ કરો." },
  "IVF Success Rate Calculator": { hi: "IVF सफलता दर कैलकुलेटर", gu: "IVF સફળતા દર કેલ્ક્યુલેટર" },
  "Fertile Period Calculator": { hi: "फर्टाइल पीरियड कैलकुलेटर", gu: "ફર્ટાઇલ પીરિયડ કેલ્ક્યુલેટર" },
  "Risk of Repeat Miscarriage Calculator": { hi: "दोबारा मिसकैरेज के जोखिम का कैलकुलेटर", gu: "ફરીથી મિસકેરેજના જોખમનું કેલ્ક્યુલેટર" },
  "Natural Pregnancy Calculator": { hi: "नेचुरल प्रेगनेंसी कैलकुलेटर", gu: "નેચરલ પ્રેગ્નન્સી કેલ્ક્યુલેટર" },
  "IVF Cost Calculator": { hi: "IVF लागत कैलकुलेटर", gu: "IVF ખર્ચ કેલ્ક્યુલેટર" },
  "AMH Level Interpreter": { hi: "AMH लेवल इंटरप्रेटर", gu: "AMH લેવલ ઇન્ટરપ્રેટર" },
  "Ovulation Calculator": { hi: "ओव्यूलेशन कैलकुलेटर", gu: "ઓવ્યુલેશન કેલ્ક્યુલેટર" },
  "Semen Analysis Calculator": { hi: "सीमेन एनालिसिस कैलकुलेटर", gu: "સીમેન એનાલિસિસ કેલ્ક્યુલેટર" },

  // IVF Success Rate Calculator
  "Evidence-Based · Clinically Informed": { hi: "साक्ष्य-आधारित · चिकित्सकीय रूप से सूचित", gu: "પુરાવા-આધારિત · તબીબી રીતે માહિતગાર" },
  "Bavishi Fertility Rate": { hi: "Bavishi Fertility दर", gu: "Bavishi Fertility દર" },
  "Most important factor": { hi: "सबसे महत्वपूर्ण कारक", gu: "સૌથી મહત્વનું પરિબળ" },
  "Best embryo transfer": { hi: "सर्वश्रेष्ठ एम्ब्रियो ट्रांसफर", gu: "શ્રેષ્ઠ એમ્બ્રિયો ટ્રાન્સફર" },
  "Cumulative success": { hi: "संचयी सफलता", gu: "સંચિત સફળતા" },
  "Your success probability is calculated using the factors that matter most — step by step.": { hi: "आपकी सफलता की संभावना सबसे महत्वपूर्ण कारकों का उपयोग करके, चरण दर चरण गणना की जाती है।", gu: "તમારી સફળતાની સંભાવના સૌથી મહત્વના પરિબળોનો ઉપયોગ કરીને, પગલું-દર-પગલું ગણવામાં આવે છે." },
  "Enter Your Age": { hi: "अपनी उम्र दर्ज करें", gu: "તમારી ઉંમર દાખલ કરો" },
  "Age is the strongest single predictor of IVF success. We start with your age-group's published live-birth rate.": { hi: "उम्र IVF सफलता का सबसे मज़बूत एकल संकेतक है। हम आपके आयु-समूह की प्रकाशित लाइव-बर्थ दर से शुरू करते हैं।", gu: "ઉંમર IVF સફળતાનું સૌથી મજબૂત એકલ પરિબળ છે. અમે તમારા વય-જૂથના પ્રકાશિત લાઇવ-બર્થ દરથી શરૂ કરીએ છીએ." },
  "Share Your Diagnosis": { hi: "अपना निदान साझा करें", gu: "તમારું નિદાન શેર કરો" },
  "Your primary fertility diagnosis is the second key factor — it adds or reduces from your age baseline.": { hi: "आपका प्राथमिक फर्टिलिटी निदान दूसरा प्रमुख कारक है — यह आपकी उम्र के आधार में जोड़ता या घटाता है।", gu: "તમારું પ્રાથમિક ફર્ટિલિટી નિદાન બીજું મુખ્ય પરિબળ છે — તે તમારા ઉંમર બેઝલાઇનમાં ઉમેરે અથવા ઘટાડે છે." },
  "Add Clinical Factors": { hi: "क्लिनिकल कारक जोड़ें", gu: "ક્લિનિકલ પરિબળો ઉમેરો" },
  "Treatment history, embryo type, and egg source are factored in to personalise your estimate.": { hi: "आपके अनुमान को व्यक्तिगत बनाने के लिए उपचार इतिहास, एम्ब्रियो प्रकार और एग स्रोत को शामिल किया जाता है।", gu: "તમારા અંદાજને વ્યક્તિગત બનાવવા સારવાર ઇતિહાસ, એમ્બ્રિયો પ્રકાર, અને એગ સ્રોતનો સમાવેશ કરવામાં આવે છે." },
  "See Your Probability": { hi: "अपनी संभावना देखें", gu: "તમારી સંભાવના જુઓ" },
  "Get your personalised success rate instantly, with a breakdown of every factor that shaped it.": { hi: "तुरंत अपनी व्यक्तिगत सफलता दर प्राप्त करें, इसे आकार देने वाले हर कारक के ब्रेकडाउन के साथ।", gu: "તાત્કાલિક તમારો વ્યક્તિગત સફળતા દર મેળવો, તેને આકાર આપતા દરેક પરિબળના બ્રેકડાઉન સાથે." },
  "Why Know Your Success Rate?": { hi: "अपनी सफलता दर क्यों जानें?", gu: "તમારો સફળતા દર શા માટે જાણવો?" },
  "Understanding your odds helps you plan, stay motivated, and make the right decisions.": { hi: "अपनी संभावनाओं को समझना आपको योजना बनाने, प्रेरित रहने और सही निर्णय लेने में मदद करता है।", gu: "તમારી શક્યતાઓ સમજવાથી તમને આયોજન કરવામાં, પ્રેરિત રહેવામાં, અને યોગ્ય નિર્ણય લેવામાં મદદ મળે છે." },
  "Set Realistic Expectations": { hi: "यथार्थवादी अपेक्षाएं निर्धारित करें", gu: "વાસ્તવિક અપેક્ષાઓ સેટ કરો" },
  "Knowing your actual probability helps you prepare emotionally and practically for each cycle.": { hi: "अपनी वास्तविक संभावना जानने से आपको हर साइकल के लिए भावनात्मक और व्यावहारिक रूप से तैयार होने में मदद मिलती है।", gu: "તમારી વાસ્તવિક સંભાવના જાણવાથી તમને દરેક સાયકલ માટે ભાવનાત્મક અને વ્યવહારુ રીતે તૈયાર થવામાં મદદ મળે છે." },
  "Understand What Helps": { hi: "समझें क्या मदद करता है", gu: "શું મદદ કરે છે તે સમજો" },
  "Discover which factors are in your favour and which are modifiable before your next cycle.": { hi: "जानें कौन से कारक आपके पक्ष में हैं और कौन से आपके अगले साइकल से पहले बदले जा सकते हैं।", gu: "તમારા આગામી સાયકલ પહેલાં કયા પરિબળો તમારી તરફેણમાં છે અને કયા બદલી શકાય તેવા છે તે શોધો." },
  "Plan Your Budget": { hi: "अपना बजट बनाएं", gu: "તમારું બજેટ બનાવો" },
  "Your success rate estimate helps you decide how many cycles to budget for and when to review options.": { hi: "आपकी सफलता दर का अनुमान यह तय करने में मदद करता है कि कितने साइकल के लिए बजट बनाना है और विकल्पों की समीक्षा कब करनी है।", gu: "તમારો સફળતા દર અંદાજ કેટલા સાયકલ માટે બજેટ બનાવવું અને ક્યારે વિકલ્પોની સમીક્ષા કરવી તે નક્કી કરવામાં મદદ કરે છે." },
  "Make Informed Decisions": { hi: "सूचित निर्णय लें", gu: "માહિતગાર નિર્ણયો લો" },
  "Evidence-based estimates help you and your doctor choose the right protocol and timing.": { hi: "साक्ष्य-आधारित अनुमान आपको और आपके डॉक्टर को सही प्रोटोकॉल और समय चुनने में मदद करते हैं।", gu: "પુરાવા-આધારિત અંદાજ તમને અને તમારા ડોક્ટરને યોગ્ય પ્રોટોકોલ અને સમય પસંદ કરવામાં મદદ કરે છે." },
  "Stay Motivated": { hi: "प्रेरित रहें", gu: "પ્રેરિત રહો" },
  "Understanding your real chances — not just a generic number — keeps you focused and hopeful.": { hi: "अपनी वास्तविक संभावनाओं को समझना — सिर्फ़ एक सामान्य संख्या नहीं — आपको केंद्रित और आशान्वित रखता है।", gu: "તમારી વાસ્તવિક શક્યતાઓ સમજવી — ફક્ત એક સામાન્ય સંખ્યા નહીં — તમને કેન્દ્રિત અને આશાવાદી રાખે છે." },
  "Time Your Treatment": { hi: "अपने उपचार का समय तय करें", gu: "તમારી સારવારનો સમય નક્કી કરો" },
  "Seeing the age impact first-hand motivates acting at the right moment rather than delaying.": { hi: "उम्र के प्रभाव को प्रत्यक्ष रूप से देखना देरी करने के बजाय सही समय पर कार्य करने के लिए प्रेरित करता है।", gu: "ઉંમરની અસર જાતે જોવાથી વિલંબ કરવાને બદલે યોગ્ય સમયે પગલાં લેવાની પ્રેરણા મળે છે." },
  "About You": { hi: "आपके बारे में", gu: "તમારા વિશે" },
  "Your Age Group": { hi: "आपका आयु समूह", gu: "તમારો વય જૂથ" },
  "— Select age group —": { hi: "— आयु समूह चुनें —", gu: "— વય જૂથ પસંદ કરો —" },
  "Under 30": { hi: "30 से कम", gu: "30 થી ઓછી" },
  "30 – 34": { hi: "30 – 34", gu: "30 – 34" },
  "35 – 37": { hi: "35 – 37", gu: "35 – 37" },
  "38 – 40": { hi: "38 – 40", gu: "38 – 40" },
  "41 – 42": { hi: "41 – 42", gu: "41 – 42" },
  "43 or older": { hi: "43 या अधिक", gu: "43 કે તેથી વધુ" },
  "Primary Diagnosis": { hi: "प्राथमिक निदान", gu: "પ્રાથમિક નિદાન" },
  "— Select diagnosis —": { hi: "— निदान चुनें —", gu: "— નિદાન પસંદ કરો —" },
  "Unexplained infertility": { hi: "अस्पष्ट बांझपन", gu: "અસ્પષ્ટ વંધ્યત્વ" },
  "PCOS / Ovulatory disorder": { hi: "PCOS / ओव्यूलेटरी विकार", gu: "PCOS / ઓવ્યુલેટરી ડિસઓર્ડર" },
  "Tubal factor": { hi: "ट्यूबल कारक", gu: "ટ્યુબલ પરિબળ" },
  "Male factor": { hi: "पुरुष कारक", gu: "પુરુષ પરિબળ" },
  "Severe male factor (azoospermia)": { hi: "गंभीर पुरुष कारक (एज़ोस्पर्मिया)", gu: "ગંભીર પુરુષ પરિબળ (એઝોસ્પર્મિયા)" },
  "Endometriosis": { hi: "एंडोमेट्रियोसिस", gu: "એન્ડોમેટ્રિઓસિસ" },
  "Diminished ovarian reserve": { hi: "कम ओवेरियन रिज़र्व", gu: "ઘટેલ ઓવેરિયન રિઝર્વ" },
  "Uterine factor": { hi: "गर्भाशय कारक", gu: "ગર્ભાશય પરિબળ" },
  "Treatment History": { hi: "उपचार इतिहास", gu: "સારવાર ઇતિહાસ" },
  "Previous IVF Attempts": { hi: "पिछले IVF प्रयास", gu: "અગાઉના IVF પ્રયાસો" },
  "First time": { hi: "पहली बार", gu: "પ્રથમ વખત" },
  "1 before": { hi: "1 पहले", gu: "1 પહેલાં" },
  "2 before": { hi: "2 पहले", gu: "2 પહેલાં" },
  "3+ before": { hi: "3+ पहले", gu: "3+ પહેલાં" },
  "Previous Successful Pregnancy?": { hi: "पिछली सफल गर्भावस्था?", gu: "અગાઉની સફળ ગર્ભાવસ્થા?" },
  "Yes": { hi: "हाँ", gu: "હા" },
  "No": { hi: "नहीं", gu: "ના" },
  "Embryo Details": { hi: "एम्ब्रियो विवरण", gu: "એમ્બ્રિયો વિગતો" },
  "Embryo Transfer Type": { hi: "एम्ब्रियो ट्रांसफर प्रकार", gu: "એમ્બ્રિયો ટ્રાન્સફર પ્રકાર" },
  "Day 5 Blastocyst": { hi: "डे 5 ब्लास्टोसिस्ट", gu: "ડે 5 બ્લાસ્ટોસિસ્ટ" },
  "Day 3 Cleavage": { hi: "डे 3 क्लीवेज", gu: "ડે 3 ક્લીવેજ" },
  "Not Known": { hi: "ज्ञात नहीं", gu: "જાણીતું નથી" },
  "Egg Source": { hi: "एग स्रोत", gu: "એગ સ્રોત" },
  "Own eggs": { hi: "स्वयं के एग", gu: "પોતાના એગ" },
  "Donor eggs": { hi: "डोनर एग", gu: "ડોનર એગ" },
  "Please answer all required questions.": { hi: "कृपया सभी आवश्यक प्रश्नों का उत्तर दें।", gu: "કૃપા કરી બધા જરૂરી પ્રશ્નોના જવાબ આપો." },
  "If your AMH is below 0.5, endometrial thickness below 7mm, or you have severe adenomyosis, please consult a specialist directly.": { hi: "यदि आपका AMH 0.5 से कम है, एंडोमेट्रियल मोटाई 7mm से कम है, या आपको गंभीर एडेनोमायोसिस है, तो कृपया सीधे विशेषज्ञ से परामर्श करें।", gu: "જો તમારું AMH 0.5 થી ઓછું છે, એન્ડોમેટ્રિયલ જાડાઈ 7mm થી ઓછી છે, અથવા તમને ગંભીર એડેનોમાયોસિસ છે, તો કૃપા કરી સીધા નિષ્ણાતની સલાહ લો." },
  "Calculate My Success Rate": { hi: "मेरी सफलता दर की गणना करें", gu: "મારો સફળતા દર ગણો" },
  "Estimated Success Rate Per Cycle": { hi: "प्रति साइकल अनुमानित सफलता दर", gu: "પ્રતિ સાયકલ અંદાજિત સફળતા દર" },
  "Favourable Prognosis": { hi: "अनुकूल पूर्वानुमान", gu: "અનુકૂળ પૂર્વાનુમાન" },
  "Moderate Prognosis": { hi: "मध्यम पूर्वानुमान", gu: "મધ્યમ પૂર્વાનુમાન" },
  "Challenging — Specialist Review Needed": { hi: "चुनौतीपूर्ण — विशेषज्ञ समीक्षा आवश्यक", gu: "પડકારજનક — નિષ્ણાત સમીક્ષા જરૂરી" },
  "Your profile indicates a favourable chance of IVF success. With the right protocol and specialist team, your outlook is genuinely encouraging.": { hi: "आपकी प्रोफ़ाइल IVF सफलता की अनुकूल संभावना दर्शाती है। सही प्रोटोकॉल और विशेषज्ञ टीम के साथ, आपकी संभावनाएं वास्तव में उत्साहजनक हैं।", gu: "તમારી પ્રોફાઇલ IVF સફળતાની અનુકૂળ શક્યતા દર્શાવે છે. યોગ્ય પ્રોટોકોલ અને નિષ્ણાત ટીમ સાથે, તમારો દૃષ્ટિકોણ ખરેખર પ્રોત્સાહક છે." },
  "Your profile shows moderate chances per cycle. Optimising your protocol and addressing modifiable factors can improve your outcome meaningfully.": { hi: "आपकी प्रोफ़ाइल प्रति साइकल मध्यम संभावनाएं दिखाती है। अपने प्रोटोकॉल को अनुकूलित करना और बदले जा सकने वाले कारकों को संबोधित करना आपके परिणाम को सार्थक रूप से बेहतर बना सकता है।", gu: "તમારી પ્રોફાઇલ પ્રતિ સાયકલ મધ્યમ શક્યતાઓ દર્શાવે છે. તમારા પ્રોટોકોલને ઓપ્ટિમાઇઝ કરવાથી અને બદલી શકાય તેવા પરિબળોને સંબોધવાથી તમારું પરિણામ અર્થપૂર્ણ રીતે સુધારી શકાય છે." },
  "Your profile indicates a more challenging prognosis per cycle. However, many patients in this range achieve success with specialist care, optimised protocols, and the right approach.": { hi: "आपकी प्रोफ़ाइल प्रति साइकल अधिक चुनौतीपूर्ण पूर्वानुमान दर्शाती है। हालांकि, इस श्रेणी के कई मरीज़ विशेषज्ञ देखभाल, अनुकूलित प्रोटोकॉल और सही दृष्टिकोण के साथ सफलता प्राप्त करते हैं।", gu: "તમારી પ્રોફાઇલ પ્રતિ સાયકલ વધુ પડકારજનક પૂર્વાનુમાન દર્શાવે છે. જોકે, આ શ્રેણીના ઘણા દર્દીઓ નિષ્ણાત સંભાળ, ઓપ્ટિમાઇઝ્ડ પ્રોટોકોલ, અને યોગ્ય અભિગમ સાથે સફળતા મેળવે છે." },
  "Cumulative chance over 3 cycles: approximately {pct}%": { hi: "3 साइकल में संचयी संभावना: लगभग {pct}%", gu: "3 સાયકલમાં સંચિત સંભાવના: આશરે {pct}%" },
  "Success probability": { hi: "सफलता की संभावना", gu: "સફળતાની સંભાવના" },
  "28% moderate": { hi: "28% मध्यम", gu: "28% મધ્યમ" },
  "50% favourable": { hi: "50% अनुकूल", gu: "50% અનુકૂળ" },
  "How Your Score Was Calculated": { hi: "आपका स्कोर कैसे गणना किया गया", gu: "તમારો સ્કોર કેવી રીતે ગણવામાં આવ્યો" },
  "Age base rate": { hi: "उम्र आधार दर", gu: "ઉંમર બેઝ દર" },
  "65% (donor)": { hi: "65% (डोनर)", gu: "65% (ડોનર)" },
  "Diagnosis": { hi: "निदान", gu: "નિદાન" },
  "Embryo": { hi: "एम्ब्रियो", gu: "એમ્બ્રિયો" },
  "+10% boost": { hi: "+10% बढ़ोतरी", gu: "+10% વધારો" },
  "Day 3": { hi: "डे 3", gu: "ડે 3" },
  "Unknown": { hi: "अज्ञात", gu: "અજ્ઞાત" },
  "Previous attempts": { hi: "पिछले प्रयास", gu: "અગાઉના પ્રયાસો" },
  "Prior successful pregnancy": { hi: "पिछली सफल गर्भावस्था", gu: "અગાઉની સફળ ગર્ભાવસ્થા" },
  "Egg source": { hi: "एग स्रोत", gu: "એગ સ્રોત" },
  "Donor (65% base)": { hi: "डोनर (65% आधार)", gu: "ડોનર (65% બેઝ)" },
  "Consult a Specialist": { hi: "विशेषज्ञ से परामर्श करें", gu: "નિષ્ણાતની સલાહ લો" },
  "Book a consultation to validate your profile and design a personalised protocol.": { hi: "अपनी प्रोफ़ाइल को मान्य करने और व्यक्तिगत प्रोटोकॉल डिज़ाइन करने के लिए कंसल्टेशन बुक करें।", gu: "તમારી પ્રોફાઇલ માન્ય કરવા અને વ્યક્તિગત પ્રોટોકોલ ડિઝાઇન કરવા કન્સલ્ટેશન બુક કરો." },
  "Full Fertility Workup": { hi: "पूर्ण फर्टिलिटी वर्कअप", gu: "સંપૂર્ણ ફર્ટિલિટી વર્કઅપ" },
  "A thorough investigation helps identify factors not captured by this calculator.": { hi: "एक गहन जांच इस कैलकुलेटर द्वारा न पकड़े गए कारकों की पहचान करने में मदद करती है।", gu: "એક સંપૂર્ણ તપાસ આ કેલ્ક્યુલેટર દ્વારા ન પકડાયેલા પરિબળોને ઓળખવામાં મદદ કરે છે." },
  "Optimise Your Health": { hi: "अपने स्वास्थ्य को अनुकूलित करें", gu: "તમારા સ્વાસ્થ્યને ઓપ્ટિમાઇઝ કરો" },
  "Folic acid, vitamin D, and lifestyle changes can meaningfully improve outcomes.": { hi: "फोलिक एसिड, विटामिन D, और जीवनशैली में बदलाव परिणामों को सार्थक रूप से बेहतर बना सकते हैं।", gu: "ફોલિક એસિડ, વિટામિન D, અને જીવનશૈલીમાં ફેરફાર પરિણામોને અર્થપૂર્ણ રીતે સુધારી શકે છે." },
  "Explore All Options": { hi: "सभी विकल्प तलाशें", gu: "બધા વિકલ્પો શોધો" },
  "Ask about multi-cycle packages, donor egg programmes, and advanced techniques like PGT-A.": { hi: "मल्टी-साइकल पैकेज, डोनर एग प्रोग्राम, और PGT-A जैसी उन्नत तकनीकों के बारे में पूछें।", gu: "મલ્ટી-સાયકલ પેકેજ, ડોનર એગ પ્રોગ્રામ, અને PGT-A જેવી અદ્યતન તકનીકો વિશે પૂછો." },
  "* This tool is for educational purposes only and does not constitute medical advice. Success rates vary based on many clinical factors not captured here. Bavishi Fertility Institute accepts no liability for decisions made based solely on this calculator's output.": { hi: "* यह टूल केवल शैक्षिक उद्देश्यों के लिए है और चिकित्सा सलाह नहीं है। सफलता दरें यहां न पकड़े गए कई क्लिनिकल कारकों के आधार पर भिन्न होती हैं। Bavishi Fertility Institute केवल इस कैलकुलेटर के परिणाम के आधार पर लिए गए निर्णयों के लिए कोई ज़िम्मेदारी स्वीकार नहीं करता है।", gu: "* આ ટૂલ ફક્ત શૈક્ષણિક હેતુ માટે છે અને તબીબી સલાહ નથી. સફળતા દર અહીં ન સમાવેલા ઘણા ક્લિનિકલ પરિબળોના આધારે બદલાય છે. Bavishi Fertility Institute ફક્ત આ કેલ્ક્યુલેટરના પરિણામના આધારે લેવાયેલા નિર્ણયો માટે કોઈ જવાબદારી સ્વીકારતું નથી." },
  "Knowing my actual success rate — not just a general number — helped me and my husband decide to go for a second cycle. That cycle gave us our child.": { hi: "अपनी वास्तविक सफलता दर जानना — सिर्फ़ एक सामान्य संख्या नहीं — मुझे और मेरे पति को दूसरे साइकल के लिए जाने का निर्णय लेने में मदद मिली। उस साइकल ने हमें हमारा बच्चा दिया।", gu: "મારો વાસ્તવિક સફળતા દર જાણવો — ફક્ત એક સામાન્ય સંખ્યા નહીં — મને અને મારા પતિને બીજા સાયકલ માટે જવાનો નિર્ણય લેવામાં મદદ કરી. તે સાયકલે અમને અમારું બાળક આપ્યું." },
  "First-time IVF patients": { hi: "पहली बार IVF मरीज़", gu: "પ્રથમ વખત IVF દર્દીઓ" },
  "Get a personalised baseline before your first cycle to set realistic expectations.": { hi: "यथार्थवादी अपेक्षाएं निर्धारित करने के लिए अपने पहले साइकल से पहले एक व्यक्तिगत आधार प्राप्त करें।", gu: "વાસ્તવિક અપેક્ષાઓ સેટ કરવા તમારા પ્રથમ સાયકલ પહેલાં વ્યક્તિગત બેઝલાઇન મેળવો." },
  "After previous IVF failure": { hi: "पिछली IVF विफलता के बाद", gu: "અગાઉની IVF નિષ્ફળતા પછી" },
  "Understand how your history and any new clinical factors affect your next cycle's odds.": { hi: "समझें कि आपका इतिहास और कोई नए क्लिनिकल कारक आपके अगले साइकल की संभावनाओं को कैसे प्रभावित करते हैं।", gu: "સમજો તમારો ઇતિહાસ અને કોઈ નવા ક્લિનિકલ પરિબળો તમારા આગામી સાયકલની શક્યતાઓને કેવી રીતે અસર કરે છે." },
  "Women over 35": { hi: "35 से अधिक उम्र की महिलाएं", gu: "35 થી વધુ ઉંમરની મહિલાઓ" },
  "See exactly how age impacts your probability and why acting sooner matters.": { hi: "ठीक-ठीक देखें कि उम्र आपकी संभावना को कैसे प्रभावित करती है और जल्दी कार्य करना क्यों महत्वपूर्ण है।", gu: "બરાબર જુઓ ઉંમર તમારી સંભાવનાને કેવી રીતે અસર કરે છે અને વહેલા પગલાં લેવા શા માટે મહત્વના છે." },
  "Considering donor eggs": { hi: "डोनर एग पर विचार कर रहे हैं", gu: "ડોનર એગ પર વિચાર કરી રહ્યા છો" },
  "Compare your own-egg probability against the donor egg baseline for informed decision-making.": { hi: "सूचित निर्णय लेने के लिए अपने स्वयं के एग की संभावना की तुलना डोनर एग आधार से करें।", gu: "માહિતગાર નિર્ણય લેવા તમારા પોતાના એગની સંભાવનાની ડોનર એગ બેઝલાઇન સાથે તુલના કરો." },
  "Understand your profile when no clear cause has been identified yet.": { hi: "समझें अपनी प्रोफ़ाइल जब अभी तक कोई स्पष्ट कारण की पहचान नहीं हुई हो।", gu: "તમારી પ્રોફાઇલ સમજો જ્યારે હજી સુધી કોઈ સ્પષ્ટ કારણ ઓળખાયું નથી." },
  "PCOS or Endometriosis": { hi: "PCOS या एंडोमेट्रियोसिस", gu: "PCOS અથવા એન્ડોમેટ્રિઓસિસ" },
  "See how your diagnosis specifically shifts your success rate and what can be optimised.": { hi: "देखें कि आपका निदान विशेष रूप से आपकी सफलता दर को कैसे बदलता है और क्या अनुकूलित किया जा सकता है।", gu: "જુઓ તમારું નિદાન ખાસ કરીને તમારો સફળતા દર કેવી રીતે બદલે છે અને શું ઓપ્ટિમાઇઝ કરી શકાય છે." },
  "Age-Based Baseline": { hi: "उम्र-आधारित बेसलाइन", gu: "ઉંમર-આધારિત બેઝલાઇન" },
  "Starts with your age group's published live-birth rate, adjusted for egg source.": { hi: "आपके आयु समूह की प्रकाशित लाइव-बर्थ दर से शुरू होता है, एग स्रोत के लिए समायोजित।", gu: "તમારા વય જૂથના પ્રકાશિત લાઇવ-બર્થ દરથી શરૂ થાય છે, એગ સ્રોત માટે એડજસ્ટ કરેલ." },
  "Clinical Modifiers": { hi: "क्लिनिकल संशोधक", gu: "ક્લિનિકલ મોડિફાયર્સ" },
  "Diagnosis, embryo quality, transfer type, and treatment history all shift the baseline.": { hi: "निदान, एम्ब्रियो गुणवत्ता, ट्रांसफर प्रकार, और उपचार इतिहास सभी बेसलाइन को बदलते हैं।", gu: "નિદાન, એમ્બ્રિયો ગુણવત્તા, ટ્રાન્સફર પ્રકાર, અને સારવાર ઇતિહાસ બધા બેઝલાઇનને બદલે છે." },
  "Cumulative Estimate": { hi: "संचयी अनुमान", gu: "સંચિત અંદાજ" },
  "Shows your 3-cycle cumulative probability using standard compounding statistics.": { hi: "मानक चक्रवृद्धि सांख्यिकी का उपयोग करके आपकी 3-साइकल संचयी संभावना दिखाता है।", gu: "માનક કમ્પાઉન્ડિંગ સ્ટેટિસ્ટિક્સનો ઉપયોગ કરીને તમારી 3-સાયકલ સંચિત સંભાવના બતાવે છે." },
  "Know Your Real Chances": { hi: "अपनी वास्तविक संभावनाएं जानें", gu: "તમારી વાસ્તવિક શક્યતાઓ જાણો" },
  "Get a specialist review of your IVF success estimate.": { hi: "अपने IVF सफलता अनुमान की विशेषज्ञ समीक्षा प्राप्त करें।", gu: "તમારો IVF સફળતા અંદાજની નિષ્ણાત સમીક્ષા મેળવો." },
  "Our fertility specialists review your full profile, including factors this calculator cannot assess, to give you a truly personalised plan.": { hi: "हमारे फर्टिलिटी विशेषज्ञ आपको वास्तव में व्यक्तिगत योजना देने के लिए आपकी पूरी प्रोफ़ाइल की समीक्षा करते हैं, जिसमें वे कारक शामिल हैं जिनका यह कैलकुलेटर आकलन नहीं कर सकता।", gu: "તમને ખરેખર વ્યક્તિગત યોજના આપવા અમારા ફર્ટિલિટી નિષ્ણાતો તમારી સંપૂર્ણ પ્રોફાઇલની સમીક્ષા કરે છે, જેમાં તે પરિબળોનો સમાવેશ થાય છે જેનું આ કેલ્ક્યુલેટર મૂલ્યાંકન કરી શકતું નથી." },
};

export function ui(key: string, locale: Locale): string {
  return locale === "en" ? key : UI_STRINGS[key]?.[locale] ?? key;
}
