import type { Locale } from "@/lib/i18n";

/** Hardcoded UI chrome strings (not CMS content). English is the key + fallback.
 *  hi/gu are AI-written — flag for review before go-live. */
export const UI_STRINGS: Record<string, { hi: string; gu: string }> = {
  "Learn more": { hi: "और जानें", gu: "વધુ જાણો" },
  "Patient Story": { hi: "मरीज़ की कहानी", gu: "દર્દીની વાર્તા" },
  "Use Calculator": { hi: "कैलकुलेटर उपयोग करें", gu: "કેલ્ક્યુલેટર વાપરો" },
  "View Centre": { hi: "सेंटर देखें", gu: "સેન્ટર જુઓ" },
  "View all awards & achievements": { hi: "सभी पुरस्कार और उपलब्धियाँ देखें", gu: "બધા એવોર્ડ અને સિદ્ધિઓ જુઓ" },
  "View More Events": { hi: "और कार्यक्रम देखें", gu: "વધુ કાર્યક્રમો જુઓ" },
  "Patient review": { hi: "मरीज़ की समीक्षा", gu: "દર્દીની સમીક્ષા" },
  "Google review": { hi: "Google समीक्षा", gu: "Google સમીક્ષા" },
  "* Terms and conditions apply.": { hi: "* नियम एवं शर्तें लागू।", gu: "* નિયમો અને શરતો લાગુ." },
  "Full Name *": { hi: "पूरा नाम *", gu: "પૂરું નામ *" },
  "Phone *": { hi: "फ़ोन *", gu: "ફોન *" },
  "Email": { hi: "ईमेल", gu: "ઇમેઇલ" },
  "Treatment of Interest": { hi: "रुचि का उपचार", gu: "રસની સારવાર" },
  "Preferred Centre": { hi: "पसंदीदा सेंटर", gu: "પસંદગીનું સેન્ટર" },
  "Message": { hi: "संदेश", gu: "સંદેશ" },
  "Sending…": { hi: "भेजा जा रहा है…", gu: "મોકલી રહ્યા છીએ…" },
  "Request a Callback": { hi: "कॉलबैक का अनुरोध करें", gu: "કૉલબેકની વિનંતી કરો" },
  "India's Trusted Fertility Experts · Since 1998": { hi: "भारत के विश्वसनीय फर्टिलिटी विशेषज्ञ · 1998 से", gu: "ભારતના વિશ્વસનીય ફર્ટિલિટી નિષ્ણાતો · 1998 થી" },
  "WhatsApp": { hi: "व्हाट्सऐप", gu: "વોટ્સએપ" },
  "24×7 Care": { hi: "24×7 देखभाल", gu: "24×7 સંભાળ" },
  "Book Consultation": { hi: "कंसल्टेशन बुक करें", gu: "કન્સલ્ટેશન બુક કરો" },
  "Check IVF Eligibility": { hi: "IVF पात्रता जांचें", gu: "IVF પાત્રતા ચકાસો" },
  "WhatsApp Now": { hi: "व्हाट्सऐप करें", gu: "વોટ્સએપ કરો" },
  "Call Now": { hi: "अभी कॉल करें", gu: "હમણાં કૉલ કરો" },

  // Contact page chrome
  "Home": { hi: "होम", gu: "હોમ" },
  "Contact Us": { hi: "संपर्क करें", gu: "અમારો સંપર્ક કરો" },
  "Call Us": { hi: "कॉल करें", gu: "કૉલ કરો" },
  "Chat with our team": { hi: "हमारी टीम से चैट करें", gu: "અમારી ટીમ સાથે ચેટ કરો" },
  "24×7 phone support — clinic visiting hours vary by centre": { hi: "24×7 फोन सपोर्ट — क्लिनिक विज़िटिंग आवर्स सेंटर के अनुसार अलग-अलग हैं", gu: "24×7 ફોન સપોર્ટ — ક્લિનિક વિઝિટિંગ અવર્સ સેન્ટર પ્રમાણે અલગ-અલગ છે" },
  "Quick replies, every day": { hi: "हर दिन त्वरित जवाब", gu: "દરરોજ ઝડપી જવાબ" },
  "We reply within 24 hours": { hi: "हम 24 घंटों के भीतर जवाब देते हैं", gu: "અમે 24 કલાકમાં જવાબ આપીએ છીએ" },
  "Our Network": { hi: "हमारा नेटवर्क", gu: "અમારું નેટવર્ક" },
  "Find a Bavishi Fertility Institute": { hi: "Bavishi Fertility Institute खोजें", gu: "Bavishi Fertility Institute શોધો" },
  "near you": { hi: "आपके पास", gu: "તમારી નજીક" },
  "14 fertility centres across 8 Indian cities — world-class care, close to home. Phone & WhatsApp support is available 24×7; centre visiting hours are listed below.": { hi: "8 भारतीय शहरों में 14 फर्टिलिटी सेंटर — विश्वस्तरीय देखभाल, घर के पास। फोन और व्हाट्सऐप सपोर्ट 24×7 उपलब्ध है; सेंटर के विज़िटिंग आवर्स नीचे दिए गए हैं।", gu: "8 ભારતીય શહેરોમાં 14 ફર્ટિલિટી સેન્ટર — વિશ્વસ્તરીય સંભાળ, ઘરની નજીક. ફોન અને વોટ્સએપ સપોર્ટ 24×7 ઉપલબ્ધ છે; સેન્ટરના વિઝિટિંગ અવર્સ નીચે આપેલા છે." },
  "Call": { hi: "कॉल", gu: "કૉલ" },
  "Directions": { hi: "दिशा-निर्देश", gu: "દિશા-નિર્દેશો" },
  "Need help choosing the right centre?": { hi: "सही सेंटर चुनने में मदद चाहिए?", gu: "યોગ્ય સેન્ટર પસંદ કરવામાં મદદ જોઈએ છે?" },
  "Our counsellors will guide you to the Bavishi Fertility Institute centre nearest you.": { hi: "हमारे काउंसलर आपको आपके नज़दीकी Bavishi Fertility Institute सेंटर तक मार्गदर्शन देंगे।", gu: "અમારા કાઉન્સેલર્સ તમને તમારા નજીકના Bavishi Fertility Institute સેન્ટર સુધી માર્ગદર્શન આપશે." },
  "FAQ": { hi: "सामान्य प्रश्न", gu: "વારંવાર પુછાતા પ્રશ્નો" },
  "Getting in touch —": { hi: "संपर्क करना —", gu: "સંપર્ક કરવો —" },
  "answered": { hi: "आसान बनाया गया", gu: "સરળ બનાવ્યું" },
  "Your journey to parenthood starts with": { hi: "पेरेंटहुड की आपकी यात्रा शुरू होती है", gu: "પેરેન્ટહુડની તમારી યાત્રા શરૂ થાય છે" },
  "one message.": { hi: "एक संदेश से।", gu: "એક સંદેશથી." },
  "WhatsApp Us": { hi: "व्हाट्सऐप करें", gu: "વોટ્સએપ કરો" },

  // Contact page hero + FAQ content (fallback copy — used when CMS has no hi/gu override)
  "We're here for you": { hi: "हम आपके लिए यहाँ हैं", gu: "અમે તમારા માટે અહીં છીએ" },
  "Contact": { hi: "संपर्क करें", gu: "સંપર્ક કરો" },
  "Have a question or ready to begin? Reach out — confidentially and without obligation. Our fertility counsellors are here to guide your very first step.": { hi: "कोई सवाल है या शुरुआत करने के लिए तैयार हैं? गोपनीय रूप से और बिना किसी दायित्व के संपर्क करें — हमारे फर्टिलिटी काउंसलर आपके पहले कदम में मार्गदर्शन के लिए यहाँ हैं।", gu: "કોઈ પ્રશ્ન છે અથવા શરૂઆત કરવા તૈયાર છો? ગોપનીય રીતે અને કોઈપણ જવાબદારી વિના સંપર્ક કરો — અમારા ફર્ટિલિટી કાઉન્સેલર્સ તમારા પ્રથમ પગલામાં માર્ગદર્શન આપવા માટે અહીં છે." },
  "How do I book an appointment at Bavishi Fertility Institute?": { hi: "मैं Bavishi Fertility Institute में अपॉइंटमेंट कैसे बुक करूं?", gu: "હું Bavishi Fertility Institute માં એપોઇન્ટમેન્ટ કેવી રીતે બુક કરું?" },
  "Fill in the enquiry form on this page, call us on +91 97126 22288, or message us on WhatsApp. Our team will help you choose the nearest centre and a convenient time.": { hi: "इस पेज पर पूछताछ फॉर्म भरें, हमें +91 97126 22288 पर कॉल करें, या व्हाट्सऐप पर संदेश भेजें। हमारी टीम आपको नज़दीकी सेंटर और सुविधाजनक समय चुनने में मदद करेगी।", gu: "આ પેજ પર પૂછપરછ ફોર્મ ભરો, અમને +91 97126 22288 પર કૉલ કરો, અથવા વોટ્સએપ પર સંદેશ મોકલો. અમારી ટીમ તમને નજીકનું સેન્ટર અને અનુકૂળ સમય પસંદ કરવામાં મદદ કરશે." },
  "Which Bavishi Fertility Institute centre is nearest to me?": { hi: "मेरे सबसे नज़दीक कौन सा Bavishi Fertility Institute सेंटर है?", gu: "મારી સૌથી નજીક કયું Bavishi Fertility Institute સેન્ટર છે?" },
  "We have 14 centres across 8 cities — Ahmedabad, Mumbai, Vadodara, Surat, Bhuj, Bhavnagar, Anand and Varanasi. Tell us your city and we'll connect you to the closest one.": { hi: "हमारे 8 शहरों — अहमदाबाद, मुंबई, वडोदरा, सूरत, भुज, भावनगर, आनंद और वाराणसी — में 14 सेंटर हैं। हमें अपना शहर बताएं, हम आपको सबसे नज़दीकी सेंटर से जोड़ देंगे।", gu: "અમારા 8 શહેરો — અમદાવાદ, મુંબઈ, વડોદરા, સુરત, ભુજ, ભાવનગર, આણંદ અને વારાણસી — માં 14 સેન્ટર છે. અમને તમારું શહેર જણાવો, અમે તમને સૌથી નજીકના સેન્ટર સાથે જોડીશું." },
  "Do you offer free consultations?": { hi: "क्या आप मुफ़्त कंसल्टेशन देते हैं?", gu: "શું તમે મફત કન્સલ્ટેશન આપો છો?" },
  "We understand that choosing the right fertility clinic is an important decision. To ensure every couple receives dedicated time, expert guidance, and a personalised evaluation, our consultations are not offered free of charge. However, we periodically offer special free consultation slots as part of limited-time programs. Please contact us to check current availability.": { hi: "हम समझते हैं कि सही फर्टिलिटी क्लिनिक चुनना एक महत्वपूर्ण निर्णय है। हर कपल को समर्पित समय, विशेषज्ञ मार्गदर्शन और व्यक्तिगत मूल्यांकन मिले, इसके लिए हमारे कंसल्टेशन मुफ़्त नहीं हैं। हालांकि, हम समय-समय पर सीमित अवधि के कार्यक्रमों के तहत विशेष मुफ़्त कंसल्टेशन स्लॉट भी देते हैं। वर्तमान उपलब्धता जानने के लिए कृपया हमसे संपर्क करें।", gu: "અમે સમજીએ છીએ કે યોગ્ય ફર્ટિલિટી ક્લિનિક પસંદ કરવો એ મહત્વનો નિર્ણય છે. દરેક કપલને સમર્પિત સમય, નિષ્ણાત માર્ગદર્શન અને વ્યક્તિગત મૂલ્યાંકન મળે તે માટે, અમારા કન્સલ્ટેશન મફત આપવામાં આવતા નથી. જોકે, અમે સમયાંતરે મર્યાદિત-સમયના કાર્યક્રમો હેઠળ ખાસ મફત કન્સલ્ટેશન સ્લોટ ઓફર કરીએ છીએ. હાલની ઉપલબ્ધતા ચકાસવા કૃપા કરી અમારો સંપર્ક કરો." },
  "Do you treat international patients?": { hi: "क्या आप अंतरराष्ट्रीय मरीज़ों का इलाज करते हैं?", gu: "શું તમે આંતરરાષ્ટ્રીય દર્દીઓની સારવાર કરો છો?" },
  "Yes — 300+ international patients choose Bavishi Fertility Institute every year. We provide end-to-end support including treatment planning and coordination across our 14 centres.": { hi: "हाँ — हर साल 300+ अंतरराष्ट्रीय मरीज़ Bavishi Fertility Institute चुनते हैं। हम अपने 14 सेंटरों में उपचार योजना और समन्वय सहित संपूर्ण सहायता प्रदान करते हैं।", gu: "હા — દર વર્ષે 300+ આંતરરાષ્ટ્રીય દર્દીઓ Bavishi Fertility Institute પસંદ કરે છે. અમે અમારા 14 સેન્ટરમાં સારવાર આયોજન અને સંકલન સહિત સંપૂર્ણ સહાય પૂરી પાડીએ છીએ." },

  // IVF Cost Calculator
  "Calculators": { hi: "कैलकुलेटर", gu: "કેલ્ક્યુલેટર" },
  "Transparent Estimates · No Hidden Surprises": { hi: "पारदर्शी अनुमान · कोई छिपा हुआ आश्चर्य नहीं", gu: "પારદર્શક અંદાજ · કોઈ છુપું આશ્ચર્ય નહીં" },
  "Free Tool": { hi: "मुफ़्त टूल", gu: "મફત ટૂલ" },
  "Instant Results": { hi: "तुरंत परिणाम", gu: "તાત્કાલિક પરિણામ" },
  "No Data Stored": { hi: "कोई डेटा सेव नहीं होता", gu: "કોઈ ડેટા સેવ થતો નથી" },
  "Typical IVF cycle cost": { hi: "सामान्य IVF साइकल लागत", gu: "સામાન્ય IVF સાયકલ ખર્ચ" },
  "Average cycles for success": { hi: "सफलता के लिए औसत साइकल", gu: "સફળતા માટે સરેરાશ સાયકલ" },
  "Success rate with right protocol": { hi: "सही प्रोटोकॉल के साथ सफलता दर", gu: "યોગ્ય પ્રોટોકોલ સાથે સફળતા દર" },
  "How This Calculator Works": { hi: "यह कैलकुलेटर कैसे काम करता है", gu: "આ કેલ્ક્યુલેટર કેવી રીતે કામ કરે છે" },
  "Transparent cost estimates based on Bavishi Fertility Institute pricing ranges.": { hi: "Bavishi Fertility Institute की मूल्य सीमाओं पर आधारित पारदर्शी लागत अनुमान।", gu: "Bavishi Fertility Institute ની કિંમત શ્રેણી પર આધારિત પારદર્શક ખર્ચ અંદાજ." },
  "Choose Your IVF Type": { hi: "अपना IVF प्रकार चुनें", gu: "તમારો IVF પ્રકાર પસંદ કરો" },
  "Select from Standard IVF, ICSI, Frozen Embryo Transfer, or Donor Egg IVF — each with different base costs.": { hi: "स्टैंडर्ड IVF, ICSI, फ्रोज़न एम्ब्रियो ट्रांसफर, या डोनर एग IVF में से चुनें — हर एक की बेस लागत अलग है।", gu: "સ્ટાન્ડર્ડ IVF, ICSI, ફ્રોઝન એમ્બ્રિયો ટ્રાન્સફર, અથવા ડોનર એગ IVF માંથી પસંદ કરો — દરેકની બેઝ કિંમત અલગ છે." },
  "Select Add-Ons": { hi: "ऐड-ऑन चुनें", gu: "એડ-ઓન પસંદ કરો" },
  "Add optional procedures like PGT-A, embryo freezing, ERA, or laser hatching that apply to your situation.": { hi: "PGT-A, एम्ब्रियो फ्रीज़िंग, ERA, या लेज़र हैचिंग जैसी वैकल्पिक प्रक्रियाएं जोड़ें जो आपकी स्थिति पर लागू होती हैं।", gu: "PGT-A, એમ્બ્રિયો ફ્રીઝિંગ, ERA, અથવા લેસર હેચિંગ જેવી વૈકલ્પિક પ્રક્રિયાઓ ઉમેરો જે તમારી સ્થિતિ પર લાગુ પડે છે." },
  "Set Number of Cycles": { hi: "साइकल की संख्या तय करें", gu: "સાયકલની સંખ્યા સેટ કરો" },
  "Planning for 1 cycle, or budgeting for 2–3? Adjust and see how the total investment changes.": { hi: "1 साइकल की योजना बना रहे हैं, या 2–3 के लिए बजट बना रहे हैं? समायोजित करें और देखें कि कुल निवेश कैसे बदलता है।", gu: "1 સાયકલનું આયોજન કરી રહ્યા છો, કે 2–3 માટે બજેટ બનાવી રહ્યા છો? એડજસ્ટ કરો અને જુઓ કુલ રોકાણ કેવી રીતે બદલાય છે." },
  "Get Your Estimate": { hi: "अपना अनुमान प्राप्त करें", gu: "તમારો અંદાજ મેળવો" },
  "See a transparent range for per-cycle and total cost, with a full line-item breakdown.": { hi: "प्रति साइकल और कुल लागत की पारदर्शी सीमा देखें, पूरी लाइन-आइटम ब्रेकडाउन के साथ।", gu: "પ્રતિ સાયકલ અને કુલ ખર્ચની પારદર્શક શ્રેણી જુઓ, સંપૂર્ણ લાઇન-આઇટમ બ્રેકડાઉન સાથે." },
  "Why Know Your Costs Upfront?": { hi: "अपनी लागत पहले से क्यों जानें?", gu: "તમારો ખર્ચ અગાઉથી શા માટે જાણવો?" },
  "Financial clarity removes one major stressor from your fertility journey.": { hi: "वित्तीय स्पष्टता आपकी फर्टिलिटी यात्रा से एक बड़ा तनाव दूर करती है।", gu: "નાણાકીય સ્પષ્ટતા તમારી ફર્ટિલિટી યાત્રામાંથી એક મોટો તણાવ દૂર કરે છે." },
  "No Unexpected Bills": { hi: "कोई अप्रत्याशित बिल नहीं", gu: "કોઈ અણધાર્યા બિલ નહીં" },
  "Know what to expect before you commit. Our estimates include medication ranges and common add-ons.": { hi: "प्रतिबद्ध होने से पहले जानें कि क्या उम्मीद करनी है। हमारे अनुमानों में दवा की सीमाएं और सामान्य ऐड-ऑन शामिल हैं।", gu: "કમિટ કરતા પહેલા જાણો શું અપેક્ષા રાખવી. અમારા અંદાજમાં દવાની શ્રેણી અને સામાન્ય એડ-ઓનનો સમાવેશ થાય છે." },
  "Plan Your Finances": { hi: "अपने वित्त की योजना बनाएं", gu: "તમારા નાણાંનું આયોજન કરો" },
  "Use the cost range to plan savings, explore EMI options, or check insurance coverage in advance.": { hi: "बचत की योजना बनाने, EMI विकल्प तलाशने, या पहले से बीमा कवरेज जांचने के लिए लागत सीमा का उपयोग करें।", gu: "બચતનું આયોજન કરવા, EMI વિકલ્પો શોધવા, અથવા અગાઉથી વીમા કવરેજ ચકાસવા માટે ખર્ચ શ્રેણીનો ઉપયોગ કરો." },
  "Compare Options": { hi: "विकल्पों की तुलना करें", gu: "વિકલ્પોની તુલના કરો" },
  "See how cycle type and add-ons affect your investment before making any decisions.": { hi: "कोई भी निर्णय लेने से पहले देखें कि साइकल प्रकार और ऐड-ऑन आपके निवेश को कैसे प्रभावित करते हैं।", gu: "કોઈપણ નિર્ણય લેતા પહેલા જુઓ સાયકલ પ્રકાર અને એડ-ઓન તમારા રોકાણને કેવી રીતે અસર કરે છે." },
  "Family Discussion Ready": { hi: "पारिवारिक चर्चा के लिए तैयार", gu: "કૌટુંબિક ચર્ચા માટે તૈયાર" },
  "Share a clear cost breakdown with your partner to make decisions together with full information.": { hi: "पूरी जानकारी के साथ मिलकर निर्णय लेने के लिए अपने पार्टनर के साथ स्पष्ट लागत ब्रेकडाउन साझा करें।", gu: "સંપૂર્ણ માહિતી સાથે મળીને નિર્ણય લેવા માટે તમારા પાર્ટનર સાથે સ્પષ્ટ ખર્ચ બ્રેકડાઉન શેર કરો." },
  "Prioritise Your Add-Ons": { hi: "अपने ऐड-ऑन को प्राथमिकता दें", gu: "તમારા એડ-ઓનને પ્રાધાન્ય આપો" },
  "Understand which add-ons are most cost-effective for your specific situation — ask your specialist.": { hi: "समझें कि आपकी विशिष्ट स्थिति के लिए कौन से ऐड-ऑन सबसे किफ़ायती हैं — अपने विशेषज्ञ से पूछें।", gu: "સમજો તમારી ચોક્કસ સ્થિતિ માટે કયા એડ-ઓન સૌથી કિફાયતી છે — તમારા નિષ્ણાતને પૂછો." },
  "Reduce Financial Anxiety": { hi: "वित्तीय चिंता कम करें", gu: "નાણાકીય ચિંતા ઘટાડો" },
  "Uncertainty about cost is one of the biggest barriers to seeking care. This calculator removes that barrier.": { hi: "लागत के बारे में अनिश्चितता देखभाल लेने में सबसे बड़ी बाधाओं में से एक है। यह कैलकुलेटर उस बाधा को दूर करता है।", gu: "ખર્ચ વિશે અનિશ્ચિતતા સંભાળ મેળવવામાં સૌથી મોટા અવરોધોમાંનો એક છે. આ કેલ્ક્યુલેટર તે અવરોધ દૂર કરે છે." },
  "Treatment Type": { hi: "उपचार प्रकार", gu: "સારવાર પ્રકાર" },
  "Type of IVF cycle": { hi: "IVF साइकल का प्रकार", gu: "IVF સાયકલનો પ્રકાર" },
  "Standard IVF": { hi: "स्टैंडर्ड IVF", gu: "સ્ટાન્ડર્ડ IVF" },
  "IVF with ICSI": { hi: "ICSI के साथ IVF", gu: "ICSI સાથે IVF" },
  "Frozen Embryo Transfer (FET)": { hi: "फ्रोज़न एम्ब्रियो ट्रांसफर (FET)", gu: "ફ્રોઝન એમ્બ્રિયો ટ્રાન્સફર (FET)" },
  "Donor Egg IVF": { hi: "डोनर एग IVF", gu: "ડોનર એગ IVF" },
  "Number of cycles": { hi: "साइकल की संख्या", gu: "સાયકલની સંખ્યા" },
  "1 cycle": { hi: "1 साइकल", gu: "1 સાયકલ" },
  "2 cycles": { hi: "2 साइकल", gu: "2 સાયકલ" },
  "3 cycles": { hi: "3 साइकल", gu: "3 સાયકલ" },
  "4+ cycles (budget planning)": { hi: "4+ साइकल (बजट योजना)", gu: "4+ સાયકલ (બજેટ આયોજન)" },
  "Add-Ons": { hi: "ऐड-ऑन", gu: "એડ-ઓન" },
  "(select all that apply)": { hi: "(जो लागू हों सभी चुनें)", gu: "(જે લાગુ પડે તે બધા પસંદ કરો)" },
  "Standard IVF (Base)": { hi: "स्टैंडर्ड IVF (आधार)", gu: "સ્ટાન્ડર્ડ IVF (બેઝ)" },
  "IVF + ICSI (Base)": { hi: "IVF + ICSI (आधार)", gu: "IVF + ICSI (બેઝ)" },
  "Frozen Embryo Transfer (Base)": { hi: "फ्रोज़न एम्ब्रियो ट्रांसफर (आधार)", gu: "ફ્રોઝન એમ્બ્રિયો ટ્રાન્સફર (બેઝ)" },
  "Donor Egg IVF (Base)": { hi: "डोनर एग IVF (आधार)", gu: "ડોનર એગ IVF (બેઝ)" },
  "PGT-A Genetic Testing": { hi: "PGT-A जेनेटिक टेस्टिंग", gu: "PGT-A જિનેટિક ટેસ્ટિંગ" },
  "Embryo Freezing & Storage": { hi: "एम्ब्रियो फ्रीज़िंग और स्टोरेज", gu: "એમ્બ્રિયો ફ્રીઝિંગ અને સ્ટોરેજ" },
  "Sperm Freezing": { hi: "स्पर्म फ्रीज़िंग", gu: "સ્પર્મ ફ્રીઝિંગ" },
  "ERA / Endometrial Testing": { hi: "ERA / एंडोमेट्रियल टेस्टिंग", gu: "ERA / એન્ડોમેટ્રિયલ ટેસ્ટિંગ" },
  "Laser Assisted Hatching": { hi: "लेज़र असिस्टेड हैचिंग", gu: "લેસર આસિસ્ટેડ હેચિંગ" },
  "Counselling Support": { hi: "काउंसलिंग सहायता", gu: "કાઉન્સેલિંગ સહાય" },
  "Calculate My IVF Cost": { hi: "मेरी IVF लागत की गणना करें", gu: "મારો IVF ખર્ચ ગણો" },
  "Recalculate": { hi: "फिर से गणना करें", gu: "ફરીથી ગણો" },
  "Estimated Total Investment": { hi: "अनुमानित कुल निवेश", gu: "અંદાજિત કુલ રોકાણ" },
  "For {cycles} cycle{s} including selected add-ons": { hi: "{cycles} साइकल के लिए, चुने गए ऐड-ऑन सहित", gu: "{cycles} સાયકલ માટે, પસંદ કરેલ એડ-ઓન સહિત" },
  "Cost Breakdown (per cycle)": { hi: "लागत ब्रेकडाउन (प्रति साइकल)", gu: "ખર્ચ બ્રેકડાઉન (પ્રતિ સાયકલ)" },
  "Total per cycle": { hi: "प्रति साइकल कुल", gu: "પ્રતિ સાયકલ કુલ" },
  "Get an Exact Quote": { hi: "सटीक कोट प्राप्त करें", gu: "ચોક્કસ ભાવ મેળવો" },
  "Book a consultation at Bavishi Fertility Institute for a precise, personalised cost plan based on your specific diagnosis.": { hi: "अपने विशिष्ट निदान के आधार पर सटीक, व्यक्तिगत लागत योजना के लिए Bavishi Fertility Institute में कंसल्टेशन बुक करें।", gu: "તમારા ચોક્કસ નિદાનના આધારે ચોક્કસ, વ્યક્તિગત ખર્ચ યોજના માટે Bavishi Fertility Institute પર કન્સલ્ટેશન બુક કરો." },
  "Explore EMI Options": { hi: "EMI विकल्प तलाशें", gu: "EMI વિકલ્પો શોધો" },
  "Ask about Bavishi Fertility Institute's flexible payment plans and medical finance options to spread your treatment costs.": { hi: "अपनी उपचार लागत फैलाने के लिए Bavishi Fertility Institute की लचीली भुगतान योजनाओं और मेडिकल फाइनेंस विकल्पों के बारे में पूछें।", gu: "તમારો સારવાર ખર્ચ ફેલાવવા માટે Bavishi Fertility Institute ની લવચીક ચુકવણી યોજનાઓ અને મેડિકલ ફાઇનાન્સ વિકલ્પો વિશે પૂછો." },
  "Review What's Included": { hi: "क्या शामिल है समीक्षा करें", gu: "શું સામેલ છે તે સમીક્ષા કરો" },
  "Always ask for a full itemised quote — medications, scans, blood tests, and lab fees can add significantly.": { hi: "हमेशा पूरी आइटमाइज़्ड कोट मांगें — दवाएं, स्कैन, ब्लड टेस्ट और लैब फीस काफी बढ़ सकती हैं।", gu: "હંમેશા સંપૂર્ણ આઇટમાઇઝ્ડ ભાવ માંગો — દવાઓ, સ્કેન, બ્લડ ટેસ્ટ અને લેબ ફી નોંધપાત્ર રીતે વધી શકે છે." },
  "Consider a Package Deal": { hi: "पैकेज डील पर विचार करें", gu: "પેકેજ ડીલ પર વિચાર કરો" },
  "Multi-cycle packages often offer better value. Ask Bavishi Fertility Institute about bundled pricing for 2–3 cycle commitments.": { hi: "मल्टी-साइकल पैकेज अक्सर बेहतर वैल्यू देते हैं। 2–3 साइकल प्रतिबद्धता के लिए बंडल्ड प्राइसिंग के बारे में Bavishi Fertility Institute से पूछें।", gu: "મલ્ટી-સાયકલ પેકેજ ઘણીવાર વધુ સારું મૂલ્ય આપે છે. 2–3 સાયકલ કમિટમેન્ટ માટે બંડલ્ડ પ્રાઇસિંગ વિશે Bavishi Fertility Institute ને પૂછો." },
  "* Cost estimates are indicative ranges for planning purposes only. Actual costs depend on your individual protocol, medications, and clinic. Request a full itemised quote at your consultation.": { hi: "* लागत अनुमान केवल योजना उद्देश्यों के लिए संकेतात्मक सीमाएं हैं। वास्तविक लागत आपके व्यक्तिगत प्रोटोकॉल, दवाओं और क्लिनिक पर निर्भर करती है। अपने कंसल्टेशन में पूरा आइटमाइज़्ड कोट मांगें।", gu: "* ખર્ચ અંદાજ ફક્ત આયોજન હેતુ માટે સૂચક શ્રેણી છે. વાસ્તવિક ખર્ચ તમારા વ્યક્તિગત પ્રોટોકોલ, દવાઓ અને ક્લિનિક પર આધારિત છે. તમારા કન્સલ્ટેશન પર સંપૂર્ણ આઇટમાઇઝ્ડ ભાવ માંગો." },
  "Using the cost calculator helped us budget properly for two cycles from the start. We weren't blindsided by any numbers — and that made the whole process less stressful.": { hi: "लागत कैलकुलेटर का उपयोग करने से हमें शुरू से ही दो साइकल के लिए सही ढंग से बजट बनाने में मदद मिली। हम किसी भी आंकड़े से हैरान नहीं हुए — और इससे पूरी प्रक्रिया कम तनावपूर्ण हो गई।", gu: "ખર્ચ કેલ્ક્યુલેટરનો ઉપયોગ કરવાથી અમને શરૂઆતથી જ બે સાયકલ માટે યોગ્ય રીતે બજેટ બનાવવામાં મદદ મળી. અમે કોઈપણ આંકડાથી ચોંક્યા નહીં — અને તેનાથી આખી પ્રક્રિયા ઓછી તણાવપૂર્ણ બની." },
  "— Patient at Bavishi Fertility Institute": { hi: "— Bavishi Fertility Institute में मरीज़", gu: "— Bavishi Fertility Institute ખાતે દર્દી" },
  "Who Should Use This Calculator?": { hi: "इस कैलकुलेटर का उपयोग किसे करना चाहिए?", gu: "આ કેલ્ક્યુલેટરનો ઉપયોગ કોણે કરવો જોઈએ?" },
  "Planning your first IVF cycle": { hi: "अपने पहले IVF साइकल की योजना बना रहे हैं", gu: "તમારા પ્રથમ IVF સાયકલનું આયોજન કરી રહ્યા છો" },
  "Get a realistic cost estimate before your first consultation so there are no surprises.": { hi: "अपने पहले कंसल्टेशन से पहले एक यथार्थवादी लागत अनुमान प्राप्त करें ताकि कोई आश्चर्य न हो।", gu: "તમારા પ્રથમ કન્સલ્ટેશન પહેલાં વાસ્તવિક ખર્ચ અંદાજ મેળવો જેથી કોઈ આશ્ચર્ય ન થાય." },
  "Budgeting for multiple cycles": { hi: "कई साइकल के लिए बजट बना रहे हैं", gu: "બહુવિધ સાયકલ માટે બજેટ બનાવી રહ્યા છો" },
  "See how total investment scales across 2–4 cycles and plan financially for the full journey.": { hi: "देखें कि 2–4 साइकल में कुल निवेश कैसे बढ़ता है और पूरी यात्रा के लिए वित्तीय योजना बनाएं।", gu: "જુઓ 2–4 સાયકલમાં કુલ રોકાણ કેવી રીતે વધે છે અને સંપૂર્ણ યાત્રા માટે નાણાકીય આયોજન કરો." },
  "Exploring financing options": { hi: "फाइनेंसिंग विकल्प तलाश रहे हैं", gu: "ફાઇનાન્સિંગ વિકલ્પો શોધી રહ્યા છો" },
  "Use the estimate to understand how much you need to save or borrow for EMI planning.": { hi: "EMI योजना के लिए आपको कितनी बचत या उधार लेने की आवश्यकता है, यह समझने के लिए अनुमान का उपयोग करें।", gu: "EMI આયોજન માટે તમારે કેટલી બચત અથવા ઉધાર લેવાની જરૂર છે તે સમજવા અંદાજનો ઉપયોગ કરો." },
  "Comparing treatment types": { hi: "उपचार प्रकारों की तुलना कर रहे हैं", gu: "સારવાર પ્રકારોની તુલના કરી રહ્યા છો" },
  "Switch between Standard IVF, ICSI, FET, and Donor Egg to compare costs before deciding.": { hi: "निर्णय लेने से पहले लागतों की तुलना करने के लिए स्टैंडर्ड IVF, ICSI, FET और डोनर एग के बीच स्विच करें।", gu: "નિર્ણય લેતા પહેલા ખર્ચની તુલના કરવા સ્ટાન્ડર્ડ IVF, ICSI, FET અને ડોનર એગ વચ્ચે સ્વિચ કરો." },
  "Understanding add-on costs": { hi: "ऐड-ऑन लागत को समझना", gu: "એડ-ઓન ખર્ચને સમજવું" },
  "See exactly how PGT-A, ERA, or other add-ons affect your total investment.": { hi: "ठीक-ठीक देखें कि PGT-A, ERA, या अन्य ऐड-ऑन आपके कुल निवेश को कैसे प्रभावित करते हैं।", gu: "બરાબર જુઓ PGT-A, ERA, અથવા અન્ય એડ-ઓન તમારા કુલ રોકાણને કેવી રીતે અસર કરે છે." },
  "Family financial planning": { hi: "पारिवारिक वित्तीय योजना", gu: "કૌટુંબિક નાણાકીય આયોજન" },
  "Share a clear, itemised estimate with your partner before making major treatment decisions.": { hi: "प्रमुख उपचार निर्णय लेने से पहले अपने पार्टनर के साथ एक स्पष्ट, आइटमाइज़्ड अनुमान साझा करें।", gu: "મોટા સારવાર નિર્ણયો લેતા પહેલા તમારા પાર્ટનર સાથે સ્પષ્ટ, આઇટમાઇઝ્ડ અંદાજ શેર કરો." },
  "What this calculator helps you do": { hi: "यह कैलकुलेटर आपकी क्या मदद करता है", gu: "આ કેલ્ક્યુલેટર તમને શું કરવામાં મદદ કરે છે" },
  "Budget Your Treatment": { hi: "अपने उपचार का बजट बनाएं", gu: "તમારી સારવારનું બજેટ બનાવો" },
  "Get indicative cost ranges for different IVF cycle types and add-on procedures.": { hi: "विभिन्न IVF साइकल प्रकारों और ऐड-ऑन प्रक्रियाओं के लिए संकेतात्मक लागत सीमाएं प्राप्त करें।", gu: "વિવિધ IVF સાયકલ પ્રકારો અને એડ-ઓન પ્રક્રિયાઓ માટે સૂચક ખર્ચ શ્રેણી મેળવો." },
  "See how cycle type and add-ons affect your total investment before booking.": { hi: "बुकिंग से पहले देखें कि साइकल प्रकार और ऐड-ऑन आपके कुल निवेश को कैसे प्रभावित करते हैं।", gu: "બુકિંગ પહેલા જુઓ સાયકલ પ્રકાર અને એડ-ઓન તમારા કુલ રોકાણને કેવી રીતે અસર કરે છે." },
  "Plan Financially": { hi: "वित्तीय रूप से योजना बनाएं", gu: "નાણાકીય રીતે આયોજન કરો" },
  "Use the estimates to explore EMI, insurance, and multi-cycle package options.": { hi: "EMI, बीमा और मल्टी-साइकल पैकेज विकल्पों का पता लगाने के लिए अनुमानों का उपयोग करें।", gu: "EMI, વીમા, અને મલ્ટી-સાયકલ પેકેજ વિકલ્પો શોધવા અંદાજનો ઉપયોગ કરો." },
  "Get a Precise Quote From Us": { hi: "हमसे सटीक कोट प्राप्त करें", gu: "અમારી પાસેથી ચોક્કસ ભાવ મેળવો" },
  "Get an exact cost plan for your IVF treatment at Bavishi Fertility Institute.": { hi: "Bavishi Fertility Institute में अपने IVF उपचार के लिए सटीक लागत योजना प्राप्त करें।", gu: "Bavishi Fertility Institute પર તમારી IVF સારવાર માટે ચોક્કસ ખર્ચ યોજના મેળવો." },
  "Our team will provide a full itemised quote, discuss flexible payment options, and help you plan the most cost-effective path to your goal.": { hi: "हमारी टीम पूरा आइटमाइज़्ड कोट देगी, लचीले भुगतान विकल्पों पर चर्चा करेगी, और आपके लक्ष्य के लिए सबसे किफ़ायती रास्ता बनाने में मदद करेगी।", gu: "અમારી ટીમ સંપૂર્ણ આઇટમાઇઝ્ડ ભાવ આપશે, લવચીક ચુકવણી વિકલ્પોની ચર્ચા કરશે, અને તમારા લક્ષ્ય માટે સૌથી કિફાયતી માર્ગ બનાવવામાં મદદ કરશે." },
  "WhatsApp Support": { hi: "व्हाट्सऐप सहायता", gu: "વોટ્સએપ સહાય" },
  "About This Calculator": { hi: "इस कैलकुलेटर के बारे में", gu: "આ કેલ્ક્યુલેટર વિશે" },
  "Frequently Asked Questions": { hi: "अक्सर पूछे जाने वाले सवाल", gu: "વારંવાર પુછાતા પ્રશ્નો" },

  // Calculator cross-links
  "Fertility Calculators To Plan Your Pregnancy Journey": { hi: "आपकी प्रेगनेंसी यात्रा की योजना बनाने के लिए फर्टिलिटी कैलकुलेटर", gu: "તમારી પ્રેગ્નન્સી યાત્રાનું આયોજન કરવા ફર્ટિલિટી કેલ્ક્યુલેટર" },
  "Use our expert-designed fertility calculators to estimate IVF success rates, track ovulation, understand your fertile window, and plan your journey to parenthood with confidence.": { hi: "IVF सफलता दर का अनुमान लगाने, ओव्यूलेशन ट्रैक करने, अपनी फर्टाइल विंडो समझने और आत्मविश्वास के साथ पेरेंटहुड की यात्रा की योजना बनाने के लिए हमारे विशेषज्ञ-डिज़ाइन किए गए फर्टिलिटी कैलकुलेटर का उपयोग करें।", gu: "IVF સફળતા દરનો અંદાજ કાઢવા, ઓવ્યુલેશન ટ્રેક કરવા, તમારી ફર્ટાઇલ વિન્ડો સમજવા, અને આત્મવિશ્વાસ સાથે પેરેન્ટહુડની યાત્રાનું આયોજન કરવા અમારા નિષ્ણાત-ડિઝાઇન કરેલા ફર્ટિલિટી કેલ્ક્યુલેટરનો ઉપયોગ કરો." },
  "IVF Success Rate Calculator": { hi: "IVF सफलता दर कैलकुलेटर", gu: "IVF સફળતા દર કેલ્ક્યુલેટર" },
  "Fertile Period Calculator": { hi: "फर्टाइल पीरियड कैलकुलेटर", gu: "ફર્ટાઇલ પીરિયડ કેલ્ક્યુલેટર" },
  "Risk of Repeat Miscarriage Calculator": { hi: "दोबारा मिसकैरेज के जोखिम का कैलकुलेटर", gu: "ફરીથી મિસકેરેજના જોખમનું કેલ્ક્યુલેટર" },
  "Natural Pregnancy Calculator": { hi: "नेचुरल प्रेगनेंसी कैलकुलेटर", gu: "નેચરલ પ્રેગ્નન્સી કેલ્ક્યુલેટર" },
  "IVF Cost Calculator": { hi: "IVF लागत कैलकुलेटर", gu: "IVF ખર્ચ કેલ્ક્યુલેટર" },
  "AMH Level Interpreter": { hi: "AMH लेवल इंटरप्रेटर", gu: "AMH લેવલ ઇન્ટરપ્રેટર" },
  "Ovulation Calculator": { hi: "ओव्यूलेशन कैलकुलेटर", gu: "ઓવ્યુલેશન કેલ્ક્યુલેટર" },
  "Semen Analysis Calculator": { hi: "सीमेन एनालिसिस कैलकुलेटर", gu: "સીમેન એનાલિસિસ કેલ્ક્યુલેટર" },

  // IVF Success Rate Calculator
  "Evidence-Based · Clinically Informed": { hi: "साक्ष्य-आधारित · चिकित्सकीय रूप से सूचित", gu: "પુરાવા-આધારિત · તબીબી રીતે માહિતગાર" },
  "Bavishi Fertility Rate": { hi: "Bavishi Fertility दर", gu: "Bavishi Fertility દર" },
  "Most important factor": { hi: "सबसे महत्वपूर्ण कारक", gu: "સૌથી મહત્વનું પરિબળ" },
  "Best embryo transfer": { hi: "सर्वश्रेष्ठ एम्ब्रियो ट्रांसफर", gu: "શ્રેષ્ઠ એમ્બ્રિયો ટ્રાન્સફર" },
  "Cumulative success": { hi: "संचयी सफलता", gu: "સંચિત સફળતા" },
  "Your success probability is calculated using the factors that matter most — step by step.": { hi: "आपकी सफलता की संभावना सबसे महत्वपूर्ण कारकों का उपयोग करके, चरण दर चरण गणना की जाती है।", gu: "તમારી સફળતાની સંભાવના સૌથી મહત્વના પરિબળોનો ઉપયોગ કરીને, પગલું-દર-પગલું ગણવામાં આવે છે." },
  "Enter Your Age": { hi: "अपनी उम्र दर्ज करें", gu: "તમારી ઉંમર દાખલ કરો" },
  "Age is the strongest single predictor of IVF success. We start with your age-group's published live-birth rate.": { hi: "उम्र IVF सफलता का सबसे मज़बूत एकल संकेतक है। हम आपके आयु-समूह की प्रकाशित लाइव-बर्थ दर से शुरू करते हैं।", gu: "ઉંમર IVF સફળતાનું સૌથી મજબૂત એકલ પરિબળ છે. અમે તમારા વય-જૂથના પ્રકાશિત લાઇવ-બર્થ દરથી શરૂ કરીએ છીએ." },
  "Share Your Diagnosis": { hi: "अपना निदान साझा करें", gu: "તમારું નિદાન શેર કરો" },
  "Your primary fertility diagnosis is the second key factor — it adds or reduces from your age baseline.": { hi: "आपका प्राथमिक फर्टिलिटी निदान दूसरा प्रमुख कारक है — यह आपकी उम्र के आधार में जोड़ता या घटाता है।", gu: "તમારું પ્રાથમિક ફર્ટિલિટી નિદાન બીજું મુખ્ય પરિબળ છે — તે તમારા ઉંમર બેઝલાઇનમાં ઉમેરે અથવા ઘટાડે છે." },
  "Add Clinical Factors": { hi: "क्लिनिकल कारक जोड़ें", gu: "ક્લિનિકલ પરિબળો ઉમેરો" },
  "Treatment history, embryo type, and egg source are factored in to personalise your estimate.": { hi: "आपके अनुमान को व्यक्तिगत बनाने के लिए उपचार इतिहास, एम्ब्रियो प्रकार और एग स्रोत को शामिल किया जाता है।", gu: "તમારા અંદાજને વ્યક્તિગત બનાવવા સારવાર ઇતિહાસ, એમ્બ્રિયો પ્રકાર, અને એગ સ્રોતનો સમાવેશ કરવામાં આવે છે." },
  "See Your Probability": { hi: "अपनी संभावना देखें", gu: "તમારી સંભાવના જુઓ" },
  "Get your personalised success rate instantly, with a breakdown of every factor that shaped it.": { hi: "तुरंत अपनी व्यक्तिगत सफलता दर प्राप्त करें, इसे आकार देने वाले हर कारक के ब्रेकडाउन के साथ।", gu: "તાત્કાલિક તમારો વ્યક્તિગત સફળતા દર મેળવો, તેને આકાર આપતા દરેક પરિબળના બ્રેકડાઉન સાથે." },
  "Why Know Your Success Rate?": { hi: "अपनी सफलता दर क्यों जानें?", gu: "તમારો સફળતા દર શા માટે જાણવો?" },
  "Understanding your odds helps you plan, stay motivated, and make the right decisions.": { hi: "अपनी संभावनाओं को समझना आपको योजना बनाने, प्रेरित रहने और सही निर्णय लेने में मदद करता है।", gu: "તમારી શક્યતાઓ સમજવાથી તમને આયોજન કરવામાં, પ્રેરિત રહેવામાં, અને યોગ્ય નિર્ણય લેવામાં મદદ મળે છે." },
  "Set Realistic Expectations": { hi: "यथार्थवादी अपेक्षाएं निर्धारित करें", gu: "વાસ્તવિક અપેક્ષાઓ સેટ કરો" },
  "Knowing your actual probability helps you prepare emotionally and practically for each cycle.": { hi: "अपनी वास्तविक संभावना जानने से आपको हर साइकल के लिए भावनात्मक और व्यावहारिक रूप से तैयार होने में मदद मिलती है।", gu: "તમારી વાસ્તવિક સંભાવના જાણવાથી તમને દરેક સાયકલ માટે ભાવનાત્મક અને વ્યવહારુ રીતે તૈયાર થવામાં મદદ મળે છે." },
  "Understand What Helps": { hi: "समझें क्या मदद करता है", gu: "શું મદદ કરે છે તે સમજો" },
  "Discover which factors are in your favour and which are modifiable before your next cycle.": { hi: "जानें कौन से कारक आपके पक्ष में हैं और कौन से आपके अगले साइकल से पहले बदले जा सकते हैं।", gu: "તમારા આગામી સાયકલ પહેલાં કયા પરિબળો તમારી તરફેણમાં છે અને કયા બદલી શકાય તેવા છે તે શોધો." },
  "Plan Your Budget": { hi: "अपना बजट बनाएं", gu: "તમારું બજેટ બનાવો" },
  "Your success rate estimate helps you decide how many cycles to budget for and when to review options.": { hi: "आपकी सफलता दर का अनुमान यह तय करने में मदद करता है कि कितने साइकल के लिए बजट बनाना है और विकल्पों की समीक्षा कब करनी है।", gu: "તમારો સફળતા દર અંદાજ કેટલા સાયકલ માટે બજેટ બનાવવું અને ક્યારે વિકલ્પોની સમીક્ષા કરવી તે નક્કી કરવામાં મદદ કરે છે." },
  "Make Informed Decisions": { hi: "सूचित निर्णय लें", gu: "માહિતગાર નિર્ણયો લો" },
  "Evidence-based estimates help you and your doctor choose the right protocol and timing.": { hi: "साक्ष्य-आधारित अनुमान आपको और आपके डॉक्टर को सही प्रोटोकॉल और समय चुनने में मदद करते हैं।", gu: "પુરાવા-આધારિત અંદાજ તમને અને તમારા ડોક્ટરને યોગ્ય પ્રોટોકોલ અને સમય પસંદ કરવામાં મદદ કરે છે." },
  "Stay Motivated": { hi: "प्रेरित रहें", gu: "પ્રેરિત રહો" },
  "Understanding your real chances — not just a generic number — keeps you focused and hopeful.": { hi: "अपनी वास्तविक संभावनाओं को समझना — सिर्फ़ एक सामान्य संख्या नहीं — आपको केंद्रित और आशान्वित रखता है।", gu: "તમારી વાસ્તવિક શક્યતાઓ સમજવી — ફક્ત એક સામાન્ય સંખ્યા નહીં — તમને કેન્દ્રિત અને આશાવાદી રાખે છે." },
  "Time Your Treatment": { hi: "अपने उपचार का समय तय करें", gu: "તમારી સારવારનો સમય નક્કી કરો" },
  "Seeing the age impact first-hand motivates acting at the right moment rather than delaying.": { hi: "उम्र के प्रभाव को प्रत्यक्ष रूप से देखना देरी करने के बजाय सही समय पर कार्य करने के लिए प्रेरित करता है।", gu: "ઉંમરની અસર જાતે જોવાથી વિલંબ કરવાને બદલે યોગ્ય સમયે પગલાં લેવાની પ્રેરણા મળે છે." },
  "About You": { hi: "आपके बारे में", gu: "તમારા વિશે" },
  "Your Age Group": { hi: "आपका आयु समूह", gu: "તમારો વય જૂથ" },
  "— Select age group —": { hi: "— आयु समूह चुनें —", gu: "— વય જૂથ પસંદ કરો —" },
  "Under 30": { hi: "30 से कम", gu: "30 થી ઓછી" },
  "30 – 34": { hi: "30 – 34", gu: "30 – 34" },
  "35 – 37": { hi: "35 – 37", gu: "35 – 37" },
  "38 – 40": { hi: "38 – 40", gu: "38 – 40" },
  "41 – 42": { hi: "41 – 42", gu: "41 – 42" },
  "43 or older": { hi: "43 या अधिक", gu: "43 કે તેથી વધુ" },
  "Primary Diagnosis": { hi: "प्राथमिक निदान", gu: "પ્રાથમિક નિદાન" },
  "— Select diagnosis —": { hi: "— निदान चुनें —", gu: "— નિદાન પસંદ કરો —" },
  "Unexplained infertility": { hi: "अस्पष्ट बांझपन", gu: "અસ્પષ્ટ વંધ્યત્વ" },
  "PCOS / Ovulatory disorder": { hi: "PCOS / ओव्यूलेटरी विकार", gu: "PCOS / ઓવ્યુલેટરી ડિસઓર્ડર" },
  "Tubal factor": { hi: "ट्यूबल कारक", gu: "ટ્યુબલ પરિબળ" },
  "Male factor": { hi: "पुरुष कारक", gu: "પુરુષ પરિબળ" },
  "Severe male factor (azoospermia)": { hi: "गंभीर पुरुष कारक (एज़ोस्पर्मिया)", gu: "ગંભીર પુરુષ પરિબળ (એઝોસ્પર્મિયા)" },
  "Endometriosis": { hi: "एंडोमेट्रियोसिस", gu: "એન્ડોમેટ્રિઓસિસ" },
  "Diminished ovarian reserve": { hi: "कम ओवेरियन रिज़र्व", gu: "ઘટેલ ઓવેરિયન રિઝર્વ" },
  "Uterine factor": { hi: "गर्भाशय कारक", gu: "ગર્ભાશય પરિબળ" },
  "Treatment History": { hi: "उपचार इतिहास", gu: "સારવાર ઇતિહાસ" },
  "Previous IVF Attempts": { hi: "पिछले IVF प्रयास", gu: "અગાઉના IVF પ્રયાસો" },
  "First time": { hi: "पहली बार", gu: "પ્રથમ વખત" },
  "1 before": { hi: "1 पहले", gu: "1 પહેલાં" },
  "2 before": { hi: "2 पहले", gu: "2 પહેલાં" },
  "3+ before": { hi: "3+ पहले", gu: "3+ પહેલાં" },
  "Previous Successful Pregnancy?": { hi: "पिछली सफल गर्भावस्था?", gu: "અગાઉની સફળ ગર્ભાવસ્થા?" },
  "Yes": { hi: "हाँ", gu: "હા" },
  "No": { hi: "नहीं", gu: "ના" },
  "Embryo Details": { hi: "एम्ब्रियो विवरण", gu: "એમ્બ્રિયો વિગતો" },
  "Embryo Transfer Type": { hi: "एम्ब्रियो ट्रांसफर प्रकार", gu: "એમ્બ્રિયો ટ્રાન્સફર પ્રકાર" },
  "Day 5 Blastocyst": { hi: "डे 5 ब्लास्टोसिस्ट", gu: "ડે 5 બ્લાસ્ટોસિસ્ટ" },
  "Day 3 Cleavage": { hi: "डे 3 क्लीवेज", gu: "ડે 3 ક્લીવેજ" },
  "Not Known": { hi: "ज्ञात नहीं", gu: "જાણીતું નથી" },
  "Egg Source": { hi: "एग स्रोत", gu: "એગ સ્રોત" },
  "Own eggs": { hi: "स्वयं के एग", gu: "પોતાના એગ" },
  "Donor eggs": { hi: "डोनर एग", gu: "ડોનર એગ" },
  "Please answer all required questions.": { hi: "कृपया सभी आवश्यक प्रश्नों का उत्तर दें।", gu: "કૃપા કરી બધા જરૂરી પ્રશ્નોના જવાબ આપો." },
  "If your AMH is below 0.5, endometrial thickness below 7mm, or you have severe adenomyosis, please consult a specialist directly.": { hi: "यदि आपका AMH 0.5 से कम है, एंडोमेट्रियल मोटाई 7mm से कम है, या आपको गंभीर एडेनोमायोसिस है, तो कृपया सीधे विशेषज्ञ से परामर्श करें।", gu: "જો તમારું AMH 0.5 થી ઓછું છે, એન્ડોમેટ્રિયલ જાડાઈ 7mm થી ઓછી છે, અથવા તમને ગંભીર એડેનોમાયોસિસ છે, તો કૃપા કરી સીધા નિષ્ણાતની સલાહ લો." },
  "Calculate My Success Rate": { hi: "मेरी सफलता दर की गणना करें", gu: "મારો સફળતા દર ગણો" },
  "Estimated Success Rate Per Cycle": { hi: "प्रति साइकल अनुमानित सफलता दर", gu: "પ્રતિ સાયકલ અંદાજિત સફળતા દર" },
  "Favourable Prognosis": { hi: "अनुकूल पूर्वानुमान", gu: "અનુકૂળ પૂર્વાનુમાન" },
  "Moderate Prognosis": { hi: "मध्यम पूर्वानुमान", gu: "મધ્યમ પૂર્વાનુમાન" },
  "Challenging — Specialist Review Needed": { hi: "चुनौतीपूर्ण — विशेषज्ञ समीक्षा आवश्यक", gu: "પડકારજનક — નિષ્ણાત સમીક્ષા જરૂરી" },
  "Your profile indicates a favourable chance of IVF success. With the right protocol and specialist team, your outlook is genuinely encouraging.": { hi: "आपकी प्रोफ़ाइल IVF सफलता की अनुकूल संभावना दर्शाती है। सही प्रोटोकॉल और विशेषज्ञ टीम के साथ, आपकी संभावनाएं वास्तव में उत्साहजनक हैं।", gu: "તમારી પ્રોફાઇલ IVF સફળતાની અનુકૂળ શક્યતા દર્શાવે છે. યોગ્ય પ્રોટોકોલ અને નિષ્ણાત ટીમ સાથે, તમારો દૃષ્ટિકોણ ખરેખર પ્રોત્સાહક છે." },
  "Your profile shows moderate chances per cycle. Optimising your protocol and addressing modifiable factors can improve your outcome meaningfully.": { hi: "आपकी प्रोफ़ाइल प्रति साइकल मध्यम संभावनाएं दिखाती है। अपने प्रोटोकॉल को अनुकूलित करना और बदले जा सकने वाले कारकों को संबोधित करना आपके परिणाम को सार्थक रूप से बेहतर बना सकता है।", gu: "તમારી પ્રોફાઇલ પ્રતિ સાયકલ મધ્યમ શક્યતાઓ દર્શાવે છે. તમારા પ્રોટોકોલને ઓપ્ટિમાઇઝ કરવાથી અને બદલી શકાય તેવા પરિબળોને સંબોધવાથી તમારું પરિણામ અર્થપૂર્ણ રીતે સુધારી શકાય છે." },
  "Your profile indicates a more challenging prognosis per cycle. However, many patients in this range achieve success with specialist care, optimised protocols, and the right approach.": { hi: "आपकी प्रोफ़ाइल प्रति साइकल अधिक चुनौतीपूर्ण पूर्वानुमान दर्शाती है। हालांकि, इस श्रेणी के कई मरीज़ विशेषज्ञ देखभाल, अनुकूलित प्रोटोकॉल और सही दृष्टिकोण के साथ सफलता प्राप्त करते हैं।", gu: "તમારી પ્રોફાઇલ પ્રતિ સાયકલ વધુ પડકારજનક પૂર્વાનુમાન દર્શાવે છે. જોકે, આ શ્રેણીના ઘણા દર્દીઓ નિષ્ણાત સંભાળ, ઓપ્ટિમાઇઝ્ડ પ્રોટોકોલ, અને યોગ્ય અભિગમ સાથે સફળતા મેળવે છે." },
  "Cumulative chance over 3 cycles: approximately {pct}%": { hi: "3 साइकल में संचयी संभावना: लगभग {pct}%", gu: "3 સાયકલમાં સંચિત સંભાવના: આશરે {pct}%" },
  "Success probability": { hi: "सफलता की संभावना", gu: "સફળતાની સંભાવના" },
  "28% moderate": { hi: "28% मध्यम", gu: "28% મધ્યમ" },
  "50% favourable": { hi: "50% अनुकूल", gu: "50% અનુકૂળ" },
  "How Your Score Was Calculated": { hi: "आपका स्कोर कैसे गणना किया गया", gu: "તમારો સ્કોર કેવી રીતે ગણવામાં આવ્યો" },
  "Age base rate": { hi: "उम्र आधार दर", gu: "ઉંમર બેઝ દર" },
  "65% (donor)": { hi: "65% (डोनर)", gu: "65% (ડોનર)" },
  "Diagnosis": { hi: "निदान", gu: "નિદાન" },
  "Embryo": { hi: "एम्ब्रियो", gu: "એમ્બ્રિયો" },
  "+10% boost": { hi: "+10% बढ़ोतरी", gu: "+10% વધારો" },
  "Day 3": { hi: "डे 3", gu: "ડે 3" },
  "Unknown": { hi: "अज्ञात", gu: "અજ્ઞાત" },
  "Previous attempts": { hi: "पिछले प्रयास", gu: "અગાઉના પ્રયાસો" },
  "Prior successful pregnancy": { hi: "पिछली सफल गर्भावस्था", gu: "અગાઉની સફળ ગર્ભાવસ્થા" },
  "Egg source": { hi: "एग स्रोत", gu: "એગ સ્રોત" },
  "Donor (65% base)": { hi: "डोनर (65% आधार)", gu: "ડોનર (65% બેઝ)" },
  "Consult a Specialist": { hi: "विशेषज्ञ से परामर्श करें", gu: "નિષ્ણાતની સલાહ લો" },
  "Book a consultation to validate your profile and design a personalised protocol.": { hi: "अपनी प्रोफ़ाइल को मान्य करने और व्यक्तिगत प्रोटोकॉल डिज़ाइन करने के लिए कंसल्टेशन बुक करें।", gu: "તમારી પ્રોફાઇલ માન્ય કરવા અને વ્યક્તિગત પ્રોટોકોલ ડિઝાઇન કરવા કન્સલ્ટેશન બુક કરો." },
  "Full Fertility Workup": { hi: "पूर्ण फर्टिलिटी वर्कअप", gu: "સંપૂર્ણ ફર્ટિલિટી વર્કઅપ" },
  "A thorough investigation helps identify factors not captured by this calculator.": { hi: "एक गहन जांच इस कैलकुलेटर द्वारा न पकड़े गए कारकों की पहचान करने में मदद करती है।", gu: "એક સંપૂર્ણ તપાસ આ કેલ્ક્યુલેટર દ્વારા ન પકડાયેલા પરિબળોને ઓળખવામાં મદદ કરે છે." },
  "Optimise Your Health": { hi: "अपने स्वास्थ्य को अनुकूलित करें", gu: "તમારા સ્વાસ્થ્યને ઓપ્ટિમાઇઝ કરો" },
  "Folic acid, vitamin D, and lifestyle changes can meaningfully improve outcomes.": { hi: "फोलिक एसिड, विटामिन D, और जीवनशैली में बदलाव परिणामों को सार्थक रूप से बेहतर बना सकते हैं।", gu: "ફોલિક એસિડ, વિટામિન D, અને જીવનશૈલીમાં ફેરફાર પરિણામોને અર્થપૂર્ણ રીતે સુધારી શકે છે." },
  "Explore All Options": { hi: "सभी विकल्प तलाशें", gu: "બધા વિકલ્પો શોધો" },
  "Ask about multi-cycle packages, donor egg programmes, and advanced techniques like PGT-A.": { hi: "मल्टी-साइकल पैकेज, डोनर एग प्रोग्राम, और PGT-A जैसी उन्नत तकनीकों के बारे में पूछें।", gu: "મલ્ટી-સાયકલ પેકેજ, ડોનર એગ પ્રોગ્રામ, અને PGT-A જેવી અદ્યતન તકનીકો વિશે પૂછો." },
  "* This tool is for educational purposes only and does not constitute medical advice. Success rates vary based on many clinical factors not captured here. Bavishi Fertility Institute accepts no liability for decisions made based solely on this calculator's output.": { hi: "* यह टूल केवल शैक्षिक उद्देश्यों के लिए है और चिकित्सा सलाह नहीं है। सफलता दरें यहां न पकड़े गए कई क्लिनिकल कारकों के आधार पर भिन्न होती हैं। Bavishi Fertility Institute केवल इस कैलकुलेटर के परिणाम के आधार पर लिए गए निर्णयों के लिए कोई ज़िम्मेदारी स्वीकार नहीं करता है।", gu: "* આ ટૂલ ફક્ત શૈક્ષણિક હેતુ માટે છે અને તબીબી સલાહ નથી. સફળતા દર અહીં ન સમાવેલા ઘણા ક્લિનિકલ પરિબળોના આધારે બદલાય છે. Bavishi Fertility Institute ફક્ત આ કેલ્ક્યુલેટરના પરિણામના આધારે લેવાયેલા નિર્ણયો માટે કોઈ જવાબદારી સ્વીકારતું નથી." },
  "Knowing my actual success rate — not just a general number — helped me and my husband decide to go for a second cycle. That cycle gave us our child.": { hi: "अपनी वास्तविक सफलता दर जानना — सिर्फ़ एक सामान्य संख्या नहीं — मुझे और मेरे पति को दूसरे साइकल के लिए जाने का निर्णय लेने में मदद मिली। उस साइकल ने हमें हमारा बच्चा दिया।", gu: "મારો વાસ્તવિક સફળતા દર જાણવો — ફક્ત એક સામાન્ય સંખ્યા નહીં — મને અને મારા પતિને બીજા સાયકલ માટે જવાનો નિર્ણય લેવામાં મદદ કરી. તે સાયકલે અમને અમારું બાળક આપ્યું." },
  "First-time IVF patients": { hi: "पहली बार IVF मरीज़", gu: "પ્રથમ વખત IVF દર્દીઓ" },
  "Get a personalised baseline before your first cycle to set realistic expectations.": { hi: "यथार्थवादी अपेक्षाएं निर्धारित करने के लिए अपने पहले साइकल से पहले एक व्यक्तिगत आधार प्राप्त करें।", gu: "વાસ્તવિક અપેક્ષાઓ સેટ કરવા તમારા પ્રથમ સાયકલ પહેલાં વ્યક્તિગત બેઝલાઇન મેળવો." },
  "After previous IVF failure": { hi: "पिछली IVF विफलता के बाद", gu: "અગાઉની IVF નિષ્ફળતા પછી" },
  "Understand how your history and any new clinical factors affect your next cycle's odds.": { hi: "समझें कि आपका इतिहास और कोई नए क्लिनिकल कारक आपके अगले साइकल की संभावनाओं को कैसे प्रभावित करते हैं।", gu: "સમજો તમારો ઇતિહાસ અને કોઈ નવા ક્લિનિકલ પરિબળો તમારા આગામી સાયકલની શક્યતાઓને કેવી રીતે અસર કરે છે." },
  "Women over 35": { hi: "35 से अधिक उम्र की महिलाएं", gu: "35 થી વધુ ઉંમરની મહિલાઓ" },
  "See exactly how age impacts your probability and why acting sooner matters.": { hi: "ठीक-ठीक देखें कि उम्र आपकी संभावना को कैसे प्रभावित करती है और जल्दी कार्य करना क्यों महत्वपूर्ण है।", gu: "બરાબર જુઓ ઉંમર તમારી સંભાવનાને કેવી રીતે અસર કરે છે અને વહેલા પગલાં લેવા શા માટે મહત્વના છે." },
  "Considering donor eggs": { hi: "डोनर एग पर विचार कर रहे हैं", gu: "ડોનર એગ પર વિચાર કરી રહ્યા છો" },
  "Compare your own-egg probability against the donor egg baseline for informed decision-making.": { hi: "सूचित निर्णय लेने के लिए अपने स्वयं के एग की संभावना की तुलना डोनर एग आधार से करें।", gu: "માહિતગાર નિર્ણય લેવા તમારા પોતાના એગની સંભાવનાની ડોનર એગ બેઝલાઇન સાથે તુલના કરો." },
  "Understand your profile when no clear cause has been identified yet.": { hi: "समझें अपनी प्रोफ़ाइल जब अभी तक कोई स्पष्ट कारण की पहचान नहीं हुई हो।", gu: "તમારી પ્રોફાઇલ સમજો જ્યારે હજી સુધી કોઈ સ્પષ્ટ કારણ ઓળખાયું નથી." },
  "PCOS or Endometriosis": { hi: "PCOS या एंडोमेट्रियोसिस", gu: "PCOS અથવા એન્ડોમેટ્રિઓસિસ" },
  "See how your diagnosis specifically shifts your success rate and what can be optimised.": { hi: "देखें कि आपका निदान विशेष रूप से आपकी सफलता दर को कैसे बदलता है और क्या अनुकूलित किया जा सकता है।", gu: "જુઓ તમારું નિદાન ખાસ કરીને તમારો સફળતા દર કેવી રીતે બદલે છે અને શું ઓપ્ટિમાઇઝ કરી શકાય છે." },
  "Age-Based Baseline": { hi: "उम्र-आधारित बेसलाइन", gu: "ઉંમર-આધારિત બેઝલાઇન" },
  "Starts with your age group's published live-birth rate, adjusted for egg source.": { hi: "आपके आयु समूह की प्रकाशित लाइव-बर्थ दर से शुरू होता है, एग स्रोत के लिए समायोजित।", gu: "તમારા વય જૂથના પ્રકાશિત લાઇવ-બર્થ દરથી શરૂ થાય છે, એગ સ્રોત માટે એડજસ્ટ કરેલ." },
  "Clinical Modifiers": { hi: "क्लिनिकल संशोधक", gu: "ક્લિનિકલ મોડિફાયર્સ" },
  "Diagnosis, embryo quality, transfer type, and treatment history all shift the baseline.": { hi: "निदान, एम्ब्रियो गुणवत्ता, ट्रांसफर प्रकार, और उपचार इतिहास सभी बेसलाइन को बदलते हैं।", gu: "નિદાન, એમ્બ્રિયો ગુણવત્તા, ટ્રાન્સફર પ્રકાર, અને સારવાર ઇતિહાસ બધા બેઝલાઇનને બદલે છે." },
  "Cumulative Estimate": { hi: "संचयी अनुमान", gu: "સંચિત અંદાજ" },
  "Shows your 3-cycle cumulative probability using standard compounding statistics.": { hi: "मानक चक्रवृद्धि सांख्यिकी का उपयोग करके आपकी 3-साइकल संचयी संभावना दिखाता है।", gu: "માનક કમ્પાઉન્ડિંગ સ્ટેટિસ્ટિક્સનો ઉપયોગ કરીને તમારી 3-સાયકલ સંચિત સંભાવના બતાવે છે." },
  "Know Your Real Chances": { hi: "अपनी वास्तविक संभावनाएं जानें", gu: "તમારી વાસ્તવિક શક્યતાઓ જાણો" },
  "Get a specialist review of your IVF success estimate.": { hi: "अपने IVF सफलता अनुमान की विशेषज्ञ समीक्षा प्राप्त करें।", gu: "તમારો IVF સફળતા અંદાજની નિષ્ણાત સમીક્ષા મેળવો." },
  "Our fertility specialists review your full profile, including factors this calculator cannot assess, to give you a truly personalised plan.": { hi: "हमारे फर्टिलिटी विशेषज्ञ आपको वास्तव में व्यक्तिगत योजना देने के लिए आपकी पूरी प्रोफ़ाइल की समीक्षा करते हैं, जिसमें वे कारक शामिल हैं जिनका यह कैलकुलेटर आकलन नहीं कर सकता।", gu: "તમને ખરેખર વ્યક્તિગત યોજના આપવા અમારા ફર્ટિલિટી નિષ્ણાતો તમારી સંપૂર્ણ પ્રોફાઇલની સમીક્ષા કરે છે, જેમાં તે પરિબળોનો સમાવેશ થાય છે જેનું આ કેલ્ક્યુલેટર મૂલ્યાંકન કરી શકતું નથી." },

  // Ovulation & Pregnancy Calculator
  "Clinically Informed · Ovulation & Pregnancy Tools": { hi: "चिकित्सकीय रूप से सूचित · ओव्यूलेशन और प्रेगनेंसी टूल्स", gu: "તબીબી રીતે માહિતગાર · ઓવ્યુલેશન અને પ્રેગ્નન્સી ટૂલ્સ" },
  "Fertile window average": { hi: "औसत फर्टाइल विंडो", gu: "સરેરાશ ફર્ટાઇલ વિન્ડો" },
  "Egg survival after ovulation": { hi: "ओव्यूलेशन के बाद एग जीवित रहने की अवधि", gu: "ઓવ્યુલેશન પછી એગ જીવિત રહેવાનો સમય" },
  "Sperm can survive in body": { hi: "शरीर में स्पर्म जीवित रह सकता है", gu: "શરીરમાં સ્પર્મ જીવિત રહી શકે છે" },
  "Typical ovulation (28-day cycle)": { hi: "सामान्य ओव्यूलेशन (28-दिन साइकल)", gu: "સામાન્ય ઓવ્યુલેશન (28-દિવસ સાયકલ)" },
  "Based on well-established menstrual cycle science — quick, accurate, and private.": { hi: "सुस्थापित मासिक धर्म चक्र विज्ञान पर आधारित — तेज़, सटीक और निजी।", gu: "સુસ્થાપિત માસિક ચક્ર વિજ્ઞાન પર આધારિત — ઝડપી, ચોક્કસ અને ખાનગી." },
  "Enter Your Cycle Data": { hi: "अपना साइकल डेटा दर्ज करें", gu: "તમારો સાયકલ ડેટા દાખલ કરો" },
  "Input the first day of your last period and your average cycle length. Most women have cycles between 24–35 days.": { hi: "अपने अंतिम पीरियड का पहला दिन और अपनी औसत साइकल लंबाई दर्ज करें। अधिकतर महिलाओं की साइकल 24–35 दिनों के बीच होती है।", gu: "તમારા છેલ્લા પીરિયડનો પ્રથમ દિવસ અને તમારી સરેરાશ સાયકલ લંબાઈ દાખલ કરો. મોટાભાગની મહિલાઓની સાયકલ 24–35 દિવસ વચ્ચે હોય છે." },
  "We Calculate Ovulation": { hi: "हम ओव्यूलेशन की गणना करते हैं", gu: "અમે ઓવ્યુલેશન ગણીએ છીએ" },
  "Using the standard luteal phase formula (cycle length minus 14 days), we estimate your most likely ovulation date.": { hi: "मानक ल्यूटियल फेज फॉर्मूला (साइकल लंबाई माइनस 14 दिन) का उपयोग करके, हम आपकी सबसे संभावित ओव्यूलेशन तारीख का अनुमान लगाते हैं।", gu: "માનક લ્યુટિયલ ફેઝ ફોર્મ્યુલા (સાયકલ લંબાઈ માઇનસ 14 દિવસ) નો ઉપયોગ કરીને, અમે તમારી સૌથી સંભવિત ઓવ્યુલેશન તારીખનો અંદાજ લગાવીએ છીએ." },
  "Get Your Fertile Window": { hi: "अपनी फर्टाइल विंडो जानें", gu: "તમારી ફર્ટાઇલ વિન્ડો મેળવો" },
  "Your fertile window spans 5 days before ovulation to 1 day after — when sperm can survive and meet an egg.": { hi: "आपकी फर्टाइल विंडो ओव्यूलेशन से 5 दिन पहले से 1 दिन बाद तक फैली होती है — जब स्पर्म जीवित रह सकता है और एग से मिल सकता है।", gu: "તમારી ફર્ટાઇલ વિન્ડો ઓવ્યુલેશનના 5 દિવસ પહેલાંથી 1 દિવસ પછી સુધી ફેલાયેલી છે — જ્યારે સ્પર્મ જીવિત રહી શકે છે અને એગને મળી શકે છે." },
  "Plan Up to 6 Months": { hi: "6 महीने तक की योजना बनाएं", gu: "6 મહિના સુધીનું આયોજન કરો" },
  "See your ovulation dates and fertile windows for the next 6 cycles in one clear, printable table.": { hi: "एक स्पष्ट, प्रिंट करने योग्य टेबल में अगले 6 साइकलों के लिए अपनी ओव्यूलेशन तारीखें और फर्टाइल विंडो देखें।", gu: "એક સ્પષ્ટ, પ્રિન્ટ કરી શકાય તેવા ટેબલમાં આગામી 6 સાયકલ માટે તમારી ઓવ્યુલેશન તારીખો અને ફર્ટાઇલ વિન્ડો જુઓ." },
  "What Our Patients Tell Us": { hi: "हमारे मरीज़ क्या कहते हैं", gu: "અમારા દર્દીઓ શું કહે છે" },
  "I had been trying for over a year and always thought Day 14 was the magic day. The calculator showed me my cycle was 31 days — so I was missing my fertile window completely. That was the breakthrough.": { hi: "मैं एक साल से अधिक समय से कोशिश कर रही थी और हमेशा सोचती थी कि डे 14 जादुई दिन है। कैलकुलेटर ने मुझे दिखाया कि मेरी साइकल 31 दिनों की थी — इसलिए मैं अपनी फर्टाइल विंडो पूरी तरह से चूक रही थी। यही वह टर्निंग पॉइंट था।", gu: "હું એક વર્ષથી વધુ સમયથી પ્રયાસ કરી રહી હતી અને હંમેશા વિચારતી હતી કે ડે 14 જાદુઈ દિવસ છે. કેલ્ક્યુલેટરે મને બતાવ્યું કે મારી સાયકલ 31 દિવસની હતી — તેથી હું મારી ફર્ટાઇલ વિન્ડો સંપૂર્ણપણે ચૂકી રહી હતી. તે જ મારો ટર્નિંગ પોઇન્ટ હતો." },
  "I used it to figure out when to time intercourse after my IUI. Knowing I was in my fertile window gave us extra hope during that two-week wait. We got pregnant on our second IUI.": { hi: "मैंने इसका उपयोग अपनी IUI के बाद संभोग का समय तय करने के लिए किया। यह जानना कि मैं अपनी फर्टाइल विंडो में थी, उस दो-सप्ताह के इंतज़ार के दौरान हमें अतिरिक्त उम्मीद देता था। हम अपनी दूसरी IUI में गर्भवती हो गईं।", gu: "મેં તેનો ઉપયોગ મારી IUI પછી સંભોગનો સમય નક્કી કરવા માટે કર્યો. મારી ફર્ટાઇલ વિન્ડોમાં હોવાનું જાણવાથી તે બે-અઠવાડિયાની રાહ દરમિયાન અમને વધારાની આશા મળી. અમે અમારી બીજી IUI માં ગર્ભવતી થયા." },
  "My cycles are irregular — 26 days one month, 33 the next. Entering different lengths helped me understand how much my window was shifting. My doctor said tracking this was the first step to understanding my PCOS.": { hi: "मेरी साइकल अनियमित है — एक महीने 26 दिन, अगले महीने 33 दिन। अलग-अलग लंबाई दर्ज करने से मुझे यह समझने में मदद मिली कि मेरी विंडो कितनी बदल रही थी। मेरे डॉक्टर ने कहा कि इसे ट्रैक करना मेरे PCOS को समझने का पहला कदम था।", gu: "મારી સાયકલ અનિયમિત છે — એક મહિને 26 દિવસ, બીજા મહિને 33 દિવસ. જુદી-જુદી લંબાઈ દાખલ કરવાથી મને એ સમજવામાં મદદ મળી કે મારી વિન્ડો કેટલી બદલાઈ રહી હતી. મારા ડોક્ટરે કહ્યું કે આનો ટ્રેક રાખવો એ મારા PCOS ને સમજવાનું પ્રથમ પગલું હતું." },
  "The 6-cycle table was a game changer. My husband travels for work and we could actually plan around his schedule for the next few months. It felt like we finally had control over something.": { hi: "6-साइकल टेबल एक गेम चेंजर था। मेरे पति काम के लिए यात्रा करते हैं और हम वास्तव में अगले कुछ महीनों के लिए उनके शेड्यूल के आसपास योजना बना सके। ऐसा महसूस हुआ जैसे आखिरकार हमारा किसी चीज़ पर नियंत्रण था।", gu: "6-સાયકલ ટેબલ એક ગેમ ચેન્જર હતું. મારા પતિ કામ માટે મુસાફરી કરે છે અને અમે ખરેખર આગામી થોડા મહિનાઓ માટે તેમના શેડ્યૂલની આસપાસ આયોજન કરી શક્યા. એવું લાગ્યું કે આખરે અમારું કંઈક પર નિયંત્રણ હતું." },
  "Pregnancy Calculator": { hi: "प्रेगनेंसी कैलकुलेटर", gu: "પ્રેગ્નન્સી કેલ્ક્યુલેટર" },
  "First day of last period": { hi: "अंतिम पीरियड का पहला दिन", gu: "છેલ્લા પીરિયડનો પ્રથમ દિવસ" },
  "Cycle length (days)": { hi: "साइकल लंबाई (दिन)", gu: "સાયકલ લંબાઈ (દિવસ)" },
  "Calculate": { hi: "गणना करें", gu: "ગણો" },
  "Last Period": { hi: "अंतिम पीरियड", gu: "છેલ્લો પીરિયડ" },
  "Calculate due date from your last menstrual period.": { hi: "अपने अंतिम मासिक धर्म से देय तारीख की गणना करें।", gu: "તમારા છેલ્લા માસિક પરથી નિયત તારીખ ગણો." },
  "Due Date": { hi: "देय तारीख", gu: "નિયત તારીખ" },
  "Calculate your pregnancy progress from an estimated due date.": { hi: "अनुमानित देय तारीख से अपनी प्रेगनेंसी की प्रगति की गणना करें।", gu: "અંદાજિત નિયત તારીખ પરથી તમારી પ્રેગ્નન્સીની પ્રગતિ ગણો." },
  "Estimated due date": { hi: "अनुमानित देय तारीख", gu: "અંદાજિત નિયત તારીખ" },
  "Please enter the first day of your last menstrual period.": { hi: "कृपया अपने अंतिम मासिक धर्म का पहला दिन दर्ज करें।", gu: "કૃપા કરી તમારા છેલ્લા માસિકનો પ્રથમ દિવસ દાખલ કરો." },
  "Please enter a cycle length between 20 and 42 days.": { hi: "कृपया 20 से 42 दिनों के बीच साइकल लंबाई दर्ज करें।", gu: "કૃપા કરી 20 થી 42 દિવસ વચ્ચે સાયકલ લંબાઈ દાખલ કરો." },
  "Please enter your estimated due date.": { hi: "कृपया अपनी अनुमानित देय तारीख दर्ज करें।", gu: "કૃપા કરી તમારી અંદાજિત નિયત તારીખ દાખલ કરો." },
  "Ovulation Date": { hi: "ओव्यूलेशन तारीख", gu: "ઓવ્યુલેશન તારીખ" },
  "Fertile Window": { hi: "फर्टाइल विंडो", gu: "ફર્ટાઇલ વિન્ડો" },
  "Pregnancy Test Date": { hi: "प्रेगनेंसी टेस्ट तारीख", gu: "પ્રેગ્નન્સી ટેસ્ટ તારીખ" },
  "Next Period": { hi: "अगला पीरियड", gu: "આગામી પીરિયડ" },
  "Current Cycle Phase": { hi: "वर्तमान साइकल फेज", gu: "વર્તમાન સાયકલ ફેઝ" },
  "Day": { hi: "दिन", gu: "દિવસ" },
  "Period #": { hi: "पीरियड #", gu: "પીરિયડ #" },
  "Period Start": { hi: "पीरियड शुरू", gu: "પીરિયડ શરૂઆત" },
  "Test Date": { hi: "टेस्ट तारीख", gu: "ટેસ્ટ તારીખ" },
  "* The results of this calculator are estimations only. Please consult your doctor for personal advice.": { hi: "* इस कैलकुलेटर के परिणाम केवल अनुमान हैं। व्यक्तिगत सलाह के लिए कृपया अपने डॉक्टर से परामर्श करें।", gu: "* આ કેલ્ક્યુલેટરના પરિણામો ફક્ત અંદાજ છે. વ્યક્તિગત સલાહ માટે કૃપા કરી તમારા ડોક્ટરની સલાહ લો." },
  "Days until birth": { hi: "जन्म तक के दिन", gu: "જન્મ સુધીના દિવસો" },
  "Estimated due date is": { hi: "अनुमानित देय तारीख है", gu: "અંદાજિત નિયત તારીખ છે" },
  "This timeline helps you follow pregnancy progress safely.": { hi: "यह टाइमलाइन आपको सुरक्षित रूप से प्रेगनेंसी की प्रगति को फॉलो करने में मदद करती है।", gu: "આ ટાઇમલાઇન તમને સુરક્ષિત રીતે પ્રેગ્નન્સીની પ્રગતિ ફોલો કરવામાં મદદ કરે છે." },
  "Baby Size": { hi: "बच्चे का आकार", gu: "બાળકનું કદ" },
  "Trimester Progress": { hi: "ट्राइमेस्टर प्रगति", gu: "ટ્રાઇમેસ્ટર પ્રગતિ" },
  "Start Date": { hi: "आरंभ तारीख", gu: "શરૂઆતની તારીખ" },
  "Pregnancy Age": { hi: "प्रेगनेंसी आयु", gu: "પ્રેગ્નન્સી ઉંમર" },
  "{weeks} weeks {days} days": { hi: "{weeks} सप्ताह {days} दिन", gu: "{weeks} અઠવાડિયાં {days} દિવસ" },
  "{week} of 40": { hi: "{week} / 40", gu: "{week} / 40" },
  "Progress": { hi: "प्रगति", gu: "પ્રગતિ" },
  "Week": { hi: "सप्ताह", gu: "અઠવાડિયું" },
  "Trimester": { hi: "ट्राइमेस्टर", gu: "ટ્રાઇમેસ્ટર" },
  "Trimester {n}": { hi: "ट्राइमेस्टर {n}", gu: "ટ્રાઇમેસ્ટર {n}" },
  "Ready to feel confident?": { hi: "आत्मविश्वास महसूस करने के लिए तैयार हैं?", gu: "આત્મવિશ્વાસ અનુભવવા તૈયાર છો?" },
  "Get expert guidance after your ovulation and pregnancy estimates.": { hi: "अपने ओव्यूलेशन और प्रेगनेंसी अनुमानों के बाद विशेषज्ञ मार्गदर्शन प्राप्त करें।", gu: "તમારા ઓવ્યુલેશન અને પ્રેગ્નન્સી અંદાજો પછી નિષ્ણાત માર્ગદર્શન મેળવો." },
  "Book a consultation with our fertility specialists to validate your cycle tracking, confirm your due date, or plan the next step.": { hi: "अपनी साइकल ट्रैकिंग की पुष्टि करने, अपनी देय तारीख की पुष्टि करने, या अगला कदम तय करने के लिए हमारे फर्टिलिटी विशेषज्ञों के साथ कंसल्टेशन बुक करें।", gu: "તમારી સાયકલ ટ્રેકિંગ ચકાસવા, તમારી નિયત તારીખની પુષ્ટિ કરવા, અથવા આગામી પગલું આયોજિત કરવા અમારા ફર્ટિલિટી નિષ્ણાતો સાથે કન્સલ્ટેશન બુક કરો." },
  "Just started trying to conceive": { hi: "गर्भधारण की कोशिश अभी शुरू की है", gu: "ગર્ભધારણનો પ્રયાસ હમણાં જ શરૂ કર્યો છે" },
  "Learn when your fertile window actually falls — most couples are surprised by the timing.": { hi: "जानें कि आपकी फर्टाइल विंडो वास्तव में कब आती है — अधिकतर जोड़े समय को लेकर हैरान होते हैं।", gu: "જાણો તમારી ફર્ટાઇલ વિન્ડો ખરેખર ક્યારે આવે છે — મોટાભાગના યુગલો સમય જોઈને આશ્ચર્યચકિત થાય છે." },
  "Irregular cycle trackers": { hi: "अनियमित साइकल ट्रैक करने वाले", gu: "અનિયમિત સાયકલ ટ્રેક કરનારા" },
  "Adjust cycle length each month to see how your fertile window shifts with irregular cycles.": { hi: "यह देखने के लिए हर महीने साइकल लंबाई समायोजित करें कि अनियमित साइकल के साथ आपकी फर्टाइल विंडो कैसे बदलती है।", gu: "અનિયમિત સાયકલ સાથે તમારી ફર્ટાઇલ વિન્ડો કેવી રીતે બદલાય છે તે જોવા દર મહિને સાયકલ લંબાઈ એડજસ્ટ કરો." },
  "Timing IUI or natural cycles": { hi: "IUI या नेचुरल साइकल का समय तय करना", gu: "IUI અથવા નેચરલ સાયકલનો સમય નક્કી કરવો" },
  "Use the ovulation date estimate to plan intercourse or IUI timing with greater precision.": { hi: "अधिक सटीकता के साथ संभोग या IUI का समय तय करने के लिए ओव्यूलेशन तारीख के अनुमान का उपयोग करें।", gu: "વધુ ચોકસાઈ સાથે સંભોગ અથવા IUI નો સમય નક્કી કરવા ઓવ્યુલેશન તારીખના અંદાજનો ઉપયોગ કરો." },
  "Planning around travel or schedules": { hi: "यात्रा या शेड्यूल के आसपास योजना बनाना", gu: "મુસાફરી અથવા શેડ્યૂલની આસપાસ આયોજન કરવું" },
  "The 6-month calendar helps you and your partner plan ahead when time apart is a factor.": { hi: "6-महीने का कैलेंडर आपको और आपके पार्टनर को आगे की योजना बनाने में मदद करता है जब अलग समय एक कारक हो।", gu: "6-મહિનાનું કેલેન્ડર તમને અને તમારા પાર્ટનરને આગળનું આયોજન કરવામાં મદદ કરે છે જ્યારે અલગ સમય એક પરિબળ હોય." },
  "Already pregnant": { hi: "पहले से गर्भवती", gu: "પહેલેથી ગર્ભવતી" },
  "Switch to pregnancy mode to track your due date, trimester progress, and baby size week by week.": { hi: "अपनी देय तारीख, ट्राइमेस्टर प्रगति, और बच्चे के आकार को सप्ताह दर सप्ताह ट्रैक करने के लिए प्रेगनेंसी मोड पर स्विच करें।", gu: "તમારી નિયત તારીખ, ટ્રાઇમેસ્ટર પ્રગતિ, અને બાળકના કદને અઠવાડિયા-દર-અઠવાડિયું ટ્રેક કરવા પ્રેગ્નન્સી મોડ પર સ્વિચ કરો." },
  "Understanding your cycle": { hi: "अपनी साइकल को समझना", gu: "તમારી સાયકલ સમજવી" },
  "Not ready to try yet? Use the tool to understand your natural rhythm before you start.": { hi: "अभी कोशिश करने के लिए तैयार नहीं हैं? शुरू करने से पहले अपनी प्राकृतिक लय को समझने के लिए इस टूल का उपयोग करें।", gu: "હજી પ્રયાસ કરવા તૈયાર નથી? શરૂ કરતા પહેલા તમારી કુદરતી લય સમજવા આ ટૂલનો ઉપયોગ કરો." },
  "About This Tool": { hi: "इस टूल के बारे में", gu: "આ ટૂલ વિશે" },
  "Find Your Fertile Window": { hi: "अपनी फर्टाइल विंडो खोजें", gu: "તમારી ફર્ટાઇલ વિન્ડો શોધો" },
  "Discover the best days for conception based on your cycle length.": { hi: "अपनी साइकल लंबाई के आधार पर गर्भधारण के लिए सर्वोत्तम दिन खोजें।", gu: "તમારી સાયકલ લંબાઈના આધારે ગર્ભધારણ માટે શ્રેષ્ઠ દિવસો શોધો." },
  "Estimate Your Due Date": { hi: "अपनी देय तारीख का अनुमान लगाएं", gu: "તમારી નિયત તારીખનો અંદાજ લગાવો" },
  "Track pregnancy progress with weeks, trimester milestones and baby size data.": { hi: "सप्ताह, ट्राइमेस्टर माइलस्टोन और बच्चे के आकार के डेटा के साथ प्रेगनेंसी की प्रगति को ट्रैक करें।", gu: "અઠવાડિયા, ટ્રાઇમેસ્ટર માઇલસ્ટોન અને બાળકના કદના ડેટા સાથે પ્રેગ્નન્સીની પ્રગતિ ટ્રેક કરો." },
  "Plan Your Next Steps": { hi: "अपने अगले कदम की योजना बनाएं", gu: "તમારા આગામી પગલાંનું આયોજન કરો" },
  "Use the estimates to time tests and appointments with more confidence.": { hi: "अधिक आत्मविश्वास के साथ टेस्ट और अपॉइंटमेंट का समय तय करने के लिए अनुमानों का उपयोग करें।", gu: "વધુ આત્મવિશ્વાસ સાથે ટેસ્ટ અને એપોઇન્ટમેન્ટનો સમય નક્કી કરવા અંદાજોનો ઉપયોગ કરો." },

  // Ovulation calculator — cycle phases
  "Menstruation": { hi: "माहवारी", gu: "માસિક" },
  "Ovulation": { hi: "ओव्यूलेशन", gu: "ઓવ્યુલેશન" },
  "Luteal Phase": { hi: "ल्यूटियल फेज", gu: "લ્યુટિયલ ફેઝ" },
  "Low probability of getting pregnant": { hi: "गर्भवती होने की संभावना कम है", gu: "ગર્ભવતી થવાની શક્યતા ઓછી છે" },
  "There is a chance of getting pregnant": { hi: "गर्भवती होने की संभावना है", gu: "ગર્ભવતી થવાની શક્યતા છે" },
  "High probability of getting pregnant": { hi: "गर्भवती होने की संभावना अधिक है", gu: "ગર્ભવતી થવાની શક્યતા વધારે છે" },

  // Ovulation calculator — baby-size names (BABY_SIZES)
  "Early Development": { hi: "प्रारंभिक विकास", gu: "પ્રારંભિક વિકાસ" },
  "Cell Division": { hi: "कोशिका विभाजन", gu: "કોષ વિભાજન" },
  "Implantation": { hi: "प्रत्यारोपण", gu: "ઇમ્પ્લાન્ટેશન" },
  "Poppy Seed": { hi: "खसखस का बीज", gu: "ખસખસનું બીજ" },
  "Sesame Seed": { hi: "तिल का बीज", gu: "તલનું બીજ" },
  "Sweet Pea": { hi: "स्वीट पी", gu: "સ્વીટ પી" },
  "Blueberry": { hi: "ब्लूबेरी", gu: "બ્લૂબેરી" },
  "Raspberry": { hi: "रास्पबेरी", gu: "રાસ્પબેરી" },
  "Grape": { hi: "अंगूर", gu: "દ્રાક્ષ" },
  "Prune": { hi: "सूखा आलूबुखारा", gu: "સૂકું આલુ" },
  "Fig": { hi: "अंजीर", gu: "અંજીર" },
  "Lime": { hi: "नींबू (लाइम)", gu: "લીંબુ (લાઇમ)" },
  "Peach": { hi: "आड़ू", gu: "પીચ" },
  "Lemon": { hi: "नींबू", gu: "લીંબુ" },
  "Orange": { hi: "संतरा", gu: "નારંગી" },
  "Avocado": { hi: "एवोकाडो", gu: "એવોકાડો" },
  "Grapefruit": { hi: "चकोतरा", gu: "ગ્રેપફ્રૂટ" },
  "Bell Pepper": { hi: "शिमला मिर्च", gu: "કેપ્સિકમ" },
  "Mango": { hi: "आम", gu: "કેરી" },
  "Banana": { hi: "केला", gu: "કેળું" },
  "Corn": { hi: "मकई (भुट्टा)", gu: "મકાઈ" },
  "Papaya": { hi: "पपीता", gu: "પપૈયું" },
  "Daikon": { hi: "मूली (डाइकॉन)", gu: "મૂળા (ડાઇકોન)" },
  "Cauliflower": { hi: "फूलगोभी", gu: "ફૂલકોબી" },
  "Scallion": { hi: "हरा प्याज", gu: "લીલી ડુંગળી" },
  "Jicama": { hi: "जिकामा", gu: "જિકામા" },
  "Rutabaga": { hi: "रूटाबागा (शलजम)", gu: "રુટાબાગા (સલગમ)" },
  "Eggplant": { hi: "बैंगन", gu: "રીંગણ" },
  "Butternut Squash": { hi: "बटरनट स्क्वैश", gu: "બટરનટ સ્ક્વોશ" },
  "Acorn Squash": { hi: "एकॉर्न स्क्वैश", gu: "એકોર્ન સ્ક્વોશ" },
  "Coconut": { hi: "नारियल", gu: "નાળિયેર" },
  "Rhubarb": { hi: "रूबर्ब", gu: "રુબાર્બ" },
  "Pineapple": { hi: "अनानास", gu: "અનાનસ" },
  "Cantaloupe": { hi: "खरबूजा", gu: "તરબૂચ (કેન્ટલૂપ)" },
  "Honeydew Melon": { hi: "हनीड्यू खरबूजा", gu: "હનીડ્યુ તડબૂચ" },
  "Romaine Lettuce": { hi: "रोमेन लेट्यूस (सलाद पत्ता)", gu: "રોમેન લેટ્યુસ" },
  "Winter Melon": { hi: "पेठा (विंटर मेलन)", gu: "કોળું (વિન્ટર મેલન)" },
  "Pumpkin": { hi: "कद्दू", gu: "કોળું" },
  "Watermelon": { hi: "तरबूज", gu: "તડબૂચ" },
  "Jackfruit": { hi: "कटहल", gu: "ફણસ" },

  // Ovulation calculator — baby-size descriptions (BABY_SIZES, week 1-42)
  "Early development stage. Your body prepares for ovulation.": { hi: "प्रारंभिक विकास चरण। आपका शरीर ओव्यूलेशन के लिए तैयार होता है।", gu: "પ્રારંભિક વિકાસ તબક્કો. તમારું શરીર ઓવ્યુલેશન માટે તૈયાર થાય છે." },
  "Rapid cell division occurring. This is when fertilization may happen.": { hi: "तेज़ी से कोशिका विभाजन हो रहा है। यह वह समय है जब निषेचन हो सकता है।", gu: "ઝડપી કોષ વિભાજન થઈ રહ્યું છે. આ સમય છે જ્યારે ફલિનીકરણ થઈ શકે છે." },
  "Embryo attaches to uterine lining. Pregnancy hormones begin production. Embryo size: 0.1mm": { hi: "एम्ब्रियो गर्भाशय की परत से जुड़ता है। गर्भावस्था हार्मोन का उत्पादन शुरू होता है। एम्ब्रियो का आकार: 0.1mm", gu: "એમ્બ્રિયો ગર્ભાશયની અસ્તર સાથે જોડાય છે. ગર્ભાવસ્થા હોર્મોનનું ઉત્પાદન શરૂ થાય છે. એમ્બ્રિયોનું કદ: 0.1mm" },
  "Pregnancy tests can now detect hCG hormone. Embryo size: 0.2mm": { hi: "अब प्रेगनेंसी टेस्ट hCG हार्मोन का पता लगा सकते हैं। एम्ब्रियो का आकार: 0.2mm", gu: "હવે પ્રેગ્નન્સી ટેસ્ટ hCG હોર્મોન શોધી શકે છે. એમ્બ્રિયોનું કદ: 0.2mm" },
  "Embryo size: 1.5mm. Neural tube forming, which becomes brain and spinal cord": { hi: "एम्ब्रियो का आकार: 1.5mm। न्यूरल ट्यूब बन रही है, जो मस्तिष्क और रीढ़ की हड्डी बनेगी", gu: "એમ્બ્રિયોનું કદ: 1.5mm. ન્યુરલ ટ્યુબ બની રહી છે, જે મગજ અને કરોડરજ્જુ બનશે" },
  "Your embryo is approximately 6mm long and starting to develop facial features": { hi: "आपका एम्ब्रियो लगभग 6mm लंबा है और चेहरे की विशेषताएं विकसित होने लगी हैं", gu: "તમારું એમ્બ્રિયો લગભગ 6mm લાંબું છે અને ચહેરાની વિશેષતાઓ વિકસવા લાગી છે" },
  "Your baby is around 13mm long and developing arm and leg buds": { hi: "आपका बच्चा लगभग 13mm लंबा है और भुजाओं और पैरों की कलियाँ विकसित हो रही हैं", gu: "તમારું બાળક લગભગ 13mm લાંબું છે અને હાથ અને પગની કળીઓ વિકસી રહી છે" },
  "Your baby measures about 16mm long and all essential organs are beginning to form": { hi: "आपके बच्चे की लंबाई लगभग 16mm है और सभी आवश्यक अंग बनना शुरू हो रहे हैं", gu: "તમારા બાળકની લંબાઈ લગભગ 16mm છે અને બધા જરૂરી અંગો બનવાનું શરૂ થઈ રહ્યા છે" },
  "Your baby is approximately 23mm long and now officially called a fetus": { hi: "आपका बच्चा लगभग 23mm लंबा है और अब आधिकारिक रूप से भ्रूण (फीटस) कहलाता है", gu: "તમારું બાળક લગભગ 23mm લાંબું છે અને હવે સત્તાવાર રીતે ફીટસ કહેવાય છે" },
  "Your baby measures about 31mm from crown to rump and is developing more defined features": { hi: "आपके बच्चे की क्राउन-रम्प लंबाई लगभग 31mm है और चेहरे की विशेषताएं अधिक स्पष्ट हो रही हैं", gu: "તમારા બાળકની ક્રાઉન-રમ્પ લંબાઈ લગભગ 31mm છે અને લક્ષણો વધુ સ્પષ્ટ થઈ રહ્યા છે" },
  "Your baby is approximately 41mm long and starting to move around actively": { hi: "आपका बच्चा लगभग 41mm लंबा है और सक्रिय रूप से हिलना-डुलना शुरू कर रहा है", gu: "તમારું બાળક લગભગ 41mm લાંબું છે અને સક્રિય રીતે હલનચલન શરૂ કરી રહ્યું છે" },
  "Your baby measures about 5.4cm long and is fully formed with all organs in place": { hi: "आपके बच्चे की लंबाई लगभग 5.4cm है और सभी अंगों के साथ पूरी तरह से बन चुका है", gu: "તમારા બાળકની લંબાઈ લગભગ 5.4cm છે અને બધા અંગો સાથે સંપૂર્ણ રીતે બની ચૂક્યું છે" },
  "Your baby is approximately 7.4cm long and has unique fingerprints forming": { hi: "आपका बच्चा लगभग 7.4cm लंबा है और उसकी अनोखी उंगलियों के निशान बन रहे हैं", gu: "તમારું બાળક લગભગ 7.4cm લાંબું છે અને તેની અનોખી આંગળીની છાપ બની રહી છે" },
  "Your baby measures about 8.7cm long and can now make facial expressions": { hi: "आपके बच्चे की लंबाई लगभग 8.7cm है और अब वह चेहरे के भाव बना सकता है", gu: "તમારા બાળકની લંબાઈ લગભગ 8.7cm છે અને હવે તે ચહેરાના હાવભાવ કરી શકે છે" },
  "Your baby is approximately 10.1cm long and can sense light through closed eyelids": { hi: "आपका बच्चा लगभग 10.1cm लंबा है और बंद पलकों के माध्यम से रोशनी महसूस कर सकता है", gu: "તમારું બાળક લગભગ 10.1cm લાંબું છે અને બંધ પોપચાં દ્વારા પ્રકાશ અનુભવી શકે છે" },
  "Your baby measures about 11.6cm long and weighs approximately 100 grams": { hi: "आपके बच्चे की लंबाई लगभग 11.6cm है और वज़न लगभग 100 ग्राम है", gu: "તમારા બાળકની લંબાઈ લગભગ 11.6cm છે અને વજન લગભગ 100 ગ્રામ છે" },
  "Your baby is approximately 13cm long and developing adipose (fat) tissue": { hi: "आपका बच्चा लगभग 13cm लंबा है और वसा (फैट) ऊतक विकसित हो रहा है", gu: "તમારું બાળક લગભગ 13cm લાંબું છે અને ચરબીયુક્ત (ફેટ) પેશી વિકસી રહી છે" },
  "Your baby measures about 14.2cm long and weighs around 190 grams": { hi: "आपके बच्चे की लंबाई लगभग 14.2cm है और वज़न लगभग 190 ग्राम है", gu: "તમારા બાળકની લંબાઈ લગભગ 14.2cm છે અને વજન લગભગ 190 ગ્રામ છે" },
  "Your baby is approximately 15.3cm long and developing a protective coating called vernix": { hi: "आपका बच्चा लगभग 15.3cm लंबा है और वर्निक्स नामक एक सुरक्षात्मक परत विकसित हो रही है", gu: "તમારું બાળક લગભગ 15.3cm લાંબું છે અને વર્નિક્સ નામનું રક્ષણાત્મક પડ વિકસી રહ્યું છે" },
  "Your baby measures about 16.4cm long and weighs around 300 grams": { hi: "आपके बच्चे की लंबाई लगभग 16.4cm है और वज़न लगभग 300 ग्राम है", gu: "તમારા બાળકની લંબાઈ લગભગ 16.4cm છે અને વજન લગભગ 300 ગ્રામ છે" },
  "Your baby is approximately 26.7cm long (head to heel) and can now swallow": { hi: "आपका बच्चा (सिर से एड़ी तक) लगभग 26.7cm लंबा है और अब निगल सकता है", gu: "તમારું બાળક (માથાથી પગ સુધી) લગભગ 26.7cm લાંબું છે અને હવે ગળી શકે છે" },
  "Your baby measures about 27.8cm long and weighs around 430 grams": { hi: "आपके बच्चे की लंबाई लगभग 27.8cm है और वज़न लगभग 430 ग्राम है", gu: "તમારા બાળકની લંબાઈ લગભગ 27.8cm છે અને વજન લગભગ 430 ગ્રામ છે" },
  "Your baby is approximately 28.9cm long and developing rapid eye movements": { hi: "आपका बच्चा लगभग 28.9cm लंबा है और उसमें तेज़ आँखों की गति (REM) विकसित हो रही है", gu: "તમારું બાળક લગભગ 28.9cm લાંબું છે અને તેમાં ઝડપી આંખની હલનચલન (REM) વિકસી રહી છે" },
  "Your baby measures about 30cm long and weighs around 600 grams": { hi: "आपके बच्चे की लंबाई लगभग 30cm है और वज़न लगभग 600 ग्राम है", gu: "તમારા બાળકની લંબાઈ લગભગ 30cm છે અને વજન લગભગ 600 ગ્રામ છે" },
  "Your baby is approximately 34.6cm long and weighs about 660 grams": { hi: "आपका बच्चा लगभग 34.6cm लंबा है और वज़न लगभग 660 ग्राम है", gu: "તમારું બાળક લગભગ 34.6cm લાંબું છે અને વજન લગભગ 660 ગ્રામ છે" },
  "Your baby measures about 35.6cm long and weighs around 760 grams": { hi: "आपके बच्चे की लंबाई लगभग 35.6cm है और वज़न लगभग 760 ग्राम है", gu: "તમારા બાળકની લંબાઈ લગભગ 35.6cm છે અને વજન લગભગ 760 ગ્રામ છે" },
  "Your baby is approximately 36.6cm long and weighs around 875 grams": { hi: "आपका बच्चा लगभग 36.6cm लंबा है और वज़न लगभग 875 ग्राम है", gu: "તમારું બાળક લગભગ 36.6cm લાંબું છે અને વજન લગભગ 875 ગ્રામ છે" },
  "Your baby measures about 37.6cm long and weighs around 1kg": { hi: "आपके बच्चे की लंबाई लगभग 37.6cm है और वज़न लगभग 1kg है", gu: "તમારા બાળકની લંબાઈ લગભગ 37.6cm છે અને વજન લગભગ 1kg છે" },
  "Your baby is approximately 38.6cm long and weighs about 1.15kg": { hi: "आपका बच्चा लगभग 38.6cm लंबा है और वज़न लगभग 1.15kg है", gu: "તમારું બાળક લગભગ 38.6cm લાંબું છે અને વજન લગભગ 1.15kg છે" },
  "Your baby measures about 39.9cm long and weighs around 1.3kg": { hi: "आपके बच्चे की लंबाई लगभग 39.9cm है और वज़न लगभग 1.3kg है", gu: "તમારા બાળકની લંબાઈ લગભગ 39.9cm છે અને વજન લગભગ 1.3kg છે" },
  "Your baby is approximately 41.1cm long and weighs about 1.5kg": { hi: "आपका बच्चा लगभग 41.1cm लंबा है और वज़न लगभग 1.5kg है", gu: "તમારું બાળક લગભગ 41.1cm લાંબું છે અને વજન લગભગ 1.5kg છે" },
  "Your baby measures about 42.4cm long and weighs around 1.7kg": { hi: "आपके बच्चे की लंबाई लगभग 42.4cm है और वज़न लगभग 1.7kg है", gu: "તમારા બાળકની લંબાઈ લગભગ 42.4cm છે અને વજન લગભગ 1.7kg છે" },
  "Your baby is approximately 43.7cm long and weighs about 1.9kg": { hi: "आपका बच्चा लगभग 43.7cm लंबा है और वज़न लगभग 1.9kg है", gu: "તમારું બાળક લગભગ 43.7cm લાંબું છે અને વજન લગભગ 1.9kg છે" },
  "Your baby measures about 45cm long and weighs about 2.1kg": { hi: "आपके बच्चे की लंबाई लगभग 45cm है और वज़न लगभग 2.1kg है", gu: "તમારા બાળકની લંબાઈ લગભગ 45cm છે અને વજન લગભગ 2.1kg છે" },
  "Your baby is approximately 46.2cm long and weighs about 2.4kg": { hi: "आपका बच्चा लगभग 46.2cm लंबा है और वज़न लगभग 2.4kg है", gu: "તમારું બાળક લગભગ 46.2cm લાંબું છે અને વજન લગભગ 2.4kg છે" },
  "Your baby measures about 47.4cm long and weighs around 2.6kg": { hi: "आपके बच्चे की लंबाई लगभग 47.4cm है और वज़न लगभग 2.6kg है", gu: "તમારા બાળકની લંબાઈ લગભગ 47.4cm છે અને વજન લગભગ 2.6kg છે" },
  "Your baby is approximately 48.6cm long and weighs about 2.9kg. Now considered full term!": { hi: "आपका बच्चा लगभग 48.6cm लंबा है और वज़न लगभग 2.9kg है। अब इसे फुल-टर्म माना जाता है!", gu: "તમારું બાળક લગભગ 48.6cm લાંબું છે અને વજન લગભગ 2.9kg છે. હવે તેને ફુલ-ટર્મ ગણવામાં આવે છે!" },
  "Your baby measures about 49.8cm long and weighs around 3.1kg": { hi: "आपके बच्चे की लंबाई लगभग 49.8cm है और वज़न लगभग 3.1kg है", gu: "તમારા બાળકની લંબાઈ લગભગ 49.8cm છે અને વજન લગભગ 3.1kg છે" },
  "Your baby is approximately 50.7cm long and weighs about 3.3kg": { hi: "आपका बच्चा लगभग 50.7cm लंबा है और वज़न लगभग 3.3kg है", gu: "તમારું બાળક લગભગ 50.7cm લાંબું છે અને વજન લગભગ 3.3kg છે" },
  "Your baby measures about 51.2cm long and weighs around 3.4kg. Ready to meet the world!": { hi: "आपके बच्चे की लंबाई लगभग 51.2cm है और वज़न लगभग 3.4kg है। दुनिया से मिलने के लिए तैयार!", gu: "તમારા બાળકની લંબાઈ લગભગ 51.2cm છે અને વજન લગભગ 3.4kg છે. દુનિયાને મળવા તૈયાર!" },
  "Your baby is approximately 51.7cm long and weighs about 3.6kg. Fully developed and ready for birth": { hi: "आपका बच्चा लगभग 51.7cm लंबा है और वज़न लगभग 3.6kg है। पूरी तरह विकसित और जन्म के लिए तैयार", gu: "તમારું બાળક લગભગ 51.7cm લાંબું છે અને વજન લગભગ 3.6kg છે. સંપૂર્ણ રીતે વિકસિત અને જન્મ માટે તૈયાર" },
  "Your baby measures about 52.3cm long and weighs about 3.7kg. You are now post-term": { hi: "आपके बच्चे की लंबाई लगभग 52.3cm है और वज़न लगभग 3.7kg है। अब आप पोस्ट-टर्म हैं", gu: "તમારા બાળકની લંબાઈ લગભગ 52.3cm છે અને વજન લગભગ 3.7kg છે. હવે તમે પોસ્ટ-ટર્મ છો" },
};

export function ui(key: string, locale: Locale): string {
  return locale === "en" ? key : UI_STRINGS[key]?.[locale] ?? key;
}
