import type { Locale } from "@/lib/i18n";

/** Hardcoded UI chrome strings (not CMS content). English is the key + fallback.
 *  hi/gu are AI-written — flag for review before go-live. */
export const UI_STRINGS: Record<string, { hi: string; gu: string }> = {
  "Learn more": { hi: "और जानें", gu: "વધુ જાણો" },
  "Patient Story": { hi: "मरीज़ की कहानी", gu: "દર્દીની વાર્તા" },
  "Use Calculator": { hi: "कैलकुलेटर उपयोग करें", gu: "કેલ્ક્યુલેટર વાપરો" },
  "View Centre": { hi: "सेंटर देखें", gu: "સેન્ટર જુઓ" },
  "View all awards & achievements": { hi: "सभी पुरस्कार और उपलब्धियाँ देखें", gu: "બધા એવોર્ડ અને સિદ્ધિઓ જુઓ" },
  "View More Events": { hi: "और कार्यक्रम देखें", gu: "વધુ કાર્યક્રમો જુઓ" },
  "Patient review": { hi: "मरीज़ की समीक्षा", gu: "દર્દીની સમીક્ષા" },
  "Google review": { hi: "Google समीक्षा", gu: "Google સમીક્ષા" },
  "* Terms and conditions apply.": { hi: "* नियम एवं शर्तें लागू।", gu: "* નિયમો અને શરતો લાગુ." },
  "Full Name *": { hi: "पूरा नाम *", gu: "પૂરું નામ *" },
  "Phone *": { hi: "फ़ोन *", gu: "ફોન *" },
  "Email": { hi: "ईमेल", gu: "ઇમેઇલ" },
  "Treatment of Interest": { hi: "रुचि का उपचार", gu: "રસની સારવાર" },
  "Preferred Centre": { hi: "पसंदीदा सेंटर", gu: "પસંદગીનું સેન્ટર" },
  "Message": { hi: "संदेश", gu: "સંદેશ" },
  "Sending…": { hi: "भेजा जा रहा है…", gu: "મોકલી રહ્યા છીએ…" },
  "Request a Callback": { hi: "कॉलबैक का अनुरोध करें", gu: "કૉલબેકની વિનંતી કરો" },
  "India's Trusted Fertility Experts · Since 1998": { hi: "भारत के विश्वसनीय फर्टिलिटी विशेषज्ञ · 1998 से", gu: "ભારતના વિશ્વસનીય ફર્ટિલિટી નિષ્ણાતો · 1998 થી" },
  "WhatsApp": { hi: "व्हाट्सऐप", gu: "વોટ્સએપ" },
  "24×7 Care": { hi: "24×7 देखभाल", gu: "24×7 સંભાળ" },
  "Book Consultation": { hi: "कंसल्टेशन बुक करें", gu: "કન્સલ્ટેશન બુક કરો" },
  "Check IVF Eligibility": { hi: "IVF पात्रता जांचें", gu: "IVF પાત્રતા ચકાસો" },
  "WhatsApp Now": { hi: "व्हाट्सऐप करें", gu: "વોટ્સએપ કરો" },
  "Call Now": { hi: "अभी कॉल करें", gu: "હમણાં કૉલ કરો" },

  // Contact page chrome
  "Home": { hi: "होम", gu: "હોમ" },
  "Contact Us": { hi: "संपर्क करें", gu: "અમારો સંપર્ક કરો" },
  "Call Us": { hi: "कॉल करें", gu: "કૉલ કરો" },
  "Chat with our team": { hi: "हमारी टीम से चैट करें", gu: "અમારી ટીમ સાથે ચેટ કરો" },
  "24×7 phone support — clinic visiting hours vary by centre": { hi: "24×7 फोन सपोर्ट — क्लिनिक विज़िटिंग आवर्स सेंटर के अनुसार अलग-अलग हैं", gu: "24×7 ફોન સપોર્ટ — ક્લિનિક વિઝિટિંગ અવર્સ સેન્ટર પ્રમાણે અલગ-અલગ છે" },
  "Quick replies, every day": { hi: "हर दिन त्वरित जवाब", gu: "દરરોજ ઝડપી જવાબ" },
  "We reply within 24 hours": { hi: "हम 24 घंटों के भीतर जवाब देते हैं", gu: "અમે 24 કલાકમાં જવાબ આપીએ છીએ" },
  "Our Network": { hi: "हमारा नेटवर्क", gu: "અમારું નેટવર્ક" },
  "Find a Bavishi Fertility Institute": { hi: "Bavishi Fertility Institute खोजें", gu: "Bavishi Fertility Institute શોધો" },
  "near you": { hi: "आपके पास", gu: "તમારી નજીક" },
  "14 fertility centres across 8 Indian cities — world-class care, close to home. Phone & WhatsApp support is available 24×7; centre visiting hours are listed below.": { hi: "8 भारतीय शहरों में 14 फर्टिलिटी सेंटर — विश्वस्तरीय देखभाल, घर के पास। फोन और व्हाट्सऐप सपोर्ट 24×7 उपलब्ध है; सेंटर के विज़िटिंग आवर्स नीचे दिए गए हैं।", gu: "8 ભારતીય શહેરોમાં 14 ફર્ટિલિટી સેન્ટર — વિશ્વસ્તરીય સંભાળ, ઘરની નજીક. ફોન અને વોટ્સએપ સપોર્ટ 24×7 ઉપલબ્ધ છે; સેન્ટરના વિઝિટિંગ અવર્સ નીચે આપેલા છે." },
  "Call": { hi: "कॉल", gu: "કૉલ" },
  "Directions": { hi: "दिशा-निर्देश", gu: "દિશા-નિર્દેશો" },
  "Need help choosing the right centre?": { hi: "सही सेंटर चुनने में मदद चाहिए?", gu: "યોગ્ય સેન્ટર પસંદ કરવામાં મદદ જોઈએ છે?" },
  "Our counsellors will guide you to the Bavishi Fertility Institute centre nearest you.": { hi: "हमारे काउंसलर आपको आपके नज़दीकी Bavishi Fertility Institute सेंटर तक मार्गदर्शन देंगे।", gu: "અમારા કાઉન્સેલર્સ તમને તમારા નજીકના Bavishi Fertility Institute સેન્ટર સુધી માર્ગદર્શન આપશે." },
  "FAQ": { hi: "सामान्य प्रश्न", gu: "વારંવાર પુછાતા પ્રશ્નો" },
  "Getting in touch —": { hi: "संपर्क करना —", gu: "સંપર્ક કરવો —" },
  "answered": { hi: "आसान बनाया गया", gu: "સરળ બનાવ્યું" },
  "Your journey to parenthood starts with": { hi: "पेरेंटहुड की आपकी यात्रा शुरू होती है", gu: "પેરેન્ટહુડની તમારી યાત્રા શરૂ થાય છે" },
  "one message.": { hi: "एक संदेश से।", gu: "એક સંદેશથી." },
  "WhatsApp Us": { hi: "व्हाट्सऐप करें", gu: "વોટ્સએપ કરો" },

  // Contact page hero + FAQ content (fallback copy — used when CMS has no hi/gu override)
  "We're here for you": { hi: "हम आपके लिए यहाँ हैं", gu: "અમે તમારા માટે અહીં છીએ" },
  "Contact": { hi: "संपर्क करें", gu: "સંપર્ક કરો" },
  "Have a question or ready to begin? Reach out — confidentially and without obligation. Our fertility counsellors are here to guide your very first step.": { hi: "कोई सवाल है या शुरुआत करने के लिए तैयार हैं? गोपनीय रूप से और बिना किसी दायित्व के संपर्क करें — हमारे फर्टिलिटी काउंसलर आपके पहले कदम में मार्गदर्शन के लिए यहाँ हैं।", gu: "કોઈ પ્રશ્ન છે અથવા શરૂઆત કરવા તૈયાર છો? ગોપનીય રીતે અને કોઈપણ જવાબદારી વિના સંપર્ક કરો — અમારા ફર્ટિલિટી કાઉન્સેલર્સ તમારા પ્રથમ પગલામાં માર્ગદર્શન આપવા માટે અહીં છે." },
  "How do I book an appointment at Bavishi Fertility Institute?": { hi: "मैं Bavishi Fertility Institute में अपॉइंटमेंट कैसे बुक करूं?", gu: "હું Bavishi Fertility Institute માં એપોઇન્ટમેન્ટ કેવી રીતે બુક કરું?" },
  "Fill in the enquiry form on this page, call us on +91 97126 22288, or message us on WhatsApp. Our team will help you choose the nearest centre and a convenient time.": { hi: "इस पेज पर पूछताछ फॉर्म भरें, हमें +91 97126 22288 पर कॉल करें, या व्हाट्सऐप पर संदेश भेजें। हमारी टीम आपको नज़दीकी सेंटर और सुविधाजनक समय चुनने में मदद करेगी।", gu: "આ પેજ પર પૂછપરછ ફોર્મ ભરો, અમને +91 97126 22288 પર કૉલ કરો, અથવા વોટ્સએપ પર સંદેશ મોકલો. અમારી ટીમ તમને નજીકનું સેન્ટર અને અનુકૂળ સમય પસંદ કરવામાં મદદ કરશે." },
  "Which Bavishi Fertility Institute centre is nearest to me?": { hi: "मेरे सबसे नज़दीक कौन सा Bavishi Fertility Institute सेंटर है?", gu: "મારી સૌથી નજીક કયું Bavishi Fertility Institute સેન્ટર છે?" },
  "We have 14 centres across 8 cities — Ahmedabad, Mumbai, Vadodara, Surat, Bhuj, Bhavnagar, Anand and Varanasi. Tell us your city and we'll connect you to the closest one.": { hi: "हमारे 8 शहरों — अहमदाबाद, मुंबई, वडोदरा, सूरत, भुज, भावनगर, आनंद और वाराणसी — में 14 सेंटर हैं। हमें अपना शहर बताएं, हम आपको सबसे नज़दीकी सेंटर से जोड़ देंगे।", gu: "અમારા 8 શહેરો — અમદાવાદ, મુંબઈ, વડોદરા, સુરત, ભુજ, ભાવનગર, આણંદ અને વારાણસી — માં 14 સેન્ટર છે. અમને તમારું શહેર જણાવો, અમે તમને સૌથી નજીકના સેન્ટર સાથે જોડીશું." },
  "Do you offer free consultations?": { hi: "क्या आप मुफ़्त कंसल्टेशन देते हैं?", gu: "શું તમે મફત કન્સલ્ટેશન આપો છો?" },
  "We understand that choosing the right fertility clinic is an important decision. To ensure every couple receives dedicated time, expert guidance, and a personalised evaluation, our consultations are not offered free of charge. However, we periodically offer special free consultation slots as part of limited-time programs. Please contact us to check current availability.": { hi: "हम समझते हैं कि सही फर्टिलिटी क्लिनिक चुनना एक महत्वपूर्ण निर्णय है। हर कपल को समर्पित समय, विशेषज्ञ मार्गदर्शन और व्यक्तिगत मूल्यांकन मिले, इसके लिए हमारे कंसल्टेशन मुफ़्त नहीं हैं। हालांकि, हम समय-समय पर सीमित अवधि के कार्यक्रमों के तहत विशेष मुफ़्त कंसल्टेशन स्लॉट भी देते हैं। वर्तमान उपलब्धता जानने के लिए कृपया हमसे संपर्क करें।", gu: "અમે સમજીએ છીએ કે યોગ્ય ફર્ટિલિટી ક્લિનિક પસંદ કરવો એ મહત્વનો નિર્ણય છે. દરેક કપલને સમર્પિત સમય, નિષ્ણાત માર્ગદર્શન અને વ્યક્તિગત મૂલ્યાંકન મળે તે માટે, અમારા કન્સલ્ટેશન મફત આપવામાં આવતા નથી. જોકે, અમે સમયાંતરે મર્યાદિત-સમયના કાર્યક્રમો હેઠળ ખાસ મફત કન્સલ્ટેશન સ્લોટ ઓફર કરીએ છીએ. હાલની ઉપલબ્ધતા ચકાસવા કૃપા કરી અમારો સંપર્ક કરો." },
  "Do you treat international patients?": { hi: "क्या आप अंतरराष्ट्रीय मरीज़ों का इलाज करते हैं?", gu: "શું તમે આંતરરાષ્ટ્રીય દર્દીઓની સારવાર કરો છો?" },
  "Yes — 300+ international patients choose Bavishi Fertility Institute every year. We provide end-to-end support including treatment planning and coordination across our 14 centres.": { hi: "हाँ — हर साल 300+ अंतरराष्ट्रीय मरीज़ Bavishi Fertility Institute चुनते हैं। हम अपने 14 सेंटरों में उपचार योजना और समन्वय सहित संपूर्ण सहायता प्रदान करते हैं।", gu: "હા — દર વર્ષે 300+ આંતરરાષ્ટ્રીય દર્દીઓ Bavishi Fertility Institute પસંદ કરે છે. અમે અમારા 14 સેન્ટરમાં સારવાર આયોજન અને સંકલન સહિત સંપૂર્ણ સહાય પૂરી પાડીએ છીએ." },

  // IVF Cost Calculator
  "Calculators": { hi: "कैलकुलेटर", gu: "કેલ્ક્યુલેટર" },
  "Transparent Estimates · No Hidden Surprises": { hi: "पारदर्शी अनुमान · कोई छिपा हुआ आश्चर्य नहीं", gu: "પારદર્શક અંદાજ · કોઈ છુપું આશ્ચર્ય નહીં" },
  "Free Tool": { hi: "मुफ़्त टूल", gu: "મફત ટૂલ" },
  "Instant Results": { hi: "तुरंत परिणाम", gu: "તાત્કાલિક પરિણામ" },
  "No Data Stored": { hi: "कोई डेटा सेव नहीं होता", gu: "કોઈ ડેટા સેવ થતો નથી" },
  "Typical IVF cycle cost": { hi: "सामान्य IVF साइकल लागत", gu: "સામાન્ય IVF સાયકલ ખર્ચ" },
  "Average cycles for success": { hi: "सफलता के लिए औसत साइकल", gu: "સફળતા માટે સરેરાશ સાયકલ" },
  "Success rate with right protocol": { hi: "सही प्रोटोकॉल के साथ सफलता दर", gu: "યોગ્ય પ્રોટોકોલ સાથે સફળતા દર" },
  "How This Calculator Works": { hi: "यह कैलकुलेटर कैसे काम करता है", gu: "આ કેલ્ક્યુલેટર કેવી રીતે કામ કરે છે" },
  "Transparent cost estimates based on Bavishi Fertility Institute pricing ranges.": { hi: "Bavishi Fertility Institute की मूल्य सीमाओं पर आधारित पारदर्शी लागत अनुमान।", gu: "Bavishi Fertility Institute ની કિંમત શ્રેણી પર આધારિત પારદર્શક ખર્ચ અંદાજ." },
  "Choose Your IVF Type": { hi: "अपना IVF प्रकार चुनें", gu: "તમારો IVF પ્રકાર પસંદ કરો" },
  "Select from Standard IVF, ICSI, Frozen Embryo Transfer, or Donor Egg IVF — each with different base costs.": { hi: "स्टैंडर्ड IVF, ICSI, फ्रोज़न एम्ब्रियो ट्रांसफर, या डोनर एग IVF में से चुनें — हर एक की बेस लागत अलग है।", gu: "સ્ટાન્ડર્ડ IVF, ICSI, ફ્રોઝન એમ્બ્રિયો ટ્રાન્સફર, અથવા ડોનર એગ IVF માંથી પસંદ કરો — દરેકની બેઝ કિંમત અલગ છે." },
  "Select Add-Ons": { hi: "ऐड-ऑन चुनें", gu: "એડ-ઓન પસંદ કરો" },
  "Add optional procedures like PGT-A, embryo freezing, ERA, or laser hatching that apply to your situation.": { hi: "PGT-A, एम्ब्रियो फ्रीज़िंग, ERA, या लेज़र हैचिंग जैसी वैकल्पिक प्रक्रियाएं जोड़ें जो आपकी स्थिति पर लागू होती हैं।", gu: "PGT-A, એમ્બ્રિયો ફ્રીઝિંગ, ERA, અથવા લેસર હેચિંગ જેવી વૈકલ્પિક પ્રક્રિયાઓ ઉમેરો જે તમારી સ્થિતિ પર લાગુ પડે છે." },
  "Set Number of Cycles": { hi: "साइकल की संख्या तय करें", gu: "સાયકલની સંખ્યા સેટ કરો" },
  "Planning for 1 cycle, or budgeting for 2–3? Adjust and see how the total investment changes.": { hi: "1 साइकल की योजना बना रहे हैं, या 2–3 के लिए बजट बना रहे हैं? समायोजित करें और देखें कि कुल निवेश कैसे बदलता है।", gu: "1 સાયકલનું આયોજન કરી રહ્યા છો, કે 2–3 માટે બજેટ બનાવી રહ્યા છો? એડજસ્ટ કરો અને જુઓ કુલ રોકાણ કેવી રીતે બદલાય છે." },
  "Get Your Estimate": { hi: "अपना अनुमान प्राप्त करें", gu: "તમારો અંદાજ મેળવો" },
  "See a transparent range for per-cycle and total cost, with a full line-item breakdown.": { hi: "प्रति साइकल और कुल लागत की पारदर्शी सीमा देखें, पूरी लाइन-आइटम ब्रेकडाउन के साथ।", gu: "પ્રતિ સાયકલ અને કુલ ખર્ચની પારદર્શક શ્રેણી જુઓ, સંપૂર્ણ લાઇન-આઇટમ બ્રેકડાઉન સાથે." },
  "Why Know Your Costs Upfront?": { hi: "अपनी लागत पहले से क्यों जानें?", gu: "તમારો ખર્ચ અગાઉથી શા માટે જાણવો?" },
  "Financial clarity removes one major stressor from your fertility journey.": { hi: "वित्तीय स्पष्टता आपकी फर्टिलिटी यात्रा से एक बड़ा तनाव दूर करती है।", gu: "નાણાકીય સ્પષ્ટતા તમારી ફર્ટિલિટી યાત્રામાંથી એક મોટો તણાવ દૂર કરે છે." },
  "No Unexpected Bills": { hi: "कोई अप्रत्याशित बिल नहीं", gu: "કોઈ અણધાર્યા બિલ નહીં" },
  "Know what to expect before you commit. Our estimates include medication ranges and common add-ons.": { hi: "प्रतिबद्ध होने से पहले जानें कि क्या उम्मीद करनी है। हमारे अनुमानों में दवा की सीमाएं और सामान्य ऐड-ऑन शामिल हैं।", gu: "કમિટ કરતા પહેલા જાણો શું અપેક્ષા રાખવી. અમારા અંદાજમાં દવાની શ્રેણી અને સામાન્ય એડ-ઓનનો સમાવેશ થાય છે." },
  "Plan Your Finances": { hi: "अपने वित्त की योजना बनाएं", gu: "તમારા નાણાંનું આયોજન કરો" },
  "Use the cost range to plan savings, explore EMI options, or check insurance coverage in advance.": { hi: "बचत की योजना बनाने, EMI विकल्प तलाशने, या पहले से बीमा कवरेज जांचने के लिए लागत सीमा का उपयोग करें।", gu: "બચતનું આયોજન કરવા, EMI વિકલ્પો શોધવા, અથવા અગાઉથી વીમા કવરેજ ચકાસવા માટે ખર્ચ શ્રેણીનો ઉપયોગ કરો." },
  "Compare Options": { hi: "विकल्पों की तुलना करें", gu: "વિકલ્પોની તુલના કરો" },
  "See how cycle type and add-ons affect your investment before making any decisions.": { hi: "कोई भी निर्णय लेने से पहले देखें कि साइकल प्रकार और ऐड-ऑन आपके निवेश को कैसे प्रभावित करते हैं।", gu: "કોઈપણ નિર્ણય લેતા પહેલા જુઓ સાયકલ પ્રકાર અને એડ-ઓન તમારા રોકાણને કેવી રીતે અસર કરે છે." },
  "Family Discussion Ready": { hi: "पारिवारिक चर्चा के लिए तैयार", gu: "કૌટુંબિક ચર્ચા માટે તૈયાર" },
  "Share a clear cost breakdown with your partner to make decisions together with full information.": { hi: "पूरी जानकारी के साथ मिलकर निर्णय लेने के लिए अपने पार्टनर के साथ स्पष्ट लागत ब्रेकडाउन साझा करें।", gu: "સંપૂર્ણ માહિતી સાથે મળીને નિર્ણય લેવા માટે તમારા પાર્ટનર સાથે સ્પષ્ટ ખર્ચ બ્રેકડાઉન શેર કરો." },
  "Prioritise Your Add-Ons": { hi: "अपने ऐड-ऑन को प्राथमिकता दें", gu: "તમારા એડ-ઓનને પ્રાધાન્ય આપો" },
  "Understand which add-ons are most cost-effective for your specific situation — ask your specialist.": { hi: "समझें कि आपकी विशिष्ट स्थिति के लिए कौन से ऐड-ऑन सबसे किफ़ायती हैं — अपने विशेषज्ञ से पूछें।", gu: "સમજો તમારી ચોક્કસ સ્થિતિ માટે કયા એડ-ઓન સૌથી કિફાયતી છે — તમારા નિષ્ણાતને પૂછો." },
  "Reduce Financial Anxiety": { hi: "वित्तीय चिंता कम करें", gu: "નાણાકીય ચિંતા ઘટાડો" },
  "Uncertainty about cost is one of the biggest barriers to seeking care. This calculator removes that barrier.": { hi: "लागत के बारे में अनिश्चितता देखभाल लेने में सबसे बड़ी बाधाओं में से एक है। यह कैलकुलेटर उस बाधा को दूर करता है।", gu: "ખર્ચ વિશે અનિશ્ચિતતા સંભાળ મેળવવામાં સૌથી મોટા અવરોધોમાંનો એક છે. આ કેલ્ક્યુલેટર તે અવરોધ દૂર કરે છે." },
  "Treatment Type": { hi: "उपचार प्रकार", gu: "સારવાર પ્રકાર" },
  "Type of IVF cycle": { hi: "IVF साइकल का प्रकार", gu: "IVF સાયકલનો પ્રકાર" },
  "Standard IVF": { hi: "स्टैंडर्ड IVF", gu: "સ્ટાન્ડર્ડ IVF" },
  "IVF with ICSI": { hi: "ICSI के साथ IVF", gu: "ICSI સાથે IVF" },
  "Frozen Embryo Transfer (FET)": { hi: "फ्रोज़न एम्ब्रियो ट्रांसफर (FET)", gu: "ફ્રોઝન એમ્બ્રિયો ટ્રાન્સફર (FET)" },
  "Donor Egg IVF": { hi: "डोनर एग IVF", gu: "ડોનર એગ IVF" },
  "Number of cycles": { hi: "साइकल की संख्या", gu: "સાયકલની સંખ્યા" },
  "1 cycle": { hi: "1 साइकल", gu: "1 સાયકલ" },
  "2 cycles": { hi: "2 साइकल", gu: "2 સાયકલ" },
  "3 cycles": { hi: "3 साइकल", gu: "3 સાયકલ" },
  "4+ cycles (budget planning)": { hi: "4+ साइकल (बजट योजना)", gu: "4+ સાયકલ (બજેટ આયોજન)" },
  "Add-Ons": { hi: "ऐड-ऑन", gu: "એડ-ઓન" },
  "(select all that apply)": { hi: "(जो लागू हों सभी चुनें)", gu: "(જે લાગુ પડે તે બધા પસંદ કરો)" },
  "Standard IVF (Base)": { hi: "स्टैंडर्ड IVF (आधार)", gu: "સ્ટાન્ડર્ડ IVF (બેઝ)" },
  "IVF + ICSI (Base)": { hi: "IVF + ICSI (आधार)", gu: "IVF + ICSI (બેઝ)" },
  "Frozen Embryo Transfer (Base)": { hi: "फ्रोज़न एम्ब्रियो ट्रांसफर (आधार)", gu: "ફ્રોઝન એમ્બ્રિયો ટ્રાન્સફર (બેઝ)" },
  "Donor Egg IVF (Base)": { hi: "डोनर एग IVF (आधार)", gu: "ડોનર એગ IVF (બેઝ)" },
  "PGT-A Genetic Testing": { hi: "PGT-A जेनेटिक टेस्टिंग", gu: "PGT-A જિનેટિક ટેસ્ટિંગ" },
  "Embryo Freezing & Storage": { hi: "एम्ब्रियो फ्रीज़िंग और स्टोरेज", gu: "એમ્બ્રિયો ફ્રીઝિંગ અને સ્ટોરેજ" },
  "Sperm Freezing": { hi: "स्पर्म फ्रीज़िंग", gu: "સ્પર્મ ફ્રીઝિંગ" },
  "ERA / Endometrial Testing": { hi: "ERA / एंडोमेट्रियल टेस्टिंग", gu: "ERA / એન્ડોમેટ્રિયલ ટેસ્ટિંગ" },
  "Laser Assisted Hatching": { hi: "लेज़र असिस्टेड हैचिंग", gu: "લેસર આસિસ્ટેડ હેચિંગ" },
  "Counselling Support": { hi: "काउंसलिंग सहायता", gu: "કાઉન્સેલિંગ સહાય" },
  "Calculate My IVF Cost": { hi: "मेरी IVF लागत की गणना करें", gu: "મારો IVF ખર્ચ ગણો" },
  "Recalculate": { hi: "फिर से गणना करें", gu: "ફરીથી ગણો" },
  "Estimated Total Investment": { hi: "अनुमानित कुल निवेश", gu: "અંદાજિત કુલ રોકાણ" },
  "For {cycles} cycle{s} including selected add-ons": { hi: "{cycles} साइकल के लिए, चुने गए ऐड-ऑन सहित", gu: "{cycles} સાયકલ માટે, પસંદ કરેલ એડ-ઓન સહિત" },
  "Cost Breakdown (per cycle)": { hi: "लागत ब्रेकडाउन (प्रति साइकल)", gu: "ખર્ચ બ્રેકડાઉન (પ્રતિ સાયકલ)" },
  "Total per cycle": { hi: "प्रति साइकल कुल", gu: "પ્રતિ સાયકલ કુલ" },
  "Get an Exact Quote": { hi: "सटीक कोट प्राप्त करें", gu: "ચોક્કસ ભાવ મેળવો" },
  "Book a consultation at Bavishi Fertility Institute for a precise, personalised cost plan based on your specific diagnosis.": { hi: "अपने विशिष्ट निदान के आधार पर सटीक, व्यक्तिगत लागत योजना के लिए Bavishi Fertility Institute में कंसल्टेशन बुक करें।", gu: "તમારા ચોક્કસ નિદાનના આધારે ચોક્કસ, વ્યક્તિગત ખર્ચ યોજના માટે Bavishi Fertility Institute પર કન્સલ્ટેશન બુક કરો." },
  "Explore EMI Options": { hi: "EMI विकल्प तलाशें", gu: "EMI વિકલ્પો શોધો" },
  "Ask about Bavishi Fertility Institute's flexible payment plans and medical finance options to spread your treatment costs.": { hi: "अपनी उपचार लागत फैलाने के लिए Bavishi Fertility Institute की लचीली भुगतान योजनाओं और मेडिकल फाइनेंस विकल्पों के बारे में पूछें।", gu: "તમારો સારવાર ખર્ચ ફેલાવવા માટે Bavishi Fertility Institute ની લવચીક ચુકવણી યોજનાઓ અને મેડિકલ ફાઇનાન્સ વિકલ્પો વિશે પૂછો." },
  "Review What's Included": { hi: "क्या शामिल है समीक्षा करें", gu: "શું સામેલ છે તે સમીક્ષા કરો" },
  "Always ask for a full itemised quote — medications, scans, blood tests, and lab fees can add significantly.": { hi: "हमेशा पूरी आइटमाइज़्ड कोट मांगें — दवाएं, स्कैन, ब्लड टेस्ट और लैब फीस काफी बढ़ सकती हैं।", gu: "હંમેશા સંપૂર્ણ આઇટમાઇઝ્ડ ભાવ માંગો — દવાઓ, સ્કેન, બ્લડ ટેસ્ટ અને લેબ ફી નોંધપાત્ર રીતે વધી શકે છે." },
  "Consider a Package Deal": { hi: "पैकेज डील पर विचार करें", gu: "પેકેજ ડીલ પર વિચાર કરો" },
  "Multi-cycle packages often offer better value. Ask Bavishi Fertility Institute about bundled pricing for 2–3 cycle commitments.": { hi: "मल्टी-साइकल पैकेज अक्सर बेहतर वैल्यू देते हैं। 2–3 साइकल प्रतिबद्धता के लिए बंडल्ड प्राइसिंग के बारे में Bavishi Fertility Institute से पूछें।", gu: "મલ્ટી-સાયકલ પેકેજ ઘણીવાર વધુ સારું મૂલ્ય આપે છે. 2–3 સાયકલ કમિટમેન્ટ માટે બંડલ્ડ પ્રાઇસિંગ વિશે Bavishi Fertility Institute ને પૂછો." },
  "* Cost estimates are indicative ranges for planning purposes only. Actual costs depend on your individual protocol, medications, and clinic. Request a full itemised quote at your consultation.": { hi: "* लागत अनुमान केवल योजना उद्देश्यों के लिए संकेतात्मक सीमाएं हैं। वास्तविक लागत आपके व्यक्तिगत प्रोटोकॉल, दवाओं और क्लिनिक पर निर्भर करती है। अपने कंसल्टेशन में पूरा आइटमाइज़्ड कोट मांगें।", gu: "* ખર્ચ અંદાજ ફક્ત આયોજન હેતુ માટે સૂચક શ્રેણી છે. વાસ્તવિક ખર્ચ તમારા વ્યક્તિગત પ્રોટોકોલ, દવાઓ અને ક્લિનિક પર આધારિત છે. તમારા કન્સલ્ટેશન પર સંપૂર્ણ આઇટમાઇઝ્ડ ભાવ માંગો." },
  "Using the cost calculator helped us budget properly for two cycles from the start. We weren't blindsided by any numbers — and that made the whole process less stressful.": { hi: "लागत कैलकुलेटर का उपयोग करने से हमें शुरू से ही दो साइकल के लिए सही ढंग से बजट बनाने में मदद मिली। हम किसी भी आंकड़े से हैरान नहीं हुए — और इससे पूरी प्रक्रिया कम तनावपूर्ण हो गई।", gu: "ખર્ચ કેલ્ક્યુલેટરનો ઉપયોગ કરવાથી અમને શરૂઆતથી જ બે સાયકલ માટે યોગ્ય રીતે બજેટ બનાવવામાં મદદ મળી. અમે કોઈપણ આંકડાથી ચોંક્યા નહીં — અને તેનાથી આખી પ્રક્રિયા ઓછી તણાવપૂર્ણ બની." },
  "— Patient at Bavishi Fertility Institute": { hi: "— Bavishi Fertility Institute में मरीज़", gu: "— Bavishi Fertility Institute ખાતે દર્દી" },
  "Who Should Use This Calculator?": { hi: "इस कैलकुलेटर का उपयोग किसे करना चाहिए?", gu: "આ કેલ્ક્યુલેટરનો ઉપયોગ કોણે કરવો જોઈએ?" },
  "Planning your first IVF cycle": { hi: "अपने पहले IVF साइकल की योजना बना रहे हैं", gu: "તમારા પ્રથમ IVF સાયકલનું આયોજન કરી રહ્યા છો" },
  "Get a realistic cost estimate before your first consultation so there are no surprises.": { hi: "अपने पहले कंसल्टेशन से पहले एक यथार्थवादी लागत अनुमान प्राप्त करें ताकि कोई आश्चर्य न हो।", gu: "તમારા પ્રથમ કન્સલ્ટેશન પહેલાં વાસ્તવિક ખર્ચ અંદાજ મેળવો જેથી કોઈ આશ્ચર્ય ન થાય." },
  "Budgeting for multiple cycles": { hi: "कई साइकल के लिए बजट बना रहे हैं", gu: "બહુવિધ સાયકલ માટે બજેટ બનાવી રહ્યા છો" },
  "See how total investment scales across 2–4 cycles and plan financially for the full journey.": { hi: "देखें कि 2–4 साइकल में कुल निवेश कैसे बढ़ता है और पूरी यात्रा के लिए वित्तीय योजना बनाएं।", gu: "જુઓ 2–4 સાયકલમાં કુલ રોકાણ કેવી રીતે વધે છે અને સંપૂર્ણ યાત્રા માટે નાણાકીય આયોજન કરો." },
  "Exploring financing options": { hi: "फाइनेंसिंग विकल्प तलाश रहे हैं", gu: "ફાઇનાન્સિંગ વિકલ્પો શોધી રહ્યા છો" },
  "Use the estimate to understand how much you need to save or borrow for EMI planning.": { hi: "EMI योजना के लिए आपको कितनी बचत या उधार लेने की आवश्यकता है, यह समझने के लिए अनुमान का उपयोग करें।", gu: "EMI આયોજન માટે તમારે કેટલી બચત અથવા ઉધાર લેવાની જરૂર છે તે સમજવા અંદાજનો ઉપયોગ કરો." },
  "Comparing treatment types": { hi: "उपचार प्रकारों की तुलना कर रहे हैं", gu: "સારવાર પ્રકારોની તુલના કરી રહ્યા છો" },
  "Switch between Standard IVF, ICSI, FET, and Donor Egg to compare costs before deciding.": { hi: "निर्णय लेने से पहले लागतों की तुलना करने के लिए स्टैंडर्ड IVF, ICSI, FET और डोनर एग के बीच स्विच करें।", gu: "નિર્ણય લેતા પહેલા ખર્ચની તુલના કરવા સ્ટાન્ડર્ડ IVF, ICSI, FET અને ડોનર એગ વચ્ચે સ્વિચ કરો." },
  "Understanding add-on costs": { hi: "ऐड-ऑन लागत को समझना", gu: "એડ-ઓન ખર્ચને સમજવું" },
  "See exactly how PGT-A, ERA, or other add-ons affect your total investment.": { hi: "ठीक-ठीक देखें कि PGT-A, ERA, या अन्य ऐड-ऑन आपके कुल निवेश को कैसे प्रभावित करते हैं।", gu: "બરાબર જુઓ PGT-A, ERA, અથવા અન્ય એડ-ઓન તમારા કુલ રોકાણને કેવી રીતે અસર કરે છે." },
  "Family financial planning": { hi: "पारिवारिक वित्तीय योजना", gu: "કૌટુંબિક નાણાકીય આયોજન" },
  "Share a clear, itemised estimate with your partner before making major treatment decisions.": { hi: "प्रमुख उपचार निर्णय लेने से पहले अपने पार्टनर के साथ एक स्पष्ट, आइटमाइज़्ड अनुमान साझा करें।", gu: "મોટા સારવાર નિર્ણયો લેતા પહેલા તમારા પાર્ટનર સાથે સ્પષ્ટ, આઇટમાઇઝ્ડ અંદાજ શેર કરો." },
  "What this calculator helps you do": { hi: "यह कैलकुलेटर आपकी क्या मदद करता है", gu: "આ કેલ્ક્યુલેટર તમને શું કરવામાં મદદ કરે છે" },
  "Budget Your Treatment": { hi: "अपने उपचार का बजट बनाएं", gu: "તમારી સારવારનું બજેટ બનાવો" },
  "Get indicative cost ranges for different IVF cycle types and add-on procedures.": { hi: "विभिन्न IVF साइकल प्रकारों और ऐड-ऑन प्रक्रियाओं के लिए संकेतात्मक लागत सीमाएं प्राप्त करें।", gu: "વિવિધ IVF સાયકલ પ્રકારો અને એડ-ઓન પ્રક્રિયાઓ માટે સૂચક ખર્ચ શ્રેણી મેળવો." },
  "See how cycle type and add-ons affect your total investment before booking.": { hi: "बुकिंग से पहले देखें कि साइकल प्रकार और ऐड-ऑन आपके कुल निवेश को कैसे प्रभावित करते हैं।", gu: "બુકિંગ પહેલા જુઓ સાયકલ પ્રકાર અને એડ-ઓન તમારા કુલ રોકાણને કેવી રીતે અસર કરે છે." },
  "Plan Financially": { hi: "वित्तीय रूप से योजना बनाएं", gu: "નાણાકીય રીતે આયોજન કરો" },
  "Use the estimates to explore EMI, insurance, and multi-cycle package options.": { hi: "EMI, बीमा और मल्टी-साइकल पैकेज विकल्पों का पता लगाने के लिए अनुमानों का उपयोग करें।", gu: "EMI, વીમા, અને મલ્ટી-સાયકલ પેકેજ વિકલ્પો શોધવા અંદાજનો ઉપયોગ કરો." },
  "Get a Precise Quote From Us": { hi: "हमसे सटीक कोट प्राप्त करें", gu: "અમારી પાસેથી ચોક્કસ ભાવ મેળવો" },
  "Get an exact cost plan for your IVF treatment at Bavishi Fertility Institute.": { hi: "Bavishi Fertility Institute में अपने IVF उपचार के लिए सटीक लागत योजना प्राप्त करें।", gu: "Bavishi Fertility Institute પર તમારી IVF સારવાર માટે ચોક્કસ ખર્ચ યોજના મેળવો." },
  "Our team will provide a full itemised quote, discuss flexible payment options, and help you plan the most cost-effective path to your goal.": { hi: "हमारी टीम पूरा आइटमाइज़्ड कोट देगी, लचीले भुगतान विकल्पों पर चर्चा करेगी, और आपके लक्ष्य के लिए सबसे किफ़ायती रास्ता बनाने में मदद करेगी।", gu: "અમારી ટીમ સંપૂર્ણ આઇટમાઇઝ્ડ ભાવ આપશે, લવચીક ચુકવણી વિકલ્પોની ચર્ચા કરશે, અને તમારા લક્ષ્ય માટે સૌથી કિફાયતી માર્ગ બનાવવામાં મદદ કરશે." },
  "WhatsApp Support": { hi: "व्हाट्सऐप सहायता", gu: "વોટ્સએપ સહાય" },
  "About This Calculator": { hi: "इस कैलकुलेटर के बारे में", gu: "આ કેલ્ક્યુલેટર વિશે" },
  "Frequently Asked Questions": { hi: "अक्सर पूछे जाने वाले सवाल", gu: "વારંવાર પુછાતા પ્રશ્નો" },

  // Calculator cross-links
  "Fertility Calculators To Plan Your Pregnancy Journey": { hi: "आपकी प्रेगनेंसी यात्रा की योजना बनाने के लिए फर्टिलिटी कैलकुलेटर", gu: "તમારી પ્રેગ્નન્સી યાત્રાનું આયોજન કરવા ફર્ટિલિટી કેલ્ક્યુલેટર" },
  "Use our expert-designed fertility calculators to estimate IVF success rates, track ovulation, understand your fertile window, and plan your journey to parenthood with confidence.": { hi: "IVF सफलता दर का अनुमान लगाने, ओव्यूलेशन ट्रैक करने, अपनी फर्टाइल विंडो समझने और आत्मविश्वास के साथ पेरेंटहुड की यात्रा की योजना बनाने के लिए हमारे विशेषज्ञ-डिज़ाइन किए गए फर्टिलिटी कैलकुलेटर का उपयोग करें।", gu: "IVF સફળતા દરનો અંદાજ કાઢવા, ઓવ્યુલેશન ટ્રેક કરવા, તમારી ફર્ટાઇલ વિન્ડો સમજવા, અને આત્મવિશ્વાસ સાથે પેરેન્ટહુડની યાત્રાનું આયોજન કરવા અમારા નિષ્ણાત-ડિઝાઇન કરેલા ફર્ટિલિટી કેલ્ક્યુલેટરનો ઉપયોગ કરો." },
  "IVF Success Rate Calculator": { hi: "IVF सफलता दर कैलकुलेटर", gu: "IVF સફળતા દર કેલ્ક્યુલેટર" },
  "Fertile Period Calculator": { hi: "फर्टाइल पीरियड कैलकुलेटर", gu: "ફર્ટાઇલ પીરિયડ કેલ્ક્યુલેટર" },
  "Risk of Repeat Miscarriage Calculator": { hi: "दोबारा मिसकैरेज के जोखिम का कैलकुलेटर", gu: "ફરીથી મિસકેરેજના જોખમનું કેલ્ક્યુલેટર" },
  "Natural Pregnancy Calculator": { hi: "नेचुरल प्रेगनेंसी कैलकुलेटर", gu: "નેચરલ પ્રેગ્નન્સી કેલ્ક્યુલેટર" },
  "IVF Cost Calculator": { hi: "IVF लागत कैलकुलेटर", gu: "IVF ખર્ચ કેલ્ક્યુલેટર" },
  "AMH Level Interpreter": { hi: "AMH लेवल इंटरप्रेटर", gu: "AMH લેવલ ઇન્ટરપ્રેટર" },
  "Ovulation Calculator": { hi: "ओव्यूलेशन कैलकुलेटर", gu: "ઓવ્યુલેશન કેલ્ક્યુલેટર" },
  "Semen Analysis Calculator": { hi: "सीमेन एनालिसिस कैलकुलेटर", gu: "સીમેન એનાલિસિસ કેલ્ક્યુલેટર" },
};

export function ui(key: string, locale: Locale): string {
  return locale === "en" ? key : UI_STRINGS[key]?.[locale] ?? key;
}
