/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    blogs: Blog;
    authors: Author;
    categories: Category;
    services: Service;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'contact-info': ContactInfo;
    'blog-hub': BlogHub;
    footer: Footer;
    header: Header;
    homepage: Homepage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'blog-hub': BlogHubSelect<false> | BlogHubSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path segment, e.g. 'contact' for /contact.
   */
  slug: string;
  hero?: {
    eyebrow?: string | null;
    /**
     * Heading text shown upright, e.g. 'Contact'.
     */
    lead?: string | null;
    /**
     * Heading text shown in italic emphasis, e.g. the brand name.
     */
    em?: string | null;
    subtitle?: string | null;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Open Graph title. Falls back to metaTitle if empty.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description. Falls back to metaDescription if empty.
     */
    ogDescription?: string | null;
    /**
     * Open Graph / social share image. Falls back to the default hero image if empty.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  /**
   * URL path segment → /blog/<slug>.
   */
  slug: string;
  /**
   * Card summary + meta description fallback.
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Who wrote the post.
   */
  author: number | Author;
  /**
   * Medical reviewer (optional). Phase 4: may point to a Doctor.
   */
  reviewedBy?: (number | null) | Author;
  category?: (number | null) | Category;
  /**
   * Estimated read time (minutes).
   */
  readMins?: number | null;
  /**
   * Display + schema datePublished. dateModified uses updatedAt.
   */
  publishedAt?: string | null;
  /**
   * Treatment slugs this post relates to (drives Related Blogs). Becomes a relationship in Phase 5.
   */
  treatmentSlugs?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Open Graph title. Falls back to metaTitle if empty.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description. Falls back to metaDescription if empty.
     */
    ogDescription?: string | null;
    /**
     * Open Graph / social share image. Falls back to the default hero image if empty.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * URL-safe id, e.g. 'dr-himanshu-bavishi'.
   */
  slug: string;
  /**
   * e.g. 'Fertility Specialist', 'Medical Content Writer'.
   */
  role?: string | null;
  /**
   * e.g. 'MD, FRCOG'.
   */
  credentials?: string | null;
  avatar?: (number | null) | Media;
  bio?: string | null;
  /**
   * schema.org sameAs — official/professional profile URLs.
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL-safe id, e.g. 'fertility-basics'.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * URL segment → /services/<slug>. Also the registry key.
   */
  slug: string;
  /**
   * Service card title.
   */
  name: string;
  /**
   * One-line card description (registry).
   */
  desc?: string | null;
  /**
   * Registry card icon.
   */
  icon?:
    | (
        | 'ScanLine'
        | 'Feather'
        | 'Baby'
        | 'Stethoscope'
        | 'ShieldCheck'
        | 'Users'
        | 'HeartPulse'
        | 'Activity'
        | 'ClipboardList'
        | 'CalendarCheck'
        | 'Eye'
        | 'Clock'
        | 'Microscope'
        | 'Sparkles'
        | 'Hand'
      )
    | null;
  /**
   * Canonical page URL, e.g. /services/3d-4d-sonography.
   */
  href?: string | null;
  /**
   * Gates the live, crawlable location→service link.
   */
  published?: boolean | null;
  /**
   * Where the card points until published.
   */
  fallback?: string | null;
  schemaType: 'MedicalProcedure' | 'MedicalTest' | 'MedicalTherapy';
  /**
   * Plain label used inside copy ("the scan").
   */
  shortName?: string | null;
  breadcrumbName?: string | null;
  /**
   * Doctor slug for the medical reviewer (becomes a relationship once Doctors migrate).
   */
  reviewerSlug?: string | null;
  /**
   * Review date, e.g. 2026-06-01.
   */
  lastReviewed?: string | null;
  hero?: {
    eyebrow?: string | null;
    h1?: string | null;
    /**
     * Italic emphasis word.
     */
    h1Em?: string | null;
    tagline?: string | null;
    badges?:
      | {
          badge: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Hero image path (an upload relation can replace this later).
     */
    image?: string | null;
    imageAlt?: string | null;
  };
  overview: {
    heading: {
      lead: string;
      /**
       * Italic emphasis fragment (optional).
       */
      em?: string | null;
    };
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional callout box.
     */
    aside?: {
      title?: string | null;
      body?: string | null;
    };
  };
  benefits: {
    heading: {
      lead: string;
      /**
       * Italic emphasis fragment (optional).
       */
      em?: string | null;
    };
    subtitle?: string | null;
    items?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  whoFor: {
    heading: {
      lead: string;
      /**
       * Italic emphasis fragment (optional).
       */
      em?: string | null;
    };
    subtitle?: string | null;
    items?:
      | {
          item: string;
          id?: string | null;
        }[]
      | null;
  };
  process: {
    heading: {
      lead: string;
      /**
       * Italic emphasis fragment (optional).
       */
      em?: string | null;
    };
    subtitle?: string | null;
    steps?:
      | {
          icon:
            | 'ScanLine'
            | 'Feather'
            | 'Baby'
            | 'Stethoscope'
            | 'ShieldCheck'
            | 'Users'
            | 'HeartPulse'
            | 'Activity'
            | 'ClipboardList'
            | 'CalendarCheck'
            | 'Eye'
            | 'Clock'
            | 'Microscope'
            | 'Sparkles'
            | 'Hand';
          /**
           * Title.
           */
          t: string;
          /**
           * Description.
           */
          d: string;
          id?: string | null;
        }[]
      | null;
    note?: string | null;
  };
  whyUs: {
    heading: {
      lead: string;
      /**
       * Italic emphasis fragment (optional).
       */
      em?: string | null;
    };
    items?:
      | {
          icon:
            | 'ScanLine'
            | 'Feather'
            | 'Baby'
            | 'Stethoscope'
            | 'ShieldCheck'
            | 'Users'
            | 'HeartPulse'
            | 'Activity'
            | 'ClipboardList'
            | 'CalendarCheck'
            | 'Eye'
            | 'Clock'
            | 'Microscope'
            | 'Sparkles'
            | 'Hand';
          /**
           * Title.
           */
          t: string;
          /**
           * Description.
           */
          d: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Optional explainer block — leave empty to hide.
   */
  infoNote?: {
    heading?: {
      lead?: string | null;
      /**
       * Italic emphasis fragment (optional).
       */
      em?: string | null;
    };
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  faqs?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Other service slugs/keys to cross-link.
   */
  related?:
    | {
        key: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Open Graph title. Falls back to metaTitle if empty.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description. Falls back to metaDescription if empty.
     */
    ogDescription?: string | null;
    /**
     * Open Graph / social share image. Falls back to the default hero image if empty.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Admin = full access (globals, users, structure). Editor = content only.
   */
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        lead?: T;
        em?: T;
        subtitle?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  author?: T;
  reviewedBy?: T;
  category?: T;
  readMins?: T;
  publishedAt?: T;
  treatmentSlugs?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  credentials?: T;
  avatar?: T;
  bio?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  desc?: T;
  icon?: T;
  href?: T;
  published?: T;
  fallback?: T;
  schemaType?: T;
  shortName?: T;
  breadcrumbName?: T;
  reviewerSlug?: T;
  lastReviewed?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        h1?: T;
        h1Em?: T;
        tagline?: T;
        badges?:
          | T
          | {
              badge?: T;
              id?: T;
            };
        image?: T;
        imageAlt?: T;
      };
  overview?:
    | T
    | {
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        aside?:
          | T
          | {
              title?: T;
              body?: T;
            };
      };
  benefits?:
    | T
    | {
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        subtitle?: T;
        items?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  whoFor?:
    | T
    | {
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        subtitle?: T;
        items?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  process?:
    | T
    | {
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        subtitle?: T;
        steps?:
          | T
          | {
              icon?: T;
              t?: T;
              d?: T;
              id?: T;
            };
        note?: T;
      };
  whyUs?:
    | T
    | {
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        items?:
          | T
          | {
              icon?: T;
              t?: T;
              d?: T;
              id?: T;
            };
      };
  infoNote?:
    | T
    | {
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  related?:
    | T
    | {
        key?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  alternateName?: string | null;
  legalName?: string | null;
  /**
   * Absolute logo URL used in schema. A Media relation can replace this later.
   */
  logoUrl?: string | null;
  /**
   * Year, e.g. 1984.
   */
  foundingDate?: string | null;
  /**
   * Canonical phone for tel: links + schema, e.g. +919712622288.
   */
  telephone?: string | null;
  /**
   * Formatted phone for on-page display, e.g. +91 97126 22288.
   */
  telephoneDisplay?: string | null;
  email?: string | null;
  /**
   * WhatsApp number digits for wa.me links, e.g. 919712622288.
   */
  whatsapp?: string | null;
  address?: {
    streetAddress?: string | null;
    addressLocality?: string | null;
    addressRegion?: string | null;
    postalCode?: string | null;
    /**
     * ISO country code, e.g. IN.
     */
    addressCountry?: string | null;
  };
  awards?:
    | {
        award: string;
        id?: string | null;
      }[]
    | null;
  /**
   * schema.org knowsAbout — areas of expertise.
   */
  knowsAbout?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  /**
   * schema.org sameAs — official profile URLs.
   */
  socialLinks?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  cards?:
    | {
        icon: 'Phone' | 'MessageCircle' | 'Mail' | 'Clock' | 'MapPin' | 'Calendar';
        /**
         * Label, e.g. 'Call Us'.
         */
        title: string;
        /**
         * Resolve value + link from Site Settings (single source of truth). 'None' keeps the value/link below (e.g. Working Hours).
         */
        channel?: ('none' | 'phone' | 'email' | 'whatsapp') | null;
        /**
         * Display value when channel = None (e.g. working hours), or display label for WhatsApp. Ignored for Phone/Email (resolved from Site Settings).
         */
        value?: string | null;
        /**
         * Link used when channel = None. Ignored for Phone/Email/WhatsApp (resolved from Site Settings).
         */
        href?: string | null;
        /**
         * Sub-line, e.g. '24×7 patient helpline'.
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-hub".
 */
export interface BlogHub {
  id: number;
  hero?: {
    /**
     * Hero heading. Empty keeps the default styled heading.
     */
    title?: string | null;
    /**
     * Hero sub-paragraph.
     */
    description?: string | null;
  };
  /**
   * Optional rich content shown beneath the hero, above the article grid.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Open Graph title. Falls back to metaTitle if empty.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description. Falls back to metaDescription if empty.
     */
    ogDescription?: string | null;
    /**
     * Open Graph / social share image. Falls back to the default hero image if empty.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Optional logo + blurb. Left empty keeps the footer visually identical.
   */
  branding?: {
    /**
     * Absolute logo URL. Empty hides the branding block.
     */
    logoUrl?: string | null;
    /**
     * Short blurb shown under the logo.
     */
    description?: string | null;
  };
  /**
   * Footer sitemap columns. Empty falls back to the built-in columns.
   */
  navGroups?:
    | {
        /**
         * Column heading, e.g. 'IVF Treatments'.
         */
        title: string;
        links?:
          | {
              label: string;
              /**
               * Resolve the link target from Site Settings (single source of truth). 'None' uses the URL below.
               */
              channel?: ('none' | 'phone' | 'email' | 'whatsapp') | null;
              /**
               * Link target when channel = None. Empty renders a non-clickable label.
               */
              url?: string | null;
              /**
               * Open in a new tab (rel=noopener).
               */
              external?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional social profiles. Empty keeps the footer visually identical.
   */
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'linkedin' | 'twitter';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Copyright owner line, rendered after '© <year> '. Empty uses the default.
   */
  copyrightText?: string | null;
  /**
   * Bottom row policy links. Empty falls back to the built-in links.
   */
  legalLinks?:
    | {
        label: string;
        /**
         * Empty renders a non-clickable label.
         */
        url?: string | null;
        /**
         * Open in a new tab (rel=noopener).
         */
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Logo shown in the header bar + mobile drawer. Left empty keeps the built-in logo.
   */
  branding?: {
    /**
     * Logo image URL (e.g. /assets/logo.png). Empty uses the default.
     */
    logoUrl?: string | null;
    /**
     * Logo alt text. Empty uses the default.
     */
    logoAlt?: string | null;
  };
  /**
   * Top-level navigation. Empty falls back to the built-in menu. A plain link uses 'Link URL'; a dropdown uses 'Mega columns'; tick 'Doctors panel' to render the auto-generated doctor menu.
   */
  navItems?:
    | {
        label: string;
        /**
         * Destination for a plain link. Leave empty when using mega columns or the Doctors panel.
         */
        url?: string | null;
        /**
         * Open this top-level link in a new tab (rel=noopener).
         */
        openInNewTab?: boolean | null;
        /**
         * Render the auto-generated, doctor-first mega panel (built from the Doctors list). Ignores the columns below.
         */
        doctors?: boolean | null;
        /**
         * Force the dropdown grid to N columns (optional — defaults to the number of columns).
         */
        megaCols?: number | null;
        /**
         * Dropdown columns. Leave empty for a plain link or the Doctors panel.
         */
        columns?:
          | {
              /**
               * Column heading. Empty renders an unlabelled column.
               */
              heading?: string | null;
              /**
               * Optional link for the heading (e.g. a city hub).
               */
              headingHref?: string | null;
              items?:
                | {
                    label: string;
                    url?: string | null;
                    /**
                     * Optional secondary line shown under the label.
                     */
                    desc?: string | null;
                    /**
                     * Optional nested links revealed under this item.
                     */
                    children?:
                      | {
                          label: string;
                          url?: string | null;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary call-to-action button (desktop bar + mobile drawer).
   */
  cta?: {
    /**
     * Button label. Empty uses the default ('Book Appointment').
     */
    label?: string | null;
    /**
     * Button target. Empty uses the default ('/#book').
     */
    url?: string | null;
    /**
     * Visual style. Only the primary style exists today.
     */
    styleVariant?: 'primary' | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * Top hero — copy only. The hero image stays code-owned (LCP-optimised).
   */
  hero?: {
    /**
     * Small label above the headline. Empty uses the default.
     */
    eyebrow?: string | null;
    /**
     * Full headline text. Empty keeps the default hero.
     */
    headline?: string | null;
    /**
     * The single word inside the headline rendered in the accent italic style.
     */
    headlineItalic?: string | null;
    /**
     * Sub-headline paragraph.
     */
    paragraph?: string | null;
    /**
     * Trust badges under the paragraph.
     */
    badges?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Up to three button labels (first is the primary button). Icons/order stay code-owned.
     */
    ctas?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Floating award chip text on the hero image.
     */
    floatingBadge?: string | null;
  };
  /**
   * Scrolling stats strip. Empty falls back to the built-in stats.
   */
  stats?:
    | {
        /**
         * Headline figure, e.g. '30,000+'.
         */
        value: string;
        /**
         * Caption under the figure.
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 'Why Bavishi Fertility Center' — the four icon cards.
   */
  whyBavishi?: {
    eyebrow?: string | null;
    /**
     * Section heading. Empty keeps the default.
     */
    heading?: {
      /**
       * Plain heading text before the highlighted word(s). Empty keeps the default heading.
       */
      lead?: string | null;
      /**
       * The highlighted (italic) word(s) at the end of the heading.
       */
      em?: string | null;
    };
    subtitle?: string | null;
    /**
     * Empty falls back to the built-in cards.
     */
    cards?:
      | {
          /**
           * Lucide icon name.
           */
          icon?:
            | (
                | 'ScanLine'
                | 'Feather'
                | 'Baby'
                | 'Stethoscope'
                | 'ShieldCheck'
                | 'Users'
                | 'HeartPulse'
                | 'Activity'
                | 'ClipboardList'
                | 'CalendarCheck'
                | 'Eye'
                | 'Clock'
                | 'Microscope'
                | 'Sparkles'
                | 'Hand'
              )
            | null;
          /**
           * Card title.
           */
          t: string;
          /**
           * Card description.
           */
          d: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * 'Why Choose Bavishi Fertility Institute?' — the Simple / Safe / Smart / Successful pillars.
   */
  whyChoose?: {
    eyebrow?: string | null;
    /**
     * Section heading. Empty keeps the default.
     */
    heading?: {
      /**
       * Plain heading text before the highlighted word(s). Empty keeps the default heading.
       */
      lead?: string | null;
      /**
       * The highlighted (italic) word(s) at the end of the heading.
       */
      em?: string | null;
    };
    subtitle?: string | null;
    /**
     * Empty falls back to the built-in pillars.
     */
    blocks?:
      | {
          /**
           * Pillar icon image URL, e.g. /assets/Simple-1.png.
           */
          icon?: string | null;
          /**
           * Icon alt text.
           */
          alt?: string | null;
          title: string;
          subtitle?: string | null;
          points?:
            | {
                /**
                 * Point heading.
                 */
                h: string;
                /**
                 * Point detail.
                 */
                d: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Suraksha Kavach section.
   */
  suraksha?: {
    /**
     * Pill label above the heading.
     */
    badge?: string | null;
    /**
     * Section heading. Empty keeps the default.
     */
    heading?: {
      /**
       * Plain heading text before the highlighted word(s). Empty keeps the default heading.
       */
      lead?: string | null;
      /**
       * The highlighted (italic) word(s) at the end of the heading.
       */
      em?: string | null;
    };
    paragraph?: string | null;
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Primary button.
     */
    primaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    /**
     * Secondary button.
     */
    secondaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    /**
     * Section image URL. Empty uses the default.
     */
    image?: string | null;
    imageAlt?: string | null;
  };
  /**
   * Awards & Recognition carousel.
   */
  awards?: {
    eyebrow?: string | null;
    /**
     * Section heading. Empty keeps the default.
     */
    heading?: {
      /**
       * Plain heading text before the highlighted word(s). Empty keeps the default heading.
       */
      lead?: string | null;
      /**
       * The highlighted (italic) word(s) at the end of the heading.
       */
      em?: string | null;
    };
    subtitle?: string | null;
    /**
     * Empty falls back to the built-in awards.
     */
    items?:
      | {
          /**
           * Award image URL.
           */
          img: string;
          title: string;
          /**
           * Sub-line under the award title.
           */
          desc?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Upcoming Events posters.
   */
  events?: {
    eyebrow?: string | null;
    /**
     * Section heading. Empty keeps the default.
     */
    heading?: {
      /**
       * Plain heading text before the highlighted word(s). Empty keeps the default heading.
       */
      lead?: string | null;
      /**
       * The highlighted (italic) word(s) at the end of the heading.
       */
      em?: string | null;
    };
    /**
     * Empty falls back to the built-in posters.
     */
    posters?:
      | {
          /**
           * Poster image URL.
           */
          src: string;
          alt: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * YouTube video IDs for the three video grids. Titles/headings stay code-owned.
   */
  videos?: {
    /**
     * Success-story videos. Empty falls back to the built-in set.
     */
    stories?:
      | {
          /**
           * YouTube video ID.
           */
          id: string;
          /**
           * Patient name.
           */
          n: string;
          /**
           * Quote.
           */
          q: string;
          /**
           * Star rating (1–5).
           */
          r?: number | null;
        }[]
      | null;
    /**
     * Educational videos. Empty falls back to the built-in set.
     */
    edu?:
      | {
          /**
           * YouTube video ID.
           */
          id: string;
          /**
           * Title.
           */
          t: string;
          /**
           * Description.
           */
          d: string;
        }[]
      | null;
    /**
     * Resource videos. Empty falls back to the built-in set.
     */
    resources?:
      | {
          /**
           * YouTube video ID.
           */
          id: string;
          /**
           * Category tag.
           */
          c: string;
          /**
           * Title.
           */
          t: string;
          /**
           * Byline / author.
           */
          date: string;
        }[]
      | null;
  };
  /**
   * Homepage FAQ accordion.
   */
  faq?: {
    eyebrow?: string | null;
    /**
     * Section heading. Empty keeps the default.
     */
    heading?: {
      /**
       * Plain heading text before the highlighted word(s). Empty keeps the default heading.
       */
      lead?: string | null;
      /**
       * The highlighted (italic) word(s) at the end of the heading.
       */
      em?: string | null;
    };
    /**
     * Empty falls back to the built-in FAQs.
     */
    items?:
      | {
          /**
           * Question.
           */
          q: string;
          /**
           * Answer.
           */
          a: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Closing call-to-action band.
   */
  finalCta?: {
    eyebrow?: string | null;
    /**
     * Section heading. Empty keeps the default.
     */
    heading?: {
      /**
       * Plain heading text before the highlighted word(s). Empty keeps the default heading.
       */
      lead?: string | null;
      /**
       * The highlighted (italic) word(s) at the end of the heading.
       */
      em?: string | null;
    };
    paragraph?: string | null;
    /**
     * Animated counters. Empty falls back to the built-in counters.
     */
    stats?:
      | {
          /**
           * Target value (counts up to this).
           */
          v: number;
          /**
           * Suffix, e.g. '+'.
           */
          s?: string | null;
          /**
           * Label.
           */
          l: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Up to three button labels. Icons/order stay code-owned.
     */
    ctas?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Open Graph title. Falls back to metaTitle if empty.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description. Falls back to metaDescription if empty.
     */
    ogDescription?: string | null;
    /**
     * Open Graph / social share image. Falls back to the default hero image if empty.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  alternateName?: T;
  legalName?: T;
  logoUrl?: T;
  foundingDate?: T;
  telephone?: T;
  telephoneDisplay?: T;
  email?: T;
  whatsapp?: T;
  address?:
    | T
    | {
        streetAddress?: T;
        addressLocality?: T;
        addressRegion?: T;
        postalCode?: T;
        addressCountry?: T;
      };
  awards?:
    | T
    | {
        award?: T;
        id?: T;
      };
  knowsAbout?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        channel?: T;
        value?: T;
        href?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-hub_select".
 */
export interface BlogHubSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  intro?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        logoUrl?: T;
        description?: T;
      };
  navGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              channel?: T;
              url?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyrightText?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        external?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        logoUrl?: T;
        logoAlt?: T;
      };
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        doctors?: T;
        megaCols?: T;
        columns?:
          | T
          | {
              heading?: T;
              headingHref?: T;
              items?:
                | T
                | {
                    label?: T;
                    url?: T;
                    desc?: T;
                    children?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        styleVariant?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        headlineItalic?: T;
        paragraph?: T;
        badges?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctas?:
          | T
          | {
              text?: T;
              id?: T;
            };
        floatingBadge?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  whyBavishi?:
    | T
    | {
        eyebrow?: T;
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        subtitle?: T;
        cards?:
          | T
          | {
              icon?: T;
              t?: T;
              d?: T;
              id?: T;
            };
      };
  whyChoose?:
    | T
    | {
        eyebrow?: T;
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        subtitle?: T;
        blocks?:
          | T
          | {
              icon?: T;
              alt?: T;
              title?: T;
              subtitle?: T;
              points?:
                | T
                | {
                    h?: T;
                    d?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  suraksha?:
    | T
    | {
        badge?: T;
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        paragraph?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        image?: T;
        imageAlt?: T;
      };
  awards?:
    | T
    | {
        eyebrow?: T;
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        subtitle?: T;
        items?:
          | T
          | {
              img?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  events?:
    | T
    | {
        eyebrow?: T;
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        posters?:
          | T
          | {
              src?: T;
              alt?: T;
              id?: T;
            };
      };
  videos?:
    | T
    | {
        stories?:
          | T
          | {
              id?: T;
              n?: T;
              q?: T;
              r?: T;
            };
        edu?:
          | T
          | {
              id?: T;
              t?: T;
              d?: T;
            };
        resources?:
          | T
          | {
              id?: T;
              c?: T;
              t?: T;
              date?: T;
            };
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        items?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
      };
  finalCta?:
    | T
    | {
        eyebrow?: T;
        heading?:
          | T
          | {
              lead?: T;
              em?: T;
            };
        paragraph?: T;
        stats?:
          | T
          | {
              v?: T;
              s?: T;
              l?: T;
              id?: T;
            };
        ctas?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}